### ISSUE TITLE
Add Motion Guidelines to Library Folder in Repo

### ISSUE THREAD

**Issue by ryanbrownhill** [IBM-Watson/design-library#114]
- [x] Add Images to img folder
- [x] Add Markdown File.

**Comment by ryanbrownhill** [comment]
@Snugug Where should I place this markdown file? Shouldn't there be a language folder inside of [library](https://github.com/IBM-Watson/design-library/tree/develop/library)?

**Comment by Snugug** [comment]
Was working on getting this in this morning, but didn't have internet to push. It'll be there later today as a stand alone folder

**Comment by joshkimmell** [comment]
@Ryan Are you writing cognitive-specific guidelines plus a motion guidelines intro?

**Comment by ryanbrownhill** [comment]
@joshkimmell I am working on a motion guidelines intro. That walks through how to create an animation on brand. As well as how to use the Sass Mixin' that's has been created for the sliding and other transitional animations. 

All the guidelines are around interface animation on a basic level. What do you mean when you say cognitive specific?

**Comment by ryanbrownhill** [comment]
@Snugug How do I submit my files to the repo? Also we need an `images` folder - how do you want that  setup? I tried by creating my own branch and then pushing but I don't have access. 

What is the typical workflow so I can contribute? Is there a resource you can point me to that walks me through this?

**Comment by Snugug** [comment]
You'll want to [fork this project](https://guides.github.com/activities/forking/), then do the branch and apply your updates from there. Once you've pushed the updates to your fork, you'll want to issue a pull request.

**Comment by ryanbrownhill** [comment]
Need #130 in order to further progress on this.

**Comment by ryanbrownhill** [comment]
@Snugug @joshkimmell  
Working with IBM Design on writing the guidelines. Currently the document I have are guides for people to create animations on brand. The problem is that the higher level information like: why include animation, where does this fit in my process, and what are the principles. 

The way IBM Design typically writes content for the site is through a small "committee." that Hayley puts together. Currently, this group is the motion designer from Idean and I but Hayley wants to bring some interaction designers on board (because motion is so closely tied to interaction)

Based on my conversation with Hayley these Guidelines are looking like:

- Intro why motion is important, etc.
- Explaining how to implement animation in the design process (If you have wireframes stage then you should do this to design for animation etc.)
- Principles
- Best Practices
- Foundations of Motion
- Building Blocks 
     -  My current document.

I can make a pull request for what I have but they would need to be updated later.
