### ISSUE TITLE
Design principles

### ISSUE THREAD

**Issue by bobbinrobyn** [IBM-Watson/design-library#116]
- [x] Write design principles
- [x] User test written principles
- [x] Choose headings/titles for principles
- [x] Prototype concepts for visual examples
- [x] User test visual examples
- [x] Synthesize research & iterate
- [x] Write short description for principles
- [x] Write intro paragraph for principles
- [x] Create final visual assets
- [x] Format text & media for production

**Comment by bobbinrobyn** [comment]
@Snugug: No rush, but when you get a chance, will you assign this to me?

**Comment by bobbinrobyn** [comment]
This won't all be done by March 24. Should I change the scope or do we want to push it to a later milestone?

**Comment by Snugug** [comment]
If it doesn't block other work we can push it to RC1 but not further than that

**Comment by joshkimmell** [comment]
That's fine... It shouldn't block. We need to have a formal review with Brad, though.

**Comment by bobbinrobyn** [comment]
After getting feedback from Brad, I brainstormed a few different ways to write the taglines. I'll pick back up on the visual examples on Friday, after our color decisions are wrapped up.

**Comment by bobbinrobyn** [comment]
Can we change this to in progress?

**Comment by bobbinrobyn** [comment]
![screen shot 2015-04-02 at 2 40 51 pm](https://cloud.githubusercontent.com/assets/9341504/6972039/a0a8ba32-d946-11e4-9ae7-7dc5d32d890c.png)
First few sketches of visual examples for the design principles. They're supposed to be pretty abstract. They could eventually have motion, if it makes sense for the content and would benefit our users.

**Comment by joshkimmell** [comment]
Hmmm... How are you imagining these in context? Maybe we could see that.

**Comment by bobbinrobyn** [comment]
Here's all the visuals I mocked up! I'll upload them by principle. 
![p1-01](https://cloud.githubusercontent.com/assets/9341504/6989323/d758a608-da1f-11e4-9437-1d323caa4b97.png)
![p1-02](https://cloud.githubusercontent.com/assets/9341504/6989319/d74e91a4-da1f-11e4-9cba-7c79593fac03.png)
![p1-03](https://cloud.githubusercontent.com/assets/9341504/6989320/d7553ea0-da1f-11e4-980b-fe27a01c917d.png)
![p1-04](https://cloud.githubusercontent.com/assets/9341504/6989321/d757a064-da1f-11e4-8a44-0a03ccae511d.png)
![p1-05](https://cloud.githubusercontent.com/assets/9341504/6989322/d75801b2-da1f-11e4-8953-db1fec9a5e9e.png)
![p1-06](https://cloud.githubusercontent.com/assets/9341504/6989324/d75da720-da1f-11e4-8e26-7d128ef38bec.png)
![p1-07](https://cloud.githubusercontent.com/assets/9341504/6989325/d767d8da-da1f-11e4-9326-5606fde28946.png)
![p1-08](https://cloud.githubusercontent.com/assets/9341504/6989326/d77f68f6-da1f-11e4-9ec5-5bc1ff9dc669.png)

**Comment by bobbinrobyn** [comment]
Principle 2: Inform Interactions
![p2-09](https://cloud.githubusercontent.com/assets/9341504/6989346/f7b1a9cc-da1f-11e4-9441-114f3cfd483c.png)
![p2-10](https://cloud.githubusercontent.com/assets/9341504/6989347/f7bf0946-da1f-11e4-82f6-c09b1a01a3f3.png)
![p2-11](https://cloud.githubusercontent.com/assets/9341504/6989349/f7c25556-da1f-11e4-8eb4-03f0b2bf7dad.png)
![p2-12](https://cloud.githubusercontent.com/assets/9341504/6989348/f7c25f88-da1f-11e4-98dd-ce9700091a27.png)

**Comment by bobbinrobyn** [comment]
*Principle 3: Offer Control*
![p3-13](https://cloud.githubusercontent.com/assets/9341504/6989363/17a7d530-da20-11e4-9d4f-73aa1d074a42.png)
![p3-14](https://cloud.githubusercontent.com/assets/9341504/6989364/17a8157c-da20-11e4-8b80-698b46b42106.png)
![p3-15](https://cloud.githubusercontent.com/assets/9341504/6989365/17aa434c-da20-11e4-9b06-260204fdbbf3.png)
![p3-16](https://cloud.githubusercontent.com/assets/9341504/6989366/17acb154-da20-11e4-9a00-6eca4ca32b43.png)
![p3-17](https://cloud.githubusercontent.com/assets/9341504/6989367/17ae9208-da20-11e4-8c57-6979da625dc9.png)

**Comment by bobbinrobyn** [comment]
There are many other things to consider, such as:
* What would these look like without a device in the image?
* How will we display multiple images for a sub-principle?
* What will the final copy be?
* If the image is showing a recommendation for copy, should there be an interface at all?
* Would it be helpful to use the same interface (e.g. the orange phone UI) for all of the sub-principles under one principle?

Feel free to give me your thoughts and suggestions. I made these images specifically to be able to test with users next week, so there will still be lots of iteration before they're final. And hopefully some visual design skillzzz from the talented @britanyponvelle and/or @poofichu.

**Comment by bobbinrobyn** [comment]
Thanks to @poofichu for making this rocking prototype! I'm user testing the principles this afternoon. http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/design_principles.html

**Comment by bobbinrobyn** [comment]
@Snugug & @kathrynmcelroy: Did y'all do a content model for this? Could y'all refresh my memory on how long the "short description" needs to be and an instance of where it might appear? Thanks!

**Comment by bobbinrobyn** [comment]
Is it the kind of thing that would appear in a call-out box when we reference a principle on another page?

**Comment by bobbinrobyn** [comment]
Unsynthesized user research is here: https://releaseblueprints.ibm.com/display/WDA/Design+Principles
Synthesis & a new iteration is coming in the morning!

**Comment by bobbinrobyn** [comment]
Copy for the principles has been updated in the wiki: https://github.com/IBM-Watson/design-library/wiki/Design-Principles

I'll add the synthesized research to the wiki ASAP.

**Comment by Snugug** [comment]
If copy is final, please work on getting it into a PR and out of the Wiki

**Comment by bobbinrobyn** [comment]
Okay, awesome. I'm meeting with @ryanbrownhill to make that happen.

**Comment by bobbinrobyn** [comment]
@channel: I added short descriptions and the intro paragraph to the design principles. I also tweaked the copy just a little bit. It would be great if you can read over these and give me any last feedback; otherwise, I'm going to call it done.

**Comment by bobbinrobyn** [comment]
https://github.com/IBM-Watson/design-library/wiki/Design-Principles

**Comment by bobbinrobyn** [comment]
This is where I'm heading with the final visuals for the principles. Any thoughts, @channel?
![p1-01](https://cloud.githubusercontent.com/assets/9341504/7048731/55c0078a-ddda-11e4-90fe-dd9d75f74222.png)
![p1-02](https://cloud.githubusercontent.com/assets/9341504/7048730/55beeada-ddda-11e4-91d0-c0f2e0bae868.png)
![p1-03](https://cloud.githubusercontent.com/assets/9341504/7048729/55be3626-ddda-11e4-86b4-9f9772740764.png)
![p1-04](https://cloud.githubusercontent.com/assets/9341504/7048732/55c083cc-ddda-11e4-98d3-6e8ff2925409.png)

**Comment by Snugug** [comment]
How does this all work responsively? I'd love to see us thinking more mobile-first with everything we're doing

**Comment by britanyponvelle** [comment]
If we added an indicator like (1) to the image and (1) to the caption, instead of a connecting line, we could move the caption underneath the visual example for small screens?

**Comment by poofichu** [comment]
@britanyponvelle FTW!  I love that idea.

**Comment by britanyponvelle** [comment]
I love the colors here @bobbinrobyn ! Very nice :)

**Comment by Snugug** [comment]
I'm concerned we're veering towards one-off pages for everything and will need to manage each of these by hand. That's a very tedious maintenance process and will make it harder to quickly and easily update content.

Let's get this in to browser and see what its like

**Comment by Snugug** [comment]
Always make sure you're referring to the [Content Models](https://github.com/IBM-Watson/design-library/wiki/Content-Models) and thinking about how we go from a representation of our content to the rendered view in a predictable way.

**Comment by kathrynmcelroy** [comment]
These look great! I really like how you've simplified and clarified the meaning. It's much easier to read and resize as needed. :+1:

**Comment by britanyponvelle** [comment]
I think we should keep the caption text same color as the others (instead of the teal)

**Comment by bobbinrobyn** [comment]
Thanks for all the feedback. To @Snugug's point about responsive, that's totally fair. The first round of images I did were designed mobile first, but didn't do well in user testing because they weren't particularly legible. So this second round was an attempt to improve readability. I'm going to try out @britanyponvelle's idea, which I think will work great!

**Comment by bobbinrobyn** [comment]
Here's an example of what a sub-principle might look like:

Clarify Watson’s capabilities with hierarchy, copy, and interactions to help set appropriate user expectations.

![p1-01](https://cloud.githubusercontent.com/assets/9341504/7051417/e536ddae-dded-11e4-9561-369a27f661ec.png)

Example: Clarify with content
1. "Remember that Chef Watson eats data, not real food. Use your own judgment when preparing these dishes."

**Comment by bobbinrobyn** [comment]
Provide intelligent defaults and positive feedback to reinforce cognitive behaviors and gradually adjust the user’s habits.

![p1-04](https://cloud.githubusercontent.com/assets/9341504/7051492/79db7a28-ddee-11e4-8213-d6183f39ef96.png)

Example: Set intelligent defaults
1. Based on the input data, this is a graph comparing REVENUE and TIME.
2. "Choose a different variable to plot."

**Comment by bobbinrobyn** [comment]
Okay - here are the final images. I'll also drop them in the wiki so you can see them in context.

Introduce Cognitive
![p1-01](https://cloud.githubusercontent.com/assets/9341504/7052399/ff704ac4-ddf3-11e4-816b-c9e1d5ac90c2.png)
![p1-02](https://cloud.githubusercontent.com/assets/9341504/7052401/ff70f474-ddf3-11e4-8620-4abe5346e3ca.png)
![p1-03](https://cloud.githubusercontent.com/assets/9341504/7052402/ff71a252-ddf3-11e4-86b5-6df1377846a9.png)
![p1-04](https://cloud.githubusercontent.com/assets/9341504/7052400/ff70d930-ddf3-11e4-803a-ee8d6484b2df.png)

Inform Interactions
![p2-05](https://cloud.githubusercontent.com/assets/9341504/7052403/ff71ee6a-ddf3-11e4-9826-08eba56fab7d.png)
![p2-06](https://cloud.githubusercontent.com/assets/9341504/7052406/ff7f63ce-ddf3-11e4-9a8d-de51c67c7ad6.png)
![p2-07](https://cloud.githubusercontent.com/assets/9341504/7052407/ff8044f6-ddf3-11e4-81b3-b99599fd9418.png)
![p2-08](https://cloud.githubusercontent.com/assets/9341504/7052404/ff7e725c-ddf3-11e4-9ad6-4322800a00d9.png)

Offer Control
![p3-09](https://cloud.githubusercontent.com/assets/9341504/7052408/ff80d2d6-ddf3-11e4-845b-be76b569bfb4.png)
![p3-10](https://cloud.githubusercontent.com/assets/9341504/7052405/ff7ed53a-ddf3-11e4-9545-1c028ccbf3c3.png)
![p3-11](https://cloud.githubusercontent.com/assets/9341504/7052409/ff8da204-ddf3-11e4-9c7b-3d5ded89f3dd.png)
![p3-12](https://cloud.githubusercontent.com/assets/9341504/7052410/ff8e18ec-ddf3-11e4-8fb2-31edfe073ea0.png)

**Comment by bobbinrobyn** [comment]
Wiki is updated with the final copy & images: https://github.com/IBM-Watson/design-library/wiki/Design-Principles. @poofichu is going to work with me tomorrow to get it into the prototype and I'll talk to @ryanbrownhill about doing a pull request.

**Comment by joshkimmell** [comment]
This looks great! @poofichu any chance of getting this into the prototype before 4pm today?

**Comment by poofichu** [comment]
Adorable comment @joshkimmell.  This will happen tomorrow.

**Comment by britanyponvelle** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
Unfortunately, not done :disappointed:

I'm going to redo the files so that each principle lives on its own page, given the decision we made about IA in #93. Then we should be good to review & close this today.

**Comment by bobbinrobyn** [comment]
Currently accepting ideas on where this paragraph should live:

*"Watson design principles are actionable guidelines that inform the design and development of cognitive software products, in order to provide consistently excellent experiences for users. They are meant to be applied in conjunction with the IBM Design Language best practices and principles. These design principles are explicitly related to Watson, but some principles may not apply to every use case."*

When all the principles lived on one page, this was at the top as an intro paragraph. I think it's still important content, but it shouldn't be repeated on every principles page. It could live just on the first principle's page, but now the title of the page is the name of the principle (i.e. "Introduce Cognitive"), so what heading would this paragraph go under?

Alternatively, could it live on the home page? Or do we need a whole "Introduction" page for the design principles?

**Comment by ryanbrownhill** [comment]
I am leaning toward homepage.

**Comment by bobbinrobyn** [comment]
@IBM-Watson/design-acceleration This is ready for :+1:!

**Comment by ryanbrownhill** [comment]
:+1: to me

**Comment by Snugug** [comment]
If we're going to have that kind of paragraph for principles on the homepage, we should have one for guidelines and UI patterns as well there.

**Comment by bobbinrobyn** [comment]
Yeah, upon further reflection, I don't think it should go on the homepage. @joshkimmell  has a good thing going with a one sentence, high-level overview of Principles on the homepage. So now I think the options are:

1. No paragraph
2. Display paragraph on the first principle's page ("Introduce Cognitive")
3. Display a shorter version of the paragraph on every page.
~~4. Display on the homepage~~
~~5. Display on a separate introduction page for Principles~~

We can test these this week.

**Comment by britanyponvelle** [comment]
I think the last sentence is the most important part of the paragraph 
> Watson design principles are actionable guidelines that inform the design and development of cognitive software products, in order to provide consistently excellent experiences for users. They are meant to be applied in conjunction with the IBM Design Language best practices and principles. **These design principles are explicitly related to Watson, but some principles may not apply to every use case.**

The other content is basically re-iterating the "Engage your users with cognitive experiences." section on the homepage, so I think we can leave it out. Perhaps we can include that sentence in each page as a type of disclaimer?

**Comment by britanyponvelle** [comment]
Or just as a paragraph.
