### ISSUE TITLE
Typeface Recommendations

### ISSUE THREAD

**Issue by una** [IBM-Watson/design-library#120]
I noticed on the wiki that @britanyponvelle is working on, **Helvetica Neue for IBM** is the default typeface we are promoting (https://github.com/IBM-Watson/design-library/wiki/Visual-Guidelines#helvetica-neue-for-ibm). We need to check in with the usability guidelines for this typeface, and answer the following questions:

**What are the limitations of the typeface? Can we use it online? Print? What are the boundaries? Who can use it?**

Keeping in mind this library is open source for developers to use, we've been moving forward with the web font **Open Sans** to avoid technical complications. These either need to be documented or a decision made for an open and widely-available typeface to be the default.

**Comment by britanyponvelle** [comment]
Since we are in the process of acquiring the rights and licensing for Helvetica Neue for IBM and will provide fall-backs in the guidelines we are currently working on writing in #98, can we close this issue?

**Comment by una** [comment]
#98 seems to encompass more but we can remove the tick mark for typography in that issue and pull that conversation into here

**Comment by britanyponvelle** [comment]
Okay that works. @joshkimmell can you move this to "In Progress" when you have a chance?

**Comment by britanyponvelle** [comment]
@joshkimmell do you have answers to the questions "What are the limitations of the typeface? Who can use it?" Are these things we should write in to the guidelines, or is a disclaimer enough? I'm not sure about this.

**Comment by britanyponvelle** [comment]
First Draft:

## Typography
Typography is the atomic element of interface design. It sets the visual tone for the Design Language across all manifestations. As a modern, clear and obvious manifestation of our capabilities, our typographic 
stack is straightforward and on-brand. Text is largely differentiated by nothing more than size and weight, keeping other properties the same or similar, differentiating only when necessary for the sake of clarity.

### Helvetica Neue for IBM
As a rule and wherever possible, the typeface of choice should be Helvetica Neue. It is the font of science and the information age, with a precision and a purposeful neutrality that commands respect. When objectivity is the goal, we lean on Helvetica Neue to do the hard work of conveying information. Its clean confidence makes it ideal for our product design.  
*We are currently in the process of inquiring about full usage rights and licensing for Helvetica Neue for IBM. During this time, we're unable to provide downloadable font assets. Please defer to the Cross-Platform Fontstack Options below for comparable fontstacks.*

**Visual Examples:**  
1. List of acceptable weights: roman, medium, bold, light, italic.

### Typographic Scale
IBM Watson uses modular type scales to create harmonious proportions and structure. Whenever possible, use a visual type scale to establish balance and determine relationships between font sizes.

**Resources:** IBM Design examples for typographic scale

### Cross-Platform Fontstack Options
Desktop or Browser: font-family: "Helvetica Neue for IBM", Helvetica, "Open Sans", Arial, sans-serif;  
iOS: font-family: "Helvetica Neue";  
Android options: font-family: "Roboto";

**Comment by britanyponvelle** [comment]
@kathrynmcelroy in your feedback you write, "Why is this Watson?" after the disclaimer about the acquisition of Helvetica license. What did you mean by that?

**Comment by kathrynmcelroy** [comment]
I meant the whole font section, not just the disclaimer. :)

**Comment by britanyponvelle** [comment]
@kathrynmcelroy ahh ok! Thanks

**Comment by britanyponvelle** [comment]
Draft v2:

## Typography
Typography is the vehicle that delivers content to interfaces. It sets the visual tone for the entire Watson experience. As a modern and clear display of our capabilities, our typographic stack is straightforward and on-brand. Text is largely differentiated by size and weight, keeping other properties the same or similar, differentiating only when necessary for the sake of clarity.

**Visual Examples:**
1. Helvetica Neue for IBM font stack code

### Helvetica Neue for IBM
As a rule and wherever possible, the typeface of choice should be Helvetica Neue. It is the font of science and the information age, with a precision and a purposeful neutrality that commands respect. Its clean confidence makes it ideal for our Watson product design.
*We are currently in the process of inquiring about full usage rights and licensing for Helvetica Neue for IBM. During this time, we're unable to provide downloadable font assets. Please defer to the Cross-Platform Fontstack Options below for comparable fontstacks.*

**Visual Examples:**
1. List of acceptable weights: roman, medium, bold, light, italic.

### Typographic Scale
IBM Watson uses modular type scales to create harmonious proportions and structure. Whenever possible, use a visual type scale to establish balance and determine relationships between font sizes.

**Visual Examples:**
1. Rendered h1, h2, h3 tags displaying type scale 

**Resources:** IBM Design examples for typographic scale

### Cross-Platform Fontstack Options
Desktop or Browser: font-family: "Helvetica Neue for IBM", Helvetica, "Open Sans", Arial, sans-serif;
Apple Watch: font-family: “San Francisco”; (add this? @una)
iOS: font-family: "Helvetica Neue";
Android options: font-family: "Roboto";

**Comment by poofichu** [comment]
@joshkimmel @una Are we still including Open Sans as an option in here?  From the research I did, the visual designers weren't so hot about it.

**Comment by una** [comment]
We need a web font alternative. Open Sans doesn't have to be the one, per se, but it does need to be something web compatible and openly available.

**Comment by poofichu** [comment]
Dat Arial tho?

**Comment by Snugug** [comment]
Also keep in mind that each weight and style we recommend needs to be downloaded (especially for Helvetica Neue for IBM). If we are recommending 4 weights each with obliques, that's 8 font files, which is about double what we should be limiting ourselves to.

**Comment by britanyponvelle** [comment]
I understand that they would need to be downloaded as individual font files, but is there another a way of displaying these options? For a project/ product we wouldn't recommend using all 4 of these together (which we can add into the recommendations), but each of these weights are available for use. The reason I was thinking of displaying them this way is because there are other weights of Helvetica we aren't recommending (Helvetica condensed, etc.)

**Comment by Snugug** [comment]
Maybe recommending weight pairs instead of just "these are the weights available"? Like Light/Medium and Regular/Bold? I also highly recommend using the actual font weights (in numbers) either as opposed to their names, or in conjunction with their names.

**Comment by britanyponvelle** [comment]
From @bobbinrobyn:  When we display our color palette, we will have our own Sass variables for each color. One of the Watson designers asked that we display each Sass variable along with the hex code and visual rendering of the color. I guess I'm just a little confused – isn't the user going to have to define their _own_ Sass variables when they use our colors? So is it helpful to them to see the way we've named ours?

**Comment by britanyponvelle** [comment]
Draft v2:

## Typography
Typography is the vehicle that delivers content to interfaces. It sets the visual tone for the entire Watson experience. Text is largely differentiated by size and weight, keeping other properties the same or similar, differentiating only when necessary for the sake of clarity.

### Helvetica Neue for IBM
Per IBM Design (link to IBM guidelines on typography): as a rule and wherever possible, use Helvetica Neue. It is the font of science and the information age, with a precision and objectivity that commands respect.  We lean on Helvetica Neue to do the hard work of conveying information, specifications and the basics. Its clean confidence makes it ideal for our product design. IBM Watson recommends choosing no more than 4 font weights per product.
*We are currently in the process of inquiring about full usage rights and licensing for Helvetica Neue for IBM. During this time, we're unable to provide downloadable font assets. Please defer to the Cross-Platform Fontstack Options below for comparable fontstacks.*

**Visual Examples:**  

![screen shot 2015-03-23 at 3 50 33 pm](https://cloud.githubusercontent.com/assets/9538528/6790304/baddcf34-d174-11e4-8568-97ba55992e54.png)

### Typographic Scale
IBM Watson uses the approved modular type scales recommended by the IBM Design Language to create harmonious proportions and structure. Whenever possible, use a visual type scale to establish balance and determine relationships between font sizes.

**Visual Examples:**
1. Rendered h1, h2, h3 tags displaying type scale  
![screen shot 2015-03-20 at 2 09 31 pm](https://cloud.githubusercontent.com/assets/9538528/6759041/e6403700-cf0a-11e4-8f2a-c74669483123.png) 

**Resources:** link to IBM Design for typographic scale

### Cross-Platform Fontstack Options
Desktop or Browser: font-family: "Helvetica Neue for IBM", Helvetica, "Open Sans", Arial, sans-serif;
Apple Watch: font-family: “San Francisco”; (add this? @una)
iOS: font-family: "Helvetica Neue";
Android options: font-family: "Roboto";

**Comment by britanyponvelle** [comment]
@joshkimmell @poofichu for the Typographic scale section, I was thinking of recommending wither the Major Third or the Perfect Fourth scale (instead of the Golden ratio). The increments for these two are under 1.5x, making the contrast less extreme. As always, the ultimate decision should be based on the content, but I think these are good staring points. 

Thoughts?

**Comment by joshkimmell** [comment]
Yah... that's good. Typo though... perfect *fourth*

**Comment by britanyponvelle** [comment]
Good eye!

**Comment by poofichu** [comment]
Bueno!

**Comment by bradbecker** [comment]
As much as it pains me to say it, we should consider removing Open Sans from the font stack. Helv N, Helv, and Arial are similar and os is not. The aspect ratio especially is different. Not to mention that it seems to draw the ire of ibm design.

**Comment by britanyponvelle** [comment]
Next steps:
- [ ] Get feedback from Watson team
- [ ] Get feedback from Studio team
- [ ] Add to branch
- [ ] Submit pull request

**Comment by britanyponvelle** [comment]
Draft v2:

## Typography
Typography is the vehicle that delivers content to interfaces. It sets the visual tone for the entire Watson experience. Text is largely differentiated by size and weight, keeping other properties the same or similar, differentiating only when necessary for the sake of clarity.

### Helvetica Neue for IBM
As a rule and wherever possible, use Helvetica Neue. It is the font of science and the information age, with a precision and objectivity that commands respect.  We lean on Helvetica Neue to do the hard work of conveying information, specifications and the basics. Its clean confidence makes it ideal for our product design. To ensure optimized performance for all users, IBM Watson recommends choosing no more than 4 font weights per product.
*We are currently in the process of inquiring about full usage rights and licensing for Helvetica Neue for IBM. During this time, we're unable to provide downloadable font assets. Please defer to the Cross-Platform Fontstack Options below for comparable fontstacks.*

**Visual Examples:**  

![screen shot 2015-03-23 at 3 50 33 pm](https://cloud.githubusercontent.com/assets/9538528/6790304/baddcf34-d174-11e4-8568-97ba55992e54.png)

### Typographic Scale
IBM Design Language recommends using modular type scales to create harmonious proportions and structure; IBM Watson uses a subset of those scales. Whenever possible, use Major Third or Perfect Forth to establish balance and determine relationships between font sizes.

**Resources:** link to IBM Design for typographic scale

### Cross-Platform Fontstack Options
Desktop or Browser: font-family: "Helvetica Neue for IBM", Helvetica, Arial, sans-serif;
Apple Watch: font-family: “San Francisco”; (add this? @una)
iOS: font-family: "Helvetica Neue";
Android options: font-family: "Roboto";

**Comment by britanyponvelle** [comment]
Two updates: 
- comment on why we recommend no more than 4 weights per product. @Snugug do you think we should add anything else to support this recommendation?
- took out recommendations for using the Major Third and Perfect Fourth, specifically. Instead, added a comment on having the content and browser size inform which scale to use. Thoughts on this @joshkimmell ?

### Helvetica Neue for IBM
As a rule and wherever possible, use Helvetica Neue. It is the font of science and the information age, with a precision and objectivity that commands respect.  We lean on Helvetica Neue to do the hard work of conveying information, specifications and the basics. Its clean confidence makes it ideal for our product design. To ensure optimized performance for all users, IBM Watson recommends choosing no more than 4 font weights per product.

### Typographic Scale
IBM Design Language recommends using modular type scales to create harmonious proportions and structure, as scale creates consistency in sizing across elements. A visual type scale turns a typographic balancing act into a set ratio. As a rule of thumb, the content and user's browser size should inform type scaling choices. IBM Watson recommends choosing breakpoints at which contrast begins to interrupt readability, and scale appropriately. 

**Resources:** link to IBM Design for typographic scale (http://www.ibm.com/design/language/framework/visual/typography.shtml)

**Comment by Snugug** [comment]
A couple of thoughts:

* We'll need a monospace font stack as well. I really love [Source Code Pro](http://adobe-fonts.github.io/source-code-pro/), but we need to find a font we like. We can slo use systems fonts, but we need a monospace font stack. For our monospace, we can add one (maybe two) additional font files. We should be clear that this is separate than the weights for Helvetica.
* Instead of `4 weight`, how about something like `4 combinations of weights and styles (light and light oblique being 2 separate combinations, for instance)`. 
* I think having recommend pairings of weights and styles would be beneficial.
* We should recommend a minimum font size (unless it's not already in the IDL)
* There's a conversation to have about including performance recommendations in the Design Principles section; if we choose to include one (I think we probably should), we can point to that as our justification for font weights/styles.

**Comment by britanyponvelle** [comment]
Pull request opened for typography guidelines #132

**Comment by britanyponvelle** [comment]
Source Code Pro looks nice. It's cleaner than [Courier New](http://www.prepressure.com/fonts/interesting/courier) and has curves that I think compliment Helvetica. 

>Monospace: font-family: 'Source Code Pro', Courier, monospace;

thoughts?

**Comment by Snugug** [comment]
I'd look for a monospace font that closely matches Source Code Pro so there aren't drastic styling shifts if that font isn't available.

**Comment by britanyponvelle** [comment]
To your other comments @Snugug : 

- IDL recommends using a minimum of 16 px/ 1 em as a base size, but I'm not sure if there is a hard rule for a minimum size.

-IDL lists recommendations for combining font weights. I feel like recommending style combinations might be too prescriptive. I think "4 combinations of weights and styles (light and light oblique being 2 separate combinations, for instance)." could be enough guidance ?

@poofichu @joshkimmell what do you think?

**Comment by britanyponvelle** [comment]
@Snugug I will add the monospace thing to my to do list

**Comment by Snugug** [comment]
@britanyponvelle 

* The base font size thing is an accessibility best practice. It's cool if we don't include it though as IDL does
* Correct me if I'm wrong, but it looks like the current content for this section has us prescribing 400 and 700 weight fonts, so I'm OK with not being a bit more prescriptive on choosing font weights. If not, something like "for best contrast, between two font weights, make sure their weights are at least 200 apart" or something like that. That would provide someone with the ability to choose, for instance, light with medium, light with bold, normal with bold, or medium with bold, but not light and normal or normal and medium.

**Comment by britanyponvelle** [comment]
Monaco seems to be closer than Courier:

>Monospace: font-family: 'Source Code Pro', Monaco, monospace;

I think recommending contrast that could solve the problem of sounding like we are dictating which weights to use, rather providing guidance to help someone choose the most appropriate weight. Sounds good to me!

Here is what I have updated:
----

## Typography
Typography is the vehicle that delivers content to interfaces. It sets the visual tone for the entire Watson experience. Text is largely differentiated by size and weight, keeping other properties the same or similar, differentiating only when necessary for the sake of clarity.

### Helvetica Neue for IBM
As a rule and wherever possible, use Helvetica Neue. It is the font of science and the information age, with a precision and objectivity that commands respect.  We lean on Helvetica Neue to do the hard work of conveying information, specifications and the basics. Its clean confidence makes it ideal for our product design. To ensure optimized performance for all users, IBM Watson recommends choosing no more than 4 combinations of weights and styles (light and light oblique being 2 separate combinations, for instance). For best contrast between two font weights, make sure their weights are at least 200 apart. 

*We are currently in the process of inquiring about full usage rights and licensing for Helvetica Neue for IBM. During this time, we're unable to provide downloadable font assets. Please defer to the Cross-Platform Fontstack Options below for comparable fontstacks.*

**Visual Examples:**  

![font-stack-example](https://cloud.githubusercontent.com/assets/9538528/6834864/d4d5925a-d304-11e4-8efb-0dfdd862b06f.png)

### Typographic Scale
IBM Design Language recommends using modular type scales to create harmonious proportions and structure, as scale creates consistency in sizing across elements. A visual type scale turns a typographic balancing act into a set ratio. As a rule of thumb, the content and user's browser size should inform type scaling choices. IBM Watson recommends choosing breakpoints at which contrast begins to interrupt readability, and scale appropriately. 


**Resources:** link to IBM Design for typographic scale (http://www.ibm.com/design/language/framework/visual/typography.shtml)

### Cross-Platform Fontstack Options
Desktop or Browser: font-family: "Helvetica Neue for IBM", Helvetica, Arial, sans-serif;  

Monospace: font-family: 'Source Code Pro', Monaco, monospace;

Apple Watch: font-family: “San Francisco”;

iOS: font-family: "Helvetica Neue";  

Android options: font-family: "Roboto";

**Comment by Snugug** [comment]
Looking good. Two thoughts: one, include Roboto in the browser font stack as well. Two, we should check to see where Monaco is available in order to ensure our font stack works as expected

**Comment by britanyponvelle** [comment]
Just wondering, why Roboto?

Monaco is only safe on Mac. Maybe we can add Lucida Console in the stack as well? It's a better backup than courier 
http://www.cssfontstack.com/

**Comment by Snugug** [comment]
Monaco looks a bit comic sans-ish to me? Either way.

Here are [all the standard fonts for all OSes](http://www.granneman.com/webdev/coding/css/fonts-and-formatting/default-fonts/) that can be used to help figure out a cross-browser cross-device font stack for our two font stacks.

The reason I recommend adding in Roboto is because Android doesn't come with Arial or Helvetica, but it comes with (<4.0) Droid Sans and (4.0+) Roboto. A user may choose to change their default sans-serif font, but if they get that far we probably want them using Roboto (or Droid Sans) so we should force that instead of whatever their theme has cooked up.

**Comment by britanyponvelle** [comment]
Thanks for the reference!  [Andale Mono]( v1.jontangerine.com) also seems to be safe for Mac, and it is closer to both [Lucida Console](http://www.cssfontstack.com/Lucida-Console) and Source Code Pro.

>Monospace: font-family: 'Source Code Pro', Lucida Console, Andale Mono, monospace;

thoughts? @joshkimmell @poofichu

**Comment by Snugug** [comment]
Resolved by #133

**Comment by britanyponvelle** [comment]
@Snugug for this part of the guideline: 
> To ensure optimized performance for all users, IBM Watson recommends choosing no more than 4 combinations of weights and styles (light and light oblique being 2 separate combinations, for instance).

Is there a resource you could point me to, so I can back this up? Some of the feedback I got is to provide more reasoning about why we are recommending certain things, so I would like to flesh this out a bit more.

**Comment by britanyponvelle** [comment]
![example-typeface-combinations](https://cloud.githubusercontent.com/assets/9538528/6945921/a0cf4678-d862-11e4-8bfe-6f911e123faf.png)

**Comment by Snugug** [comment]
@britanyponvelle Take a read of the [Performance Considerations](http://www.smashingmagazine.com/2013/05/17/typographic-design-patterns-practices-case-study-2013/) section of the Smashing Magazine Typographic Design Patterns Practices Case Study for 2013. Ultimately, it's a performance consideration and may actually change once I see just how heavy the Helvetica fonts are. Basically it comes down to weight and number of HTTP requests one wants to use on typography, and how that compares to the perceived performance of a site. We should probably also include in our typography guidelines that we recommend not displaying web fonts on a user's initial load of a page (downloading them asynchronously in the background) and on subsequent page views, loading in the custom font (we do this to prevent the flash of unstyled content and only serve web fonts to browsers that support the latest font standards, not a full potentially very heavy font stack)

This, however, speaks to a larger question about whether we should have performance guidelines as part of what we're doing; if so we'd be able to point there.

**Comment by britanyponvelle** [comment]
Great! Thank you. I'll work on this today.

**Comment by britanyponvelle** [comment]
To your last point:
>This, however, speaks to a larger question about whether we should have performance guidelines as part of what we're doing; if so we'd be able to point there.

I think we at least need a "web font performance recommendations" section in Typography. Right now, we have that group into the "Helvetica Neue for IBM" section, and I feel like it should be separated.

**Comment by Snugug** [comment]
Cool, I can type that up and issue a PR for you to look over; probably Friday given my schedule.

**Comment by britanyponvelle** [comment]
Oh great! I started something... but struggling pretty hard lol.

"### Performance Considerations  
When presenting large amounts of content, it is important to consider how multiple font downloads can effect the browser’s performance for your user. Every weight and style of Helvetica Neue requires a separate download. IBM Watson recommends choosing no more than 4 combinations of weights and styles (light and light oblique being 2 separate combinations, for instance)."

**Comment by britanyponvelle** [comment]
I like your idea better!
