### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by joshkimmell** [IBM-Watson/design-library#121]
- [x] Watson Intro copy
- [x] Getting Started user flow (if any for v.1.0.0)
- [x] Write lil' blurb for UI Patterns
- [ ] Issue PR to bring it in to the Library

**Comment by bobbinrobyn** [comment]
I brainstormed a little bit on the copy! https://github.com/IBM-Watson/design-library/wiki/Intro-to-WDL

**Comment by kathrynmcelroy** [comment]
Love it! My only minor idea is to change the second paragraph "provide a coherent brand experience" into "provide a coherent user experiences" because it's more about our products being coherent together than the generalized brand.

**Comment by britanyponvelle** [comment]
Here are some examples from a SxSW talk I went to: http://firsttimeux.tumblr.com/ :)

**Comment by joshkimmell** [comment]
![getting_started_v2](https://cloud.githubusercontent.com/assets/8161298/6988208/962f9ba6-da14-11e4-8fac-1c08aaa06773.jpg)

Working on a mockup for responsive... although I'm more concerned with the flow.

**Comment by joshkimmell** [comment]
is this still too removed from the rest of the site? Since the side navigation is missing... I also think we can simplify the opening paragraph considerably.

**Comment by bobbinrobyn** [comment]
I think the hierarchy of the information is spot-on :+1:

I don't think think the side nav can just go missing, but I bet you can integrate this layout into what we already have designed.

I don't love those 3 "Get Started" buttons. What if we eliminated them, and instead just made each of those headings a link to its respective section?

**Comment by kathrynmcelroy** [comment]
I think the Introduction section should be better integrated in the "Principles" section, including having the navigation. It's not just a splash page, it's the first sub-section of the "Principles" section.

I don't think we need to spell out what each of the sections are; in user testing the IA and navigation, almost everyone could easily distinguish between "Principles" and "Guidelines". What we do need is a brief introduction to what Watson is, in addition to the intro on the Design Guide (the "Meet Watson" section of the earlier content)

**Comment by kathrynmcelroy** [comment]
It should also have the "Next" button on the bottom that directs the user on to the "Values", which is the next sub-section.

**Comment by bobbinrobyn** [comment]
Agreed @kathrynmcelroy. That came up in user testing as a demonstrated need - at least one or two sentences to explain what Watson/cognitive is.

**Comment by kathrynmcelroy** [comment]
The middle is completely open for content/design, but here's what the bottom should look like from Jessica's mock-up: http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/index.html

**Comment by joshkimmell** [comment]
Next button: totally agree. I just wanted to get the content in.

**Comment by kathrynmcelroy** [comment]
Based on this mockup, did we decide to move "Values" to its own page? Or will it be added to this introduction page to further introduce "cognitive/Watson" to the users?

**Comment by joshkimmell** [comment]
So... Here's the hierarchy as I believe we understand it:
# Introduce Watson (cognitive)
# Introduce the Design Guide
# Explain how to use the Guide???
# Explain how to use the UI Patterns???
# Provide clear calls to action???

**Comment by joshkimmell** [comment]
Whoa... I need to re-learn markdown.

**Comment by joshkimmell** [comment]
2.5. Watson Design Values???

**Comment by kathrynmcelroy** [comment]
The original hierarchy for this page was:
- Introduction to Watson
- Introduction to Design Guide and why/how to use it
- Watson high-level values (however they end up, but currently Heroic, Helpful, and Humane)

Then it goes on to the "Next page:" of Design Principles, and later we'll add in the Personality page after that, all within the Principles section

What kind of calls to action do we need? If our goal is to have users read through all the Principles on first visit, then our main call to action is for them to proceed on to the next page, otherwise I think the users will click into the section they need if it's not their first time.

**Comment by joshkimmell** [comment]
Okay... I can work with that, but one thing I think we're missing is the instructions for devs to use the patterns.

**Comment by joshkimmell** [comment]
Okay... here's where I'm leaving it today. Let's discuss more on Monday. Have a good weekend!!!

![getting_started_v3](https://cloud.githubusercontent.com/assets/8161298/6989091/6389c330-da1d-11e4-9d7f-a76bb74cd884.jpg)

**Comment by kathrynmcelroy** [comment]
@joshkimmell Looking great!

Could the dev instructions live on the UI Pattern page? With additional information about how to use each type of pattern on that pattern type's page. We can discuss further on Monday.

**Comment by joshkimmell** [comment]
Yes, they could. Thanks!

**Comment by joshkimmell** [comment]
![getting_started_v4](https://cloud.githubusercontent.com/assets/8161298/7013026/87bb03bc-dc7b-11e4-9bac-d7df5fb7c5d7.jpg)

**Comment by britanyponvelle** [comment]
The centered text on this page feels disconnected from the other pages (since we don't center text anywhere else). Also, I don't know if the bolded text in the titles adds value here. Since the text is set in an H tag, I think that could be enough distinction from the body text. Especially in "Meet Watson", because it almost looks like we are recreating the logo with the regular paired with bold Helvetica.

**Comment by joshkimmell** [comment]
![getting_started_v5](https://cloud.githubusercontent.com/assets/8161298/7070020/c8188402-dea1-11e4-87da-cf8b3fdb2513.jpg)

Another take on this based on some feedback.

**Comment by britanyponvelle** [comment]
@joshkimmell are you proposing the logotype in the nav bar and the extended underline?

**Comment by britanyponvelle** [comment]
@joshkimmell are you proposing the logotype in the nav bar and the extended underline?

A few thoughts:

- I think the orange in the logotype looks off here because IBM and the logo seem like a separate element than "Watson Design Guide." 
-  the `aside` treatment makes sense for the links if we don't want it to be the focus of the page, rather additional material.
- The logo on top of "Meet Watson" still feels too close to the example of what not to do for logo reconfiguration. I think this is because of the title. If you switch "Meet" with "IBM" it is pretty much our wordmark. Perhaps we can think of a different title, or not use the logo?

**Comment by ryanbrownhill** [comment]
I agree with @britanyponvelle on all those points.

 Specifically I have concern with the current treatment of the "Meet Watson" its too similar to this:
![screen shot 2015-04-09 at 4 25 11 pm](https://cloud.githubusercontent.com/assets/9538395/7077297/41b01d38-ded5-11e4-8882-fdb556eca5f4.png)

What I recommend doing is using the entire logo and have a subtitle under it.

**Comment by britanyponvelle** [comment]
Maybe "Design Watson Experiences" ?

**Comment by britanyponvelle** [comment]
here is a quick mock up of what I mean:
(with the watermark version for the graphic maybe?)

![screen shot 2015-04-09 at 5 11 49 pm](https://cloud.githubusercontent.com/assets/9538528/7078137/170825ce-dedc-11e4-86fb-eff068d15c60.png)
![screen shot 2015-04-09 at 5 11 33 pm](https://cloud.githubusercontent.com/assets/9538528/7078140/19070c6e-dedc-11e4-9b34-f91d6ef488f2.png)

**Comment by joshkimmell** [comment]
Ooh... I like the direction. Let's talk about this tomorrow.

**Comment by ryanbrownhill** [comment]
I like where it is headed - I think it's a little too dark - lower the
opacity on it?

On Thursday, April 9, 2015, Britany Ponvelle <notifications@github.com>
wrote:

> here is a quick mock up of what I mean:
> (with the watermark version for the graphic maybe?)
>
> [image: screen shot 2015-04-09 at 5 11 49 pm]
> <https://cloud.githubusercontent.com/assets/9538528/7078137/170825ce-dedc-11e4-86fb-eff068d15c60.png>
> [image: screen shot 2015-04-09 at 5 11 33 pm]
> <https://cloud.githubusercontent.com/assets/9538528/7078140/19070c6e-dedc-11e4-9b34-f91d6ef488f2.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IBM-Watson/design-library/issues/121#issuecomment-91369896>
> .
>


-- 
-Ryan G. Brownhill
ryanbrownhill.com
ryanbrownhill@gmail.com

**Comment by joshkimmell** [comment]
1. I agree with Ryan, maybe match the background color of the left nav?
2. I'm concerned that it's taking up a LOT of space for very little benefit. 
3. Would this also be breaking our logo guidelines? Or could be construed as doing this?

![image](https://cloud.githubusercontent.com/assets/8161298/7088510/cc839b40-df59-11e4-96d3-07618135cf67.png)

**Comment by britanyponvelle** [comment]
For this we would have to use the watermark version (which I don't have, so I just left the logo for now). As I understand it the watermark is meant to be cropped, so this wouldn't be breaking any rules. Agreed that it's taking up quite a bit of space right now. Do you think moving it up would help, or do you think the watermark wouldn't work?

Here is one more idea: (We would use the watermark here as well)

![wdg-intro-16](https://cloud.githubusercontent.com/assets/9538528/7088815/8d8511c8-df5c-11e4-9846-9c1a856aa23b.png)

![wdg-intro-17](https://cloud.githubusercontent.com/assets/9538528/7088819/91897d5e-df5c-11e4-93c6-cb2db6cb295c.png)

**Comment by joshkimmell** [comment]
This is interesting! It definitely looks more like a watermark and I like the contrast on the page... it makes the design more interesting. However, it introduces a new theme for the entire site (we shouldn't be creating one-off designs... remember, we're building a design system, so this would change the content model), which is fine if we choose to go in this direction. Would we expand this design to the rest of the site?

**Comment by joshkimmell** [comment]
![getting_started_v6](https://cloud.githubusercontent.com/assets/8161298/7089316/94534836-df60-11e4-85e7-f8646cc2a23d.jpg)

I added a little more color... Also, I feel like the subnav highlight (Teal 60) is too close to the grey body copy, so I changed to Teal 40. Thoughts?

**Comment by britanyponvelle** [comment]
If we are treating this as in intro page, I think it could be okay to have a hero image here. All of the other elements are the same, so I don't think switching to another page would be confusing.  Just a thought though!

@joshkimmell Teal 40 isn't accessible on the grey 10 background :(

**Comment by britanyponvelle** [comment]
With light grey instead of the dark:

![screen shot 2015-04-10 at 9 14 19 am](https://cloud.githubusercontent.com/assets/9538528/7089527/1424ad4c-df62-11e4-8c58-66c0d8188d18.png)

The title is more consistent, but the grey looks off next to the side nav. Not a huge fan of this.

**Comment by joshkimmell** [comment]
Let's talk about what needs to be accessible and what doesn't. The highlight bar (the little vertical teal bar to the left of the nav link) is a design element that I would argue doesn't need to be there, but it adds a small amount of value. I didn't change the text color, which absolutely needs to be accessible.

**Comment by britanyponvelle** [comment]
Ahhh I see now. I thought you meant you changed both the teal text and the bar to 40. (It's hard to tell from the photo that they are different)

**Comment by joshkimmell** [comment]
small screen dark and light bg...
![getting_started_v7](https://cloud.githubusercontent.com/assets/8161298/7089676/26546cf4-df63-11e4-9167-6d058666d480.jpg)
![getting_started_v8](https://cloud.githubusercontent.com/assets/8161298/7089677/265b0550-df63-11e4-8074-673dc26e6ff6.jpg)

**Comment by kathrynmcelroy** [comment]
I agree with Britany, I think we can do a hero image for the Intro page, and it's a pattern we might re-use for the UI Patterns base page (which we will need). 

I like the gray a lot better than the black, except it looks like it doesn't work with the small screen bc it's the same color as the navigation..

**Comment by britanyponvelle** [comment]
I would push for the dark grey in the hero image because the light grey doesn't provide enough contrast between that and the side navigation. The dark could work well on mobile and desktop. My thoughts are if we want to make something different, it should be noticeably different (not just a little) so the users don't get confused about where they are.

**Comment by bobbinrobyn** [comment]
:+1: 

I agree with @britanyponvelle. The dark grey feels like more of a distinct first impression, but it's not so much of a one-off that it looks out of place. I would argue that the purpose of this page is mostly about orienting users to what exactly they're looking at, and I think the contrast of the dark grey helps emphasize that point. It's also the same exact color as the header on all the other pages, so that's a good point of consistency.

Also agree with the points about the side nav. It gets really confusing when the hero image has a light grey background.

**Comment by bobbinrobyn** [comment]
I'm a fan of the white type on the dark grey, because the orange type/dark grey fill reminds me so much of Halloween. Yikes. (But maybe that's just me.)

To bring in more orange, I think we could add another heading like we see on all the other pages. Something like this:

"Design Watson Experiences" <-- in white
[insert new heading here] <-- in orange
"IBM Watson is a system of cognitive technology..."

**Comment by kathrynmcelroy** [comment]
Agreed with @bobbinrobyn on the Halloween intro image. Maybe that's why I preferred the lighter gray. 

After reading these comments, I agree with going with the darker gray background with white text. :+1:

**Comment by joshkimmell** [comment]
![getting_started_v9-1](https://cloud.githubusercontent.com/assets/8161298/7094014/92f28b1e-df83-11e4-90ef-2c9627989e07.jpg)
![getting_started_v9-2](https://cloud.githubusercontent.com/assets/8161298/7094013/92f21828-df83-11e4-9197-0f3204f02a6c.jpg)

**Comment by britanyponvelle** [comment]
:+1:

**Comment by joshkimmell** [comment]
@channel: can we get some feedback on this today?

**Comment by britanyponvelle** [comment]
I think the header is looking great! Can we make the space above and below the white text equal?

**Comment by bobbinrobyn** [comment]
@joshkimmell: I think it looks great! But "Engage your users with cognitive experiences." is different colors on desktop and mobile. Are you going with teal or grey?

**Comment by joshkimmell** [comment]
Sorry... we're going grey.

**Comment by kathrynmcelroy** [comment]
I like it overall, but the font weight for "Design Watson Experiences" versus "What is Watson" feels a little unbalanced for hierarchy. Should the former also be an H1 and therefore be bold?

**Comment by joshkimmell** [comment]
@kathrynmcelroy: I see your point and we can discuss, but it's a hero, not a header, and could therefore be excluded from the "type" hierarchy.

**Comment by britanyponvelle** [comment]
I agree that the hero image text feels like it is competing against the title since they are the same size. I think "Design Watson Experiences" should be bigger than the title to create clearer hierarchy there?

**Comment by joshkimmell** [comment]
Yep. I've been playing with that. What do you think?
![getting_started_v10-1](https://cloud.githubusercontent.com/assets/8161298/7098277/286b56a6-dfa4-11e4-8028-7cb016f55ff0.jpg)
![getting_started_v10-2](https://cloud.githubusercontent.com/assets/8161298/7098278/286d0398-dfa4-11e4-9bb5-2445866f8ff7.jpg)

**Comment by britanyponvelle** [comment]
Yes! Looking great.

**Comment by kathrynmcelroy** [comment]
Love it! :+1:

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by britanyponvelle** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
This is duplicated in #144. I think one can be closed, and one should stay open.

**Comment by Snugug** [comment]
I'm going to keep both open, this one tracking content, that one tracking design, as they're two different things that both need updating based on the conversation around #93 today

**Comment by bobbinrobyn** [comment]
What do we think about this content living on the homepage in a blurb about the Design Principles?

"Watson design principles are actionable guidelines that inform the design and development of cognitive software products, in order to provide consistently excellent experiences for users. They are meant to be applied in conjunction with the IBM Design Language best practices and principles. These design principles are explicitly related to Watson, but some principles may not apply to every use case."

**Comment by ryanbrownhill** [comment]
@bobbinrobyn That sounds good to me! :+1:

**Comment by joshkimmell** [comment]
![getting_started_v11-1](https://cloud.githubusercontent.com/assets/8161298/7263469/5b59f490-e847-11e4-8ede-2070c2cbe982.jpg)
![getting_started_v11-2](https://cloud.githubusercontent.com/assets/8161298/7263468/5b564a3e-e847-11e4-9a35-6f25ac2b87d8.jpg)

**Comment by joshkimmell** [comment]
![getting_started_v11-1](https://cloud.githubusercontent.com/assets/8161298/7263500/aaae7da4-e847-11e4-9b18-2302072db109.jpg)

**Comment by joshkimmell** [comment]
This didn't take Robyn's **giant** principle intro paragraph into consideration...

**Comment by bobbinrobyn** [comment]
I worked hard on that giant paragraph... :stuck_out_tongue_closed_eyes:

**Comment by ryanbrownhill** [comment]
I like the highlighted & underlined "Design Guide" - I wonder how obvious this will be if a user is on a different page. 
I like the side content will be nice "action items" for the 404 page.

**Comment by poofichu** [comment]
This is very visually different from the guidelines section sidenav (greybox).  Was that on purpose?  I personally would want a consistent experience throughout the site.

Also, not a fan of the underline under "design library."  I can see what you're trying to do there (active state for a homepage), but I don't think it's needed.

**Comment by britanyponvelle** [comment]
Agreed on the underline of "design  library", It feels disconnected from the other sections since we only do it here. Although, I think the side bar with the links is fine here because it isn't replacing the grey ide nav content (it is duplicating the main nav content) which is why we chose to remove it from this page. @bobbinrobyn can speak more about that decision

**Comment by joshkimmell** [comment]
Yes! The home page is a one-off (has always been). We should have a subnav if and only if there is sub-content. 

Re: the Design Guide underline
It was used instead of a "Home" button in the top nav. It's also a nod to IBM Design Language.

**Comment by britanyponvelle** [comment]
Scratch that-- I understand the reasoning around the underline now. I think this is a better solution that adding a "Home Page" links.

**Comment by poofichu** [comment]
But the IBM Design Language doesn't have an underline on the homepage?  Or a home link?

I don't see it as being a necessary component.  I think it's a common pattern nowadays that clicking on the "logo" will take a user back to the homepage.

**Comment by joshkimmell** [comment]
@poofichu 
you're wrong. I'm right. 
Kidding... I'm open to user testing this.

**Comment by poofichu** [comment]
Yes please!  TEST.  I really think the blue underline is distracting.

**Comment by joshkimmell** [comment]
Okay... we'll test it tomorrow. 
(but you're wrong)
:sheep:

**Comment by poofichu** [comment]
FINE.
(but your face is wrong)

**Comment by joshkimmell** [comment]
![getting_started_v11-3](https://cloud.githubusercontent.com/assets/8161298/7264034/c806d3b0-e84c-11e4-824e-f3b4e6b9b036.jpg)
Watson has wood!

**Comment by Snugug** [comment]
As it's the home page it shouldn't have previous and next buttons. And is Design Guide going to be highlighted like a normal main nav link?

**Comment by joshkimmell** [comment]
I left the buttons in to show the redesign of the buttons. 
I'm sad that you didn't comment on the wood.

**Comment by Snugug** [comment]
Too easy

**Comment by poofichu** [comment]
I see your wood and raise you cats.

![watson-cats](https://cloud.githubusercontent.com/assets/6757613/7265279/f51a65c0-e84b-11e4-8d46-28091f2dc9b6.png)

**Comment by joshkimmell** [comment]
That's the spirit!

**Comment by bobbinrobyn** [comment]
@joshkimmell But ultimately decided it doesn't need to live on the homepage. I'll find a new home for it.

**Comment by poofichu** [comment]
Just tested the "how do you get to the homepage" with Jefferson, Mina, and Elisa.  All of them clicked on the logo immediately.  I think it's safe to say we don't need the underline or a homepage link.

**Comment by britanyponvelle** [comment]
I hope you used the kitty page.

**Comment by britanyponvelle** [comment]
I think that the side bar for the content on the right should be something a little less prominent. The teal is   pretty eye catching, but it's not an important element on the page and it's too similar to `aside`

**Comment by joshkimmell** [comment]
Need to write the final descriptions for the "lil' side blurbs"

**Comment by joshkimmell** [comment]
For the UI Patterns blurb: 
From basic HTML elements to complex cognitive components, the UI Pattern library will show you how to build Watson UIs.

Thoughts?

**Comment by britanyponvelle** [comment]
This sounds great! Should we spell out "Watson user interfaces" ?

**Comment by ryanbrownhill** [comment]
We don't show them how but we provide them the resources to build UI's. Maybe something like this?

"From basic HTML elements to complex cognitive components, the UI Pattern library will give you the resources to build Watson user interfaces."

**Comment by poofichu** [comment]
@channel http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/index.html

Please review!

**Comment by bobbinrobyn** [comment]
@poofichu Is this updated? I think you implemented the right-hand column of little blurbs, but I'm not seeing it.

**Comment by britanyponvelle** [comment]
I think the grey bar is a little heavy on the right side. Can we make it thinner than the teal bar on the left so it's not as prominent? Also, we will have to use the glyph version of the arrow, since it's under 32px x 32px.

**Comment by joshkimmell** [comment]
![getting_started_v12-2](https://cloud.githubusercontent.com/assets/8161298/7378696/f1ea207a-edb4-11e4-9c70-ebdd3ec54b1b.jpg)
Here's the latest...
added rough footer
icons are 32x32

**Comment by ryanbrownhill** [comment]
I think that the footer could be skinnier. I am imagining something more like this:

![screen shot 2015-04-28 at 2 58 54 pm](https://cloud.githubusercontent.com/assets/9538395/7379178/8794627c-edb8-11e4-83a9-f460c4522d66.png)

**Comment by britanyponvelle** [comment]
Yay, footer! What's the reason behind the teal link color for "privacy" and "terms of use", but grey for "Get the Repo on GitHub"?  It seems like they should all be the same color.

**Comment by ryanbrownhill** [comment]
@britanyponvelle can we move the footer conversation to #197 :heart:

**Comment by joshkimmell** [comment]
Ah... @britanyponvelle good question. Well, my answer is quite simple and, dare I say, interesti...

I'm a dumbass.

**Comment by britanyponvelle** [comment]
Agreed with @ryanbrownhill on smaller footer. I think it's tall because of the "drop us a line" button. I don't think the button is necessary here though, perhaps contact info would be enough. Also, we don't use a button anywhere else on the site

**Comment by britanyponvelle** [comment]
ok :)

**Comment by britanyponvelle** [comment]
The hierarchy of the side links seem a little off the me. I don't know if it makes sense to have this content in `figure` sized text. Seeing it in the browser makes me feel like this content is secondary, but it is  this is the call to action for the page.

My proposal is that there is a title, blurb about the section, and then a link to that section. 

Thoughts?

**Comment by poofichu** [comment]
I actually do agree when you put it like that @bponvelle.

Maybe more of a layout like the 404 page, but we could compromise with having the titles linked and with the icons?
http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/404.html

**Comment by Snugug** [comment]
This is the 102 comment on this thread. Seriously though, we get shit done. Go team.

**Comment by joshkimmell** [comment]
@britanyponvelle like this?
![getting_started_v12-4](https://cloud.githubusercontent.com/assets/8161298/7392901/65a37b4c-ee50-11e4-9362-a64847196cb2.jpg)

**Comment by britanyponvelle** [comment]
Which heading tag were you thinking of using for this?

**Comment by britanyponvelle** [comment]
I think the hierarchy is clearer!

**Comment by joshkimmell** [comment]
I'm not sure... That's why I posted it, to get some feedback... I'll get back to you on that.

**Comment by bobbinrobyn** [comment]
@poofichu and @joshkimmell – These are my revisions for the little blurbs. The original "will help you" and "will give you" language seemed a little awkward to me. Also, I took out the aspirational bits like "brand values" and "cognitive components" because they don't exist yet, and we shouldn't claim that we're offering things that we aren't actually offering.

Principles
Watson design principles provide the foundation for designing excellent cognitive experiences for users.

Guidelines
These style, interaction, and branding guides offer detailed recommendations for elements like color, typography, and motion.

UI Patterns
The UI pattern library contains the resources for building Watson user interfaces, including basic HTML elements and more complex components.

**Comment by joshkimmell** [comment]
:+1:

**Comment by poofichu** [comment]
Hey Josh, the problem we're having with the sidebar styling is that it makes that content feels secondary.  Let's see what it looks like with that content moved underneath.

**Comment by poofichu** [comment]
http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/index.html

We went with a 3 box structure.  It mimics the top nav.  Thoughts?

**Comment by bobbinrobyn** [comment]
We discussed this yesterday, but I'm a big fan of this layout!
+ It elevates the hierarchy of the 3 calls to action from the rest of the content
+ It evens out the hierarchy *between* the 3 calls to action
+ It mimics the horizontal layout of the links in the header
+ Footer is well-resolved with the slightly darker shade of gray
+ Maintaining the shorter line length for the main body copy is super important (and well done here)
+ The pop of teal on the buttons helps add some visual interest to the bottom half of the page

**Comment by Snugug** [comment]
I like too. I also feel those buttons are a good place to add some nice animations

**Comment by britanyponvelle** [comment]
I think this is looking great! I have a crazy idea... what if the main content (everything below "Design Watson Experiences" and above the boxes) was aligned to the second column? Right now I feel that the top is really heavy on the left, and it think that could help. It would also mimic the placement of the main content on other pages. Thoughts?

**Comment by poofichu** [comment]
@britanyponvelle more like this:
http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/index.html

**Comment by britanyponvelle** [comment]
Left aligned is better. lol

**Comment by poofichu** [comment]
http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/index.html

3/4 width for that middle section.  @britanyponvelle better?  (fyi, ignore the footer for now)

**Comment by britanyponvelle** [comment]
Hmmm... the white space is more evenly distributed, but the alignment feels arbitrary since it's not anchored to any of the boxes. My vote is to left-align all of the main content. Thank you for humoring me @poofichu :heart:

**Comment by poofichu** [comment]
Okay full width:
http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/index.html

For the record, I like this the best ;)

**Comment by britanyponvelle** [comment]
This is better! Although, I think the measure should be the same length on this page as it is on the others.

**Comment by joshkimmell** [comment]
![image](https://cloud.githubusercontent.com/assets/8161298/7421937/6068a0ae-ef4e-11e4-979f-bd116cb3bab2.png)

@britanyponvelle, @poofichu: thoughts on "visual anchors?"

**Comment by joshkimmell** [comment]
I just felt like there wasn't enough substance (or formatting) in the "cards"

**Comment by britanyponvelle** [comment]
Hmmm in my opinion the bar doesn't add value to the content, so I think the box is fine. It does what it is intended to do,  elevates the hierarchy of the 3 calls to action from the rest of the content

**Comment by britanyponvelle** [comment]
We could add icons next to the three titles perhaps, to make more of a distinction between the three. Thoughts?

**Comment by poofichu** [comment]
I'm actually super duper awesomely fabulously okay with the simplicity.  Any more, and I won't know where to look / what to click.

**Comment by ryanbrownhill** [comment]
Agreed no icons necessary :smile:

**Comment by ryanbrownhill** [comment]
What is the final decision on this? 
My understanding is: "Cards" at bottom with no visual anchors & no icons? Like we have here: http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/index.html

**Comment by joshkimmell** [comment]
Now we're working on the sidebar. There is concern about the full-width content, so @poofichu is playing with moving the sidebar to the side.

**Comment by poofichu** [comment]
Okay, we refactored the content into the paragraph -- made more sense.  @britanyponvelle @bobbinrobyn @ryanbrownhill agreed.

http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/index.html

Made it 75% for the fullest width.

**Comment by Snugug** [comment]
The fact that the body copy isn't the full width of the cards looks very weird to me when it's aligned left. Maybe center aligning that would make it look better? Or maybe shrinking the container of the cards? Either way, the width should go on the wrapper, not the paragraphs, and instead of using a media query to set a solid width, you should use `max-width`, which sets the largest something will grow while allowing it to shrink smaller

I'm also confused by having two titles on this page: `Design Watson Experiences` and `What is Watson?`. What is Watson should probably not be an `H1`, it should probably be an `H2`.

**Comment by poofichu** [comment]
@britanyponvelle and I are going to take this around to get design feedback from people.  We'll see what we come up with.

**Comment by joshkimmell** [comment]
@snugug: I agree with the H2.

**Comment by joshkimmell** [comment]
![getting_started_v14-1](https://cloud.githubusercontent.com/assets/8161298/7457067/4ecd8fcc-f24f-11e4-866a-b141f277f9ab.jpg)
Disregard the footer...

**Comment by joshkimmell** [comment]
![getting_started_v14-2](https://cloud.githubusercontent.com/assets/8161298/7460678/7c68ec0e-f26a-11e4-87d8-b70cc7485f3d.jpg)

**Comment by Snugug** [comment]
I like https://github.com/IBM-Watson/design-library/issues/121#issuecomment-98770623 better

**Comment by kathrynmcelroy** [comment]
For the Guidelines paragraph, can we change the examples to line up with the guides previously mentioned? Recommending changing it to: "elements like color, motion, and wordmark."

**Comment by poofichu** [comment]
http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/index.html

New homepage design added.  Thoughts?

**Comment by joshkimmell** [comment]
- can we please use an svg for the background image? It's pixellated right now.
- the placement of bg image is off on a smaller screen.

**Comment by britanyponvelle** [comment]
Containing the paragraph content to 2 columns improves the legibility and gives it much more breathing room. 

I think we could work the orange into this page a little more by adding it to the logo. It feels pretty teal heavy right now

**Comment by britanyponvelle** [comment]
Great job, Jessica!

**Comment by poofichu** [comment]
@joshkimmell We're going to play with the background image placement when we get away from the prototype.  I'm going to need to really research into SVGs and background image usage.  They don't play well, from what I can remember.

**Comment by poofichu** [comment]
http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/index.html

I needs some :+1: from you peeps!!

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by kathrynmcelroy** [comment]
:+1:

**Comment by britanyponvelle** [comment]
teal avatar then :+1:

**Comment by joshkimmell** [comment]
:+1:

**Comment by joshkimmell** [comment]
@poofichu: http://codepen.io/netsi1964/pen/HGJms

**Comment by poofichu** [comment]
@joshkimmell Noted.  I'll play with it.

**Comment by Snugug** [comment]
We're approaching a month past due for this. How close are we to a PR?

**Comment by poofichu** [comment]
Should @lhuihui or I handle the PR?

**Comment by Snugug** [comment]
Doesn't matter to me.

**Comment by Lhuihui** [comment]
@Snugug @poofichu Suggest we wait until we finish _layout.html to borrow most of the structure and style from other pages.

**Comment by Snugug** [comment]
Once #257 is done that page is done, but you also shouldn't wait until that's in. This isn't going to be a separate template file, it's going to be fed directly in to the main content are of that template. 

Is the proposal that we hold off until the rest of the page styling is done?

**Comment by poofichu** [comment]
I know the homepage is a one off, but is it going to grab the default styling from the rest of the site?  Same with 404?  There's only a few things on here that are custom.

**Comment by Snugug** [comment]
@poofichu Yah, they should all grab default styling from the site.

**Comment by poofichu** [comment]
Word.  We'll wait till we can get the default styling done today and then move on to this.

**Comment by britanyponvelle** [comment]
:+1:

**Comment by Snugug** [comment]
Resolved by #301
