### ISSUE TITLE
Determine color system

### ISSUE THREAD

**Issue by britanyponvelle** [IBM-Watson/design-library#122]
Use feedback that Robyn is doing in #94 to determine the Watson Color System

**Comment by bobbinrobyn** [comment]
This is done! We can close it.   
https://github.com/IBM-Watson/design-library/wiki/Color-Guidelines  
http://pages.design.ibm.com/rlhammon/watson-color-palettes/master/palette_final.html

**Comment by Snugug** [comment]
All looks great!

If the content in the Wiki is the final content for the site, we need to get a PR opened to bring it in to the repository. @ryanbrownhill just did similar with #128

**Comment by Snugug** [comment]
Resolved by #133
