### ISSUE TITLE
Content Modeling (cont'd)

### ISSUE THREAD

**Issue by joshkimmell** [IBM-Watson/design-library#124]
Take the spreadsheet previously created and flesh it out.

**Comment by kathrynmcelroy** [comment]
Updated Content Modeling on the wiki based on feedback from Britany, Robyn, and Jessica this morning. https://github.com/IBM-Watson/design-library/wiki/Content-Modeling---in-progress

**Comment by Snugug** [comment]
Reading through this, some of it looks more like a site map than content models. Are you going to spin the content models out of this?

**Comment by kathrynmcelroy** [comment]
@Snugug The Content Model portion is up top. The "principles" is a little site-mapy, but the Guidelines and UI Patterns part are more inline with traditional content models. The bottom section is showing how the Content Model applies to the site map and how the pieces are being used.

What other information do you need for the official "Content Model"? This is at the point that the content-makers understand and know what they're making, but I can further refine it to better inform the folder structure.

**Comment by Snugug** [comment]
I'd like to see the individual models abstracted out of the site-mapie flow and into sections that are easily identified with their attributes and how those attributes get used.

**Comment by kathrynmcelroy** [comment]
What do you mean by "individual models"? How would that differ from the "Guideline" model? I understand that the "Principles" one is different but are the "Guideline" and "UI Pattern" models in pretty good form? I'm currently working on making it more streamlined.

**Comment by Snugug** [comment]
Let's take Guidelines for instance:

I see Guideline General Title, then under that Section title with some pieces and under that sub section title. I'm not entirely sure what to make of that in terms of a content model. Is each section a separate piece of content? Are those attributes of each section, or just content that's to be represented in each section. What about subsections? Are they attributes of sections? Can sections be remixed, or are they just part of the body copy of the guideline? What about unstructured attributes, like tags, etc…? To me, that kind of looks like an outline of a guideline, but not a structured model of a guideline that we can start designing IAs against. I'm looking to see something like the following:

```markdown
# Guideline

This is a description of what a Guideline is and why one would write one.

## Attributes

**Title**
  * Required
  * Number allowed: 1
  * Type: text
**Description**
  * Required
  * Number allowed: 1
  * Type: long text (or, reference to external markdown file)
**Short Description**
  * Required
  * Number allowed: 1
  * Type: short text (or, reference to external markdown file)
**Section**
  * Required
  * Number allowed: Minimum 1
  * Type: Reference to Section content type
--- or ---
**Sections**
  * Required
  * Number allowed: Minimum 1
  * Attributes
     * **Title**
       * Required
       * Number allowed: 1
       * Type: text
     **Description**
       * Required
       * Number allowed: 1
       * Type: long text (or, reference to external markdown file)
     **Short Description**
       * Required
       * Number allowed: 1
       * Type: short text (or, reference to external markdown file)
```

Are sections stand-alone content files that have their own meta data, or are they pieces of the larger guideline that simply link to the meaty parts. What about sub-sections? Imagine you had to describe each content type in such a way that someone could build a database schema to hold them; that's what we need from our content models.

**Comment by kathrynmcelroy** [comment]
@Snugug There are indeed images for each of the Principles' "actionable insights". See the attached image for examples of what @bobbinrobyn is working on for the principle pages

![fullsizerender](https://cloud.githubusercontent.com/assets/5400092/6949655/53046fc2-d87b-11e4-9a29-134ee9d9a7f3.jpg)

**Comment by kathrynmcelroy** [comment]
- What content type is the content on the “Getting Started” page?
- What about the description of the “Design Principles”?

I've created a more thorough modeling of some of the elements. @Snugug do you want me to put that into the wiki or as a comment for you to review first?

**Comment by Snugug** [comment]
In the wiki please

**Comment by kathrynmcelroy** [comment]
@Snugug Those first two questions were also for you when you get a chance

**Comment by Snugug** [comment]
@kathrynmcelroy We may not have a content model for them; they may be a "landing page" content type, or may be something else. Why don't you take a swing at trying to figure it out; if you get stuck LMK

**Comment by kathrynmcelroy** [comment]
Updated the wiki with additional content types in Principles and Guidelines. There are a few questions in there. @Snugug Please review when you have time. Working on landing page next.

**Comment by kathrynmcelroy** [comment]
Updated. @Snugug Please go through and make changes as needed.

**Comment by Snugug** [comment]
```markdown
---
type: guideline
title: Color
resources:
  files:
    - name: IBM Color Palette ASE
      source: /assets/color/ibm-color-palette.ase
  links:
    - name: Color Accessibility Chart
      source: http://foo-bar-baz.com
variables:
  palette-application:
    light:
      title: Light Palette
      image: /images/colors/light-palette.png
      description: 'Blue 60; Secondary: Orange 50'
      caption: 'Consider blah blah blah'
    dark:
      title: Dark Palette
      image: /images/colors/light-palette.png
      description: 'Blue 30; Secondary: Orange 30'
      caption: 'Consider blah blah blah'
  primary-colors:
    instructions: Choose a primary and secondary color
    colors:
      - palette: 'blue'
        number: 60
        personality:
          - Trustworthy
          - Systematic
      - palette: 'orange'
        number: 60
        personality: 
          - Innovation
          - Utility
      - palette: 'teal'
        number: 60
        personality:
          - Awareness
          - Approchability
  accent-colors:
    instructions: Choose a primary and secondary color
    colors:
      - palette: 'blue'
        number: 40
        personality:
          - Trustworthy
          - Systematic
      - palette: 'orange'
        number: 30
        personality: 
          - Innovation
          - Utility
      - palette: 'teal'
        number: 40
        personality:
          - Awareness
          - Approchability
  supporting-greys:
---

Color is a crucial component…

## Colros for Watson

The colors chosen…

{{> primary-color-display primary-colors}}

## Choosing a Color Palette

Choose a primary color…

{{> color-picker primary-colors}}

{{> color-picker accent-colors}}

{{> color-picker supporting-greys}}

## Applying a Color Palette

{{> figure palette-application.light }}

{{> figure palette-application.dark }}
```

**Comment by bobbinrobyn** [comment]
![screen shot 2015-04-13 at 11 56 28 am](https://cloud.githubusercontent.com/assets/9341504/7120660/33e6f5b2-e1d4-11e4-882f-8f6b8ab917a5.png)

---
type: principle
title: Design Principles
variables:
	principle:
		introduce-cognitive:
			title: Introduce Cognitive
			summary: Give first-time users a set of "cognitive training wheels" and continue to provide unobtrusive support as needed.
		inform-interactions:
			title: Inform Interactions
			summary: Reduce the complexity of using Watson by informing the user's interactions as they collaborate with Watson to accomplish desired tasks.
		offer-control:
			title: Offer Control
			summary: Let the user choose more help or less help by offering control when it is wanted. Watson experiences should naturally adapt to amplify the user's abilities and expertise.
	example:
		introduce-one:
			image:
			description: Provide intelligent defaults and positive feedback to reinforce cognitive behaviors and gradually adjust the user’s habits.
			caption:
				1. Based on the input data, this is a graph comparing REVENUE and TIME.
				2. Choose a different variable to plot
		introduce-two:
			image:
			description: Clarify Watson's capabilities with hierarchy, copy, and interactions to help set appropriate user expectations.
			caption:
				1. "Remember that Chef Watson eats data, not real food. Use your own judgment when preparing these dishes."
---

Watson design principles are actionable guidelines that inform the design and development of cognitive software products, in order to provide consistently excellent experiences for users. They are meant to be applied in conjunction with the IBM Design Language best practices and principles. These design principles are explicitly related to Watson, but some principles may not apply to every use case.

{{> SOME-FUNCTION-HERE display principle.introduce-cognitive}}

+ Provide intelligent defaults and positive feedback
+ Clarify Watson's capabilities
+ Educate the user throughout the experience
+ Integrate additional information as a secondary focus

{{> figure example.introduce-one}}
{{> figure example.introduce-two}}

**Comment by bobbinrobyn** [comment]
---
type: principle
title: Design Principles
variables:
	principle:
		introduce-cognitive:
			title: Introduce Cognitive
			summary: Give first-time users a set of "cognitive training wheels" and continue to provide unobtrusive support as needed.
		inform-interactions:
			title: Inform Interactions
			summary: Reduce the complexity of using Watson by informing the user's interactions as they collaborate with Watson to accomplish desired tasks.
		offer-control:
			title: Offer Control
			summary: Let the user choose more help or less help by offering control when it is wanted. Watson experiences should naturally adapt to amplify the user's abilities and expertise.
	example:
		introduce-one:
			image:
			description: Provide intelligent defaults and positive feedback to reinforce cognitive behaviors and gradually adjust the user’s habits.
			caption:
				1. Based on the input data, this is a graph comparing REVENUE and TIME.
				2. Choose a different variable to plot
		introduce-two:
			image:
			description: Clarify Watson's capabilities with hierarchy, copy, and interactions to help set appropriate user expectations.
			caption:
				1. "Remember that Chef Watson eats data, not real food. Use your own judgment when preparing these dishes."
---

Watson design principles are actionable guidelines that inform the design and development of cognitive software products, in order to provide consistently excellent experiences for users. They are meant to be applied in conjunction with the IBM Design Language best practices and principles. These design principles are explicitly related to Watson, but some principles may not apply to every use case.

{{> SOME-FUNCTION-HERE display principle.introduce-cognitive}}

+ Provide intelligent defaults and positive feedback
+ Clarify Watson's capabilities
+ Educate the user throughout the experience
+ Integrate additional information as a secondary focus

{{> figure example.introduce-one}}
{{> figure example.introduce-two}}

**Comment by bobbinrobyn** [comment]
@Snugug: This is my .md file so far for the design principles. How am I doing?

**Comment by bobbinrobyn** [comment]
Also, @Snugug should I be using tabs or spaces?

**Comment by Snugug** [comment]
@bobbinrobyn So for principles, I think what we'd want something more along the lines of:

```yaml
title: Introduce Cognitive
summary: Give first-time users a set of …
suggestions:
  - Provide intelligent defaults and positive feedback
  - Clarify Watson's capabilities
  - Educate the user through the experience
examples:
  - image: path/to/image.png
  - description: Provide intelligent defaults
  - explanation:
    - 'Based on the input data…'
    - 'Choose a different variable to plot
```

This way we can keep a principle's examples connected to it, and keep the suggestions structured as well.

**Comment by Snugug** [comment]
Use tabs for now; we can pair later today for me to get you setup with our standard configuration. You can try it yourself if you'd like: In Sublime Text, open up the Command Palette (`cmd+shift+p`), type `install` and hit enter, type `editorconfig` and hit enter, restart Sublime Text.

**Comment by kathrynmcelroy** [comment]
We need a higher-level Section that will cover the title and description for the "Design Principles" page, similar to the content for each individual "Guideline". This Content Type would also cover the high-level section of "UI Patterns" when we have a description of it before we dive into the sub-sections of Elements, Components, and Layouts.

The model for that high-level section will be the same as the "Guideline", but the "Section" would be optional instead of required. (because its sections are the "Principle"s). @Snugug Should we create that high-level section content type, or should we alter the "Guideline" to be more generic?

**Comment by bobbinrobyn** [comment]
@Snugug: Awesome, thanks for the feedback. What is our convention around using single quotes -anytime there's a string, only if there are special characters, etc.?

**Comment by bobbinrobyn** [comment]
@Snugug: Okay, here's attempt numero dos. Also, as far as I can tell, I already have editorconfig installed. Does that mean I'm good to use tabs?

```markdown
---
type: 
title: Design Principles
---

Watson design principles are actionable guidelines that inform the design and development of cognitive software products, in order to provide consistently excellent experiences for users. They are meant to be applied in conjunction with the IBM Design Language best practices and principles. These design principles are explicitly related to Watson, but some principles may not apply to every use case.

{{> SOME-FUNCTION-HERE display principle.introduce-cognitive}}
{{> SOME-FUNCTION-HERE display principle.inform-interactions}}
{{> SOME-FUNCTION-HERE display principle.offer-control}}
```

```markdown
type: principle
title: Introduce Cognitive
summary: Give first-time users a set of "cognitive training wheels" and continue to provide unobtrusive support as needed.
callout: This relies on the principle of Introducing Cognitive.
recommendations:
	- Provide intelligent defaults and positive feedback
	- Clarify Watson's capabilities
	- Educate the user throughout the experience
	- Integrate additional information as a secondary focus
examples:
	introduce-one:
		- image:
		- description: Provide intelligent defaults and positive feedback to reinforce cognitive behaviors and gradually adjust the user’s habits.
		- explanation:
			- Based on the input data, this is a graph comparing REVENUE and TIME.
			- "Choose a different variable to plot"
	introduce-two:
		- image:
		- description: Clarify Watson's capabilities with hierarchy, copy, and interactions to help set appropriate user expectations.
		- explanation:
			- "Remember that Chef Watson eats data, not real food. Use your own judgment when preparing these dishes."
	introduce-three:
		- image:
		- description: Educate the user throughout the experience without interrupting their workflow.
		- explanation:
			- "You still need to complete an action to see results."
	introduce-four:
		- image:
		- description: Integrate additional explanation into the visual hierarchy as a secondary focus so that it doesn’t get in the way of more experienced users.
		- explanation:
			- "Did you know?..."
```

**Comment by britanyponvelle** [comment]
Here is my attempt at finishing the color guidelines:

```markdown

---
type: guideline
title: Color
resources:
  files:
    - name: IBM Color Palette ASE
      source: /assets/visual/ibm-color-palette.ase
variables:
  palette-application:
    light:
      title: Light Palette
      image: /images/visual/light-palette.svg
      description: 'Primary: Blue 60, Secondary: Orange 50, Accent: Teal 40'
      caption: 'Consider users who are sensitive to brightness and high contrast colors by using a neutral value as a background color instead of pure white.'
    dark:
      title: Dark Palette
      image: /images/visual/dark-palette.svg
      description: 'Primary: Blue 30, Secondary: Orange 30, Accent: Teal 30'
      caption: 'Consider users who are sensitive to brightness and high contrast colors by using a grey value as a background color instead of pure black.'
  primary-colors:
    instructions: Choose a primary and secondary color
    colors:
      - palette: 'Blue'
        number: 60
        personality:
          - Trustworthy
          - Systematic
      - palette: 'Orange'
        number: 50
        personality: 
          - Innovation
          - Utility
      - palette: 'Teal'
        number: 60
        personality:
          - Awareness
          - Approchability
  accent-colors:
    instructions: Choose a primary and secondary color
    colors:
      - palette: 'Blue'
        number: 40
      - palette: 'Orange'
        number: 30
      - palette: 'Teal'
        number: 40
    - palette: 'Yellow'
        number: 30
  supporting-greys:
    instructions: Choose supporting greys and neutrals
    colors:
      - palette: 'Grey'
        number: 90
      - palette: 'Grey'
        number: 80
      - palette: 'Grey'
        number: 60
      - palette: 'Grey'
        number: 50
      - palette: 'Grey'
        number: 10
      - palette: 'Neutral'
        number: 4
      - palette: 'Neutral'
        number: 2
---

Color is a crucial component of our visual vernacular, helping to unify the look and feel of all communications. The [IBM Design Language](http://www.ibm.com/design/language/framework/visual/color.shtml) comprises a wide spectrum of colors; IBM Watson relies on a defined subset of those colors to establish its unique presence while respecting the broader IBM Design guidelines.

## Colors for Watson

The colors chosen for IBM Watson are flexible and distinguish Watson as a brand across all user experiences. The colors chosen for IBM Watson were developed using color psychology to support the Watson [brand attributes](brand-attributes.html), reinforce Watson's personality, and set the tone of each specific product.

{{> primary-color-display primary-colors}}

## Choosing A Color Palette

Choose a primary color, a secondary color, and an accent color. Additional tints and shades of the chosen palette can help to unify the design. These values can add variety to a palette without additional colors. Use the IBM Design Language for a wider variety of colors, values, and neutrals.

{{> color-picker primary-colors}}

{{> color-picker accent-colors}}

{{> color-picker supporting-greys}}

## Applying A Color Palette

Color is a powerful communication tool to determine hierarchy on a page. Use ample white space and neutrals to create balance and to direct users' attention.

{{> figure palette-application.light }}

{{> figure palette-application.dark }}
```

**Comment by Snugug** [comment]
Looking at these content models:

* Example, Aside, Inline Code Snippet, Block Quote, Example, and Color Swatch aren't stand-alone content types. They are reusable types of content, but they don't ever exist on their own. As such, they need to be referenced from some other content type, or we need to differentiate between stand-alone content types and expected content for a display pattern (which is what these things are).
* Color Swatch should be updated based on the conversation we had
* Resources under Guidelines needs to be updated based on above conversation
* Variables (like in `pattern`) need to be added where appropriate (most likely Guidelines and Principles)

@kathrynmcelroy Please, in this thread, distinguish for me what content models can live on their own and which are sub-pieces of content that does live on its own. We can divide up the models from that.

**Comment by britanyponvelle** [comment]
@Snugug when you say "Color Swatch should be updated based on the conversation we had", do you mean update the front matter to this structure?

```yaml
title: Introduce Cognitive
summary: Give first-time users a set of …
suggestions:
  - Provide intelligent defaults and positive feedback
  - Clarify Watson's capabilities
  - Educate the user through the experience
examples:
  - image: path/to/image.png
  - description: Provide intelligent defaults
  - explanation:
    - 'Based on the input data…'
    - 'Choose a different variable to plot
```

**Comment by Snugug** [comment]
@britanyponvelle I'm working on getting finalized content models by EOD today.

**Comment by britanyponvelle** [comment]
```markdown
---
type: guideline
title: Accessibility
---

Watson design principles are actionable guidelines that inform the design and development of cognitive software products, in order to provide consistently excellent experiences for users. They are meant to be applied in conjunction with the IBM Design Language best practices and principles. These design principles are explicitly related to Watson, but some principles may not apply to every use case.

{{> SOME-FUNCTION-HERE display principle.introduce-cognitive}}
{{> SOME-FUNCTION-HERE display principle.inform-interactions}}
{{> SOME-FUNCTION-HERE display principle.offer-control}}
```

```markdown
---
type: principle
title: Introduce Cognitive
summary: Give first-time users a set of "cognitive training wheels" and continue to provide unobtrusive support as needed.
callout: This relies on the principle of Introducing Cognitive.
recommendations:
	- Provide intelligent defaults and positive feedback
	- Clarify Watson's capabilities
	- Educate the user throughout the experience
	- Integrate additional information as a secondary focus
examples:
	introduce-one:
		- image:
		- description: Provide intelligent defaults and positive feedback to reinforce cognitive behaviors and gradually adjust the user’s habits.
		- explanation:
			- Based on the input data, this is a graph comparing REVENUE and TIME.
			- "Choose a different variable to plot"
	introduce-two:
		- image:
		- description: Clarify Watson's capabilities with hierarchy, copy, and interactions to help set appropriate user expectations.
		- explanation:
			- "Remember that Chef Watson eats data, not real food. Use your own judgment when preparing these dishes."
	introduce-three:
		- image:
		- description: Educate the user throughout the experience without interrupting their workflow.
		- explanation:
			- "You still need to complete an action to see results."
	introduce-four:
		- image:
		- description: Integrate additional explanation into the visual hierarchy as a secondary focus so that it doesn’t get in the way of more experienced users.
		- explanation:
			- "Did you know?..."
---
```

**Comment by Snugug** [comment]
Not gonna close this until they're finalized

**Comment by Snugug** [comment]
I've finalized the [content models](https://github.com/IBM-Watson/design-library/wiki/Content-Models), final feedback is requested.

I've divided content models up into two different kinds: primary ones (that stand alone and get rendered directly) and secondary ones (which are structured types of content that can be mixed and matched inside a primary one).

With these new content types, the [Principles](https://github.com/IBM-Watson/design-library/issues/145) page is a Guideline content type with multiple Details sub-content pieces included in the main content area. The home page is (and always was going to be) a one-off page. Patterns are patterns.

Thoughts?

**Comment by bobbinrobyn** [comment]
Thanks for finalizing this and sorting out the callout thing. For the design principles, does this content live in the primary content type? If so, I think we're going to need some more attributes.
![screen shot 2015-04-15 at 10 58 00 am](https://cloud.githubusercontent.com/assets/9341504/7163214/750c2126-e35e-11e4-82d4-0dfe4338d126.png)

**Comment by bobbinrobyn** [comment]
Sorry, I forgot to tag you @Snugug ^^^

**Comment by bobbinrobyn** [comment]
Also @Snugug, does every content type needs to have its own markdown file? For example, each detail will have a separate file?

**Comment by bobbinrobyn** [comment]
Also @Snugug, we need an additional attribute for this type of content: "This relies on the principle of Introducing Cognitive."  It's a optional note that references & links to a design principle and can be displayed with a guideline or pattern.

**Comment by bobbinrobyn** [comment]
This is a wireframe, but it gives you the idea. It's the content in the little box. Maybe it could qualify as an aside?
![screen shot 2015-04-15 at 11 37 56 am](https://cloud.githubusercontent.com/assets/9341504/7164144/02301332-e364-11e4-81c5-181eec25f65b.png)

**Comment by Snugug** [comment]
@bobbinrobyn Each of the sub-content types have their information stored in the `variables` attribute of the primary content type they're part of. A key defining feature of all of the sub-content types is that they are not stand-alone content, so no need for separate markdown files.

**Comment by Snugug** [comment]
@bobbinrobyn For the attribute linking to a principle, can you describe what rules that follows? What does it reference? What's the box with the X? Where does that come from? What's that secondary content in there and where does it come from? How and where does it get displayed?

**Comment by bobbinrobyn** [comment]
@Snugug:
1. In a case where a guideline or pattern is heavily influenced by one of the design principles, we would like to reference the principle and display it near the guideline or pattern.
2. The content is minimal (the wireframe is not up to date). It is a line of text that says: "This relies on the principle of [Introducing Cognitive]" and contains a link to that principle on the Design Principles page.
3. Displaying this piece of content is optional. A designer will manually choose whether or not to display it for a given guideline or principle.

**Comment by Snugug** [comment]
@bobbinrobyn Manually deciding whether to include that optional content or not is a problem if it's being pulled from the principle (because that content isn't structured in a way we can get at it per se), if it's simply free-form content we can do that.

My recommendation is, until we have that in practice, let's not worry about it now.

**Comment by bobbinrobyn** [comment]
Deal.

**Comment by bobbinrobyn** [comment]
```markdown
---
type: guideline
title: Design Principles
variables:
    detail:
        introduce-one:
            - visual display: images/visual/introduce-one.svg
            - description: Provide intelligent defaults and positive feedback to reinforce cognitive behaviors and gradually adjust the user’s habits.
            - callout:
                - graph:
                    - title: Based on the input data, this is a graph comparing REVENUE and TIME.
                    - description: This describes the variables plotted on a graph.
                - copy:
                    - title: "Choose a different variable to plot"
                    - description: This is copy that displays below a graph.
        introduce-two:
            - visual display: images/visual/introduce-two.svg
            - description: Clarify Watson's capabilities with hierarchy, copy, and interactions to help set appropriate user expectations.
            - callout:
                - copy: 
                    - title: "Remember that Chef Watson eats data, not real food. Use your own judgment when preparing these dishes."
                    - description: This is copy that displays below the primary content.
        introduce-three:
            - visual display: images/visual/introduce-three.svg
            - description: Educate the user throughout the experience without interrupting their workflow.
            - callout:
                - empty state:
                    - title: "You still need to complete an action to see results."
                    - description: This is an empty module with copy that explains the user's next action.
        introduce-four:
            - visual display: images/visual/introduce-four.svg
            - description: Integrate additional explanation into the visual hierarchy as a secondary focus so that it doesn’t get in the way of more experienced users.
            - callout:
                - copy:
                    - title: "Did you know?..."
                    - description: This is copy that displays beside the primary content.
        inform-one:
            - visual display: images/visual/inform-one.svg
            - description: Demonstrate Watson’s heavy lifting with visual metaphors and indications of the actions Watson takes.
            - callout:
                - modules:
                    - title: Primary Insights
                    - description: These are modules that display primary insights.
                - copy:
                    - title: "See other hypotheses"
                    - description: This is copy that displays below the primary content.
---

Watson design principles are actionable guidelines that inform the design and development of cognitive software products, in order to provide consistently excellent experiences for users. They are meant to be applied in conjunction with the IBM Design Language best practices and principles. These design principles are explicitly related to Watson, but some principles may not apply to every use case.

#Introduce Cognitive

**Give first-time users a set of "cognitive training wheels" and continue to provide unobtrusive support as needed.**

{{> SOME-FUNCTION-HERE display detail.introduce-one}}
{{> SOME-FUNCTION-HERE display detail.introduce-two}}
{{> SOME-FUNCTION-HERE display detail.introduce-three}}
{{> SOME-FUNCTION-HERE display detail.introduce-four}}

#Inform Interactions

**Reduce the complexity of using Watson by informing the user's interactions as they collaborate with Watson to accomplish desired tasks.**

{{> SOME-FUNCTION-HERE display detail.inform-one}}
{{> SOME-FUNCTION-HERE display detail.inform-two}}
{{> SOME-FUNCTION-HERE display detail.inform-three}}
{{> SOME-FUNCTION-HERE display detail.inform-four}}

**Comment by bobbinrobyn** [comment]
Hey @Snugug, how is this looking? I only put 5 out of the 12 details, to give you an idea of what they would be but so that I didn't have to redo them all if I'm not on the right track.

I'm specifically curious about whether or not I need line 4 ("detail:") and/or if I should have a different naming convention for each of the details.

I'm also curious about the callouts. In gave each callout a name so that in cases where there was more than one callout, we could distinguish between them. Is that necessary?

**Comment by Snugug** [comment]
@bobbinrobyn That all looks good! Here are some suggestions to make it a bit easier to work with:

Instead of dashes, use `camelCase` for spaces. Same goes where you have spaces (like `visual display`)

For a detail, have it arranged like the following:

```javascript
informOne: 
  visualDisplay: images/visual/inform-one.
  description: "Demonstrate Watson’s heavy lifting with visual metaphors and indications of the actions Watson takes."
  callout: 
    - title: "Primary Insights"
      description: "These are modules that display primary insights."
    - title: "See other hypotheses"
      description: "This is copy that displays below the primary content."    
```

**Comment by bobbinrobyn** [comment]
Awesome, thanks @Snugug. Should I use quotation marks around every string? If so, how do I distinguish between quotation marks that I want to _display_ and all the other quotation marks.

**Comment by Snugug** [comment]
Double quotes around all strings. For when you want to display quotes, you should escape them:

```
"Hello \"World\", how are you?"
```

**Comment by bobbinrobyn** [comment]
@Snugug: Thanks. What about strings that won't be visually rendered?

type: guideline
**OR**
type: "guideline"

**Comment by Snugug** [comment]
single words dont need quotes

**Comment by bobbinrobyn** [comment]
So if it looks like this in markdown...:

```markdown
---
"\"Choose a different variable to plot\""
---

...it will look like this on the page?:
"Choose a different variable to plot"

**Comment by Snugug** [comment]
Yes

**Comment by Snugug** [comment]
An [Escape Character](http://en.wikipedia.org/wiki/Escape_character) (in JavaScript and most of the front-end languages, `\`) is a character that says "interpret the next character in a different manner than you normally would". With quotes, because we wrap strings in them, when we escape a quote character (single or double), it says "treat this as a literal character, not as the end of the string". There are some special escape sequences, like `\n` which creates a new line and `\t` which inserts a tab.

**Comment by bobbinrobyn** [comment]
Thanks @Snugug, I'm learning so much today. #camelcase :camel:

Here's a second pass. How am I doing?

```markdown
---
type: guideline
title: "Design Principles"
variables:
    detail:
        introduceOne:
            visualDisplay: images/visual/introduce-one.svg
            description: "Provide intelligent defaults and positive feedback to reinforce cognitive behaviors and gradually adjust the user’s habits."
            callout:
                - title: "Based on the input data, this is a graph comparing REVENUE and TIME."
                  description: "This describes the variables plotted on the graph."
                - title: "\"Choose a different variable to plot\""
                  description: "This is copy that displays below a graph."
        introduceTwo:
            visualDisplay: images/visual/introduce-two.svg
            description: "Clarify Watson's capabilities with hierarchy, copy, and interactions to help set appropriate user expectations."
            callout:
                - title: "\"Remember that Chef Watson eats data, not real food. Use your own judgment when preparing these dishes.\""
                  description: "This is copy that displays below the primary content."
        introduceThree:
            visualDisplay: images/visual/introduce-three.svg
            description: "Educate the user throughout the experience without interrupting their workflow."
            callout:
                - title: "\"You still need to complete an action to see results.\""
                  description: "This is an empty module with copy that explains the user's next action."
        introduceFour:
            visualDisplay: images/visual/introduce-four.svg
            description: "Integrate additional explanation into the visual hierarchy as a secondary focus so that it doesn’t get in the way of more experienced users."
            callout:
                - title: "\"Did you know?...\""
                  description: "This is copy that displays beside the primary content."
        informOne:
            visualDisplay: images/visual/inform-one.svg
            description: "Demonstrate Watson’s heavy lifting with visual metaphors and indications of the actions Watson takes."
            callout:
                - title: "Primary Insights"
                  description: These are modules that display primary insights.
                - title: "\"See other hypotheses\""
                  description: "This is copy that displays below the primary content."
---

Watson design principles are actionable guidelines that inform the design and development of cognitive software products, in order to provide consistently excellent experiences for users. They are meant to be applied in conjunction with the IBM Design Language best practices and principles. These design principles are explicitly related to Watson, but some principles may not apply to every use case.

#Introduce Cognitive

**Give first-time users a set of "cognitive training wheels" and continue to provide unobtrusive support as needed.**

{{> SOME-FUNCTION-HERE display detail.introduceOne}}
{{> SOME-FUNCTION-HERE display detail.introduceTwo}}
{{> SOME-FUNCTION-HERE display detail.introduceThree}}
{{> SOME-FUNCTION-HERE display detail.introduceFour}}

#Inform Interactions

**Reduce the complexity of using Watson by informing the user's interactions as they collaborate with Watson to accomplish desired tasks.**

{{> SOME-FUNCTION-HERE display detail.informOne}}
{{> SOME-FUNCTION-HERE display detail.informTwo}}
{{> SOME-FUNCTION-HERE display detail.informThree}}
{{> SOME-FUNCTION-HERE display detail.informFour}}

#Offer Control
```

**Comment by Snugug** [comment]
Perfect!

The one thing I'd recommend is that the headers be H2's (`## Introduce Cognitive`) instead of H1s as they are part of one body of text. We should only have one H1 per page, and that'd be the page's title when it gets displayed.

**Comment by kathrynmcelroy** [comment]
@Snugug Please add content modeling for Documentation so that it can be included in the #93 IA for UI Patterns.

**Comment by Snugug** [comment]
@kathrynmcelroy Documentation is the same as guidelines.

**Comment by britanyponvelle** [comment]
What is the progress report on this?

**Comment by ryanbrownhill** [comment]
I believe UI Patterns need to be included in the content model. 
This could be continued here in UI Patterns AI: #172

**Comment by bobbinrobyn** [comment]
Yep, I think we can close this if it's being covered in #172. I think this falls on you @Snugug.

**Comment by Snugug** [comment]
As [Patterns are included in the Content Modeling](https://github.com/IBM-Watson/design-library/wiki/Content-Models#pattern), I'm going to close this.
