### ISSUE TITLE
Decide direction for Documentation & Guidelines

### ISSUE THREAD

**Issue by ryanbrownhill** [IBM-Watson/design-library#130]
- [x] Define difference between documentation & guidelines
- [x] Define the Content Modeling these different documents
- [x] Define where these live (Repo or Wiki)
- [x] Define how to format these documents (Markdown formatting, etc.)

**Comment by ryanbrownhill** [comment]
Guidelines are the methodologies and best practices we use for a certain subject.
Documentation is the technical side of how to use our components and design library.

Animation is a special case it includes both Guidelines and Documentation on how to create animations (it does not include Technical Documentations on how to implement them - that will be housed elsewhere)

Wiki is where we will work on the content - then we push the final content as a markdown file within the repo Library folder. Once the document is moved to the repo it will be cleared from the Wiki.

As for Content Modeling of the Guidelines pages @kathrynmcelroy is working on that in the [Wiki](https://github.com/IBM-Watson/design-library/wiki/Content-Modeling---in-progress)

As for Content Modeling of the  Documentation @Snugug maybe we could capture that structure in a document somewhere.

**Comment by kathrynmcelroy** [comment]
Initial Content Modeling outline is up in the Wiki: https://github.com/IBM-Watson/design-library/issues/130#issuecomment-85643940

I did not make specifics on length of text, etc., but I'm trying to meet up with Josh somehow go over and add in any additional elements and details that we may need. (and we may not need "short descriptions" for each section/sub-section...) Feedback welcome, and this is still evolving.

**Comment by ryanbrownhill** [comment]
This model looks great! This issue looks good to close. @Snugug - anything else we need to do before closing. Do we need to create a pull request for the content model? If we did would it live in the language folder?

**Comment by kathrynmcelroy** [comment]
Blocked by Content Modeling for documentation.
