### ISSUE TITLE
Choose how to categorize & display elements

### ISSUE THREAD

**Issue by bobbinrobyn** [IBM-Watson/design-library#136]
@Snugug and @kathrynmcelroy are choosing between an alphabetical list or a categorized list of elements

**Comment by Snugug** [comment]
Alphabetical for the time being.

**Comment by kathrynmcelroy** [comment]
We need to determine the future system for search and filter so that we can build the first release in a way that allows gradual updates to reach that system, rather than requiring a complete overhaul. 

- [ ] search and filter planning and design

**Comment by Snugug** [comment]
I talked to two experts in the field yesterday ([Brad Frost](https://twitter.com/brad_frost) and [Jonathan Snook](https://twitter.com/snookca)) about how they organize their style guides/pattern libraries. Brad Frost is the creator of Pattern Lab and [Atomic Design](http://bradfrost.com/blog/post/atomic-web-design/) and is world-renowned  as an expert in style guides and pattern libraries and can probably be pointed to as the person responsible for the prominence of style guides in the field today. Jonathan Snook is the author of SMACSS and pretty much the father of modular CSS thinking on the web.

 I asked them "How do you organize your patterns in your pattern libraries?" Here are their insights:

* Everyone primarily organizes them by high-level groupings roughly equal to our `Base/Components/Layouts`. Brad uses Atomic Design, Jonathan uses a system similar to ours with `Base/Modules/Layouts`.
* Both Brad and Johnathan organize patterns within their high-level groupings manually. Both are roughly based on pattern dependencies. Patterns that are more depended upon (used more) than others are higher up in the list.
*  Johnathan does not provide sub-groupings under the high-level groupings, Brad sometimes does. It depends upon the team.
* Brad ultimately didn't think it mattered if the patterns were arranged alphabetically, manually, or grouped. 
* Both agreed that trying to arrange them into mid-level groups that may span between high-level groupings isn't great (for instance, `forms`, or `text`) They find that people are more interested in global/base stuff first, then individual, more complex patterns.
* Neither of them have a good way to automatically categorize and arrange patterns. They agree it's super hard
* Both thought a UX Flow based approach would be super interesting, but neither had ever seen it before, and both agreed it'd probably be best as a filter option.

One thing we absolutely need to do is _not just interview designers_. Our engineers are going to be the primary consumers of the patterns, so we need to get many more of them involved in our interviews. Designer's advice on this is good, but we need much more research and insight from our engineers.

**Comment by bobbinrobyn** [comment]
I will user test a few different options ASAP (before the end of the week) and report back.

**Comment by britanyponvelle** [comment]
Should the deadline for this be Release Candidate 3?

**Comment by bobbinrobyn** [comment]
I'm picking up on this issue for @kathrynmcelroy, so I want to get caught up with @Snugug. Let's chat tomorrow. Two basic, intuitive sub-groups that I want to recommend are for headers and lists:

**Header** would include: H1, H2, H3, H4, H5, H6
**List** would include: ol, ul

**Comment by Snugug** [comment]
@bobbinrobyn Let's chat today.

**Comment by bobbinrobyn** [comment]
It's been decided... **alphabetical**. No groups (for now).

We can (and should) user test this, but it will be after the initial launch of the website. We should see how developers group patterns, and observe if there is any consistency among developers or if all the groups tend to be idiosyncratic. Other questions to ask include:

What happens if a pattern belongs in multiple groups (e.g. a button belongs to a "Button" group and an "Input" group)? Does the developer want to see it repeated in both groups, or not?

What happens if a pattern belongs in multiple sections (e.g. a button belongs to both "Elements" and "Components")?

**Comment by bobbinrobyn** [comment]
There is an argument to be made for groups like headers, lists, and inputs. But as @Snugug will continue to preach until we have all drunk the Kool-Aid, **there needs to be a rule behind it**. We can't just arbitrarily (or even systematically, but manually) decide that some pages display multiple patterns and some pages display a single pattern. It needs to be systematic *and* automatable.

And just in case you were thinking, "Can't the rule be 'if it has header in the title, display it on the same page'?" let it be known that an H1 is indeed different than an H6. Even though they are both headers and the documentation looks 95% identical.

**Comment by bobbinrobyn** [comment]
I think we're good to close this.
:+1:

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by britanyponvelle** [comment]
:+1:

**Comment by Snugug** [comment]
:+1:
