### ISSUE TITLE
feature/syntax-highlighting

### ISSUE THREAD

**Issue by Snugug** [IBM-Watson/design-library#137]
A component to track our token coloring for [Prism](http://prismjs.com/) for syntax highlighted code blocks.

**Comment by Snugug** [comment]
I also recommend you looking at [Prism's plugins](http://prismjs.com/#plugins) to determine if you'd like to include any of them. For instance, I know you originally had line numbering; if you'd still like to include it, make a point of requiring it. For most code snippets we probably don't need line numbers, but they can be super useful when referencing actual files.

**Comment by britanyponvelle** [comment]
@Snugug will we be referencing actual files often? If not, I think leaving off the numbers is fine since it doesn't add much value to the code snippets. 

Should I add this css file to language>code-snippets?

**Comment by Snugug** [comment]
Agreed.

Actually, what I'd love is for you to make a new component called `syntax-highlighting` that follows the conventions of the other components and issue a PR. Directly contributing! Yay!

I can help you get Prism and all of the stuff needed in.

**Comment by britanyponvelle** [comment]
Cool! Are there instructions listed somewhere that I can follow?

**Comment by britanyponvelle** [comment]
For the "follows the conventions of the other components" part lol

**Comment by Snugug** [comment]
:\ not yet, but they're needed. Those are the contributing guidelines I need to write in #66

**Comment by britanyponvelle** [comment]
Ok! Is it the similar to the "feature" procedure? This one would go in patterns> components?

**Comment by Snugug** [comment]
Basically copy/paste the `radiogroup` component or any of the other patterns in `base` and update the names as needed.

**Comment by britanyponvelle** [comment]
Ok I will give it a shot!

**Comment by Snugug** [comment]
Awesome!

**Comment by ryanbrownhill** [comment]
:+1: via #150

**Comment by britanyponvelle** [comment]
:+1: ^what he said

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by Snugug** [comment]
Will be closed when PR is merged

**Comment by ryanbrownhill** [comment]
resolve by #208
