### ISSUE TITLE
Design for Color Page

### ISSUE THREAD

**Issue by britanyponvelle** [IBM-Watson/design-library#138]
Visual design for Guidelines> Color page.

**Comment by britanyponvelle** [comment]
See additional exploration [here](https://github.com/IBM-Watson/design-library/issues/74).

**Comment by britanyponvelle** [comment]
Browsers wider than 1000px: 

![wdl-color-large](https://cloud.githubusercontent.com/assets/9538528/6923544/0c971622-d798-11e4-8349-90f66e86b37a.png)

Browsers smaller than 1000px: 
![wdl-color-small](https://cloud.githubusercontent.com/assets/9538528/6923563/1e7e0aa8-d798-11e4-8726-a95d1cdce5ec.png)

**Comment by britanyponvelle** [comment]
Updated: 

Updated resources panel:
![wdl-typography-large-v6](https://cloud.githubusercontent.com/assets/9538528/6966873/8e0b847e-d921-11e4-944c-ea704d5b0c5d.png)

![wdl-color-small-v2](https://cloud.githubusercontent.com/assets/9538528/6967031/63c2d464-d922-11e4-8497-13e60f5da728.png)

**Comment by britanyponvelle** [comment]
I've removed the box+ orange line from the "Light and Dark Palette" examples because we are using that styling for block quotes. Also, it makes more sense for this text to be apart of the caption. 

old:
![screen shot 2015-04-03 at 9 37 50 am](https://cloud.githubusercontent.com/assets/9538528/6983607/9594af6c-d9e5-11e4-8541-79b25490e5e2.png)

updated:
![screen shot 2015-04-03 at 9 38 01 am](https://cloud.githubusercontent.com/assets/9538528/6983609/9ad166f0-d9e5-11e4-8525-28e449feb767.png)

**Comment by britanyponvelle** [comment]
Updated swatches in "Choosing A Color Palette":

The four column looked tight visually (especially with the text inside) so I wanted to see what two columns would look like. I favor this version because there is more breathing room around the content and easier to skim. Thoughts on this?

![screen shot 2015-04-06 at 9 59 29 am](https://cloud.githubusercontent.com/assets/9538528/7006337/e7511b80-dc45-11e4-986f-436731c09cf3.png)


Breakpoint at 700px:

![screen shot 2015-04-06 at 10 02 53 am](https://cloud.githubusercontent.com/assets/9538528/7006318/c1afb440-dc45-11e4-956c-48d47002000f.png)

**Comment by bobbinrobyn** [comment]
Wooo, yes! The 4 column swatches were good, but I think this is better.

**Comment by kathrynmcelroy** [comment]
I think this looks great!

**Comment by joshkimmell** [comment]
I like it better. Is anyone thinking about the display of the color values within the box? I think some categorization or hierarchy (maybe animation) could make for a more elegant experience.

**Comment by britanyponvelle** [comment]
@joshkimmell I left the titles as the same size as the values because I didn't think it made sense to put too much emphasis on the name of the color. Right now it is differentiated by the bold text. Do you think there should be more hierarchy between the titles (Choose and Accent color) and the swatch?

**Comment by joshkimmell** [comment]
Not that we should mimic what IBM Design Language is doing, but maybe use their's for inspiration? Let's discuss.

**Comment by kathrynmcelroy** [comment]
@britanyponvelle Updated Color text:
The colors chosen for IBM Watson are flexible and distinguish Watson as a brand across all user experiences. The colors chosen for IBM Watson were developed using color psychology to support the Watson brand attributes, reinforce Watson's personality, and set the tone of each specific product.

Choose a primary color, a secondary color, and an accent color. Additional tints and shades of the chosen palette can help to unify the design. These values can add variety to a palette without additional colors. Use the IBM Design Language for a wider variety of colors, values, and neutrals.

**Comment by britanyponvelle** [comment]
Content updated in the prototype:

http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/color.html

**Comment by britanyponvelle** [comment]
Updated swatch image for wiki:
![screen shot 2015-04-07 at 3 09 30 pm](https://cloud.githubusercontent.com/assets/9538528/7032400/28bb9346-dd38-11e4-9188-a6ec54ee7dd8.png)

**Comment by poofichu** [comment]
Direct links to IBM Design Language!!!
http://www.ibm.com/design/language/framework/visual/color.shtml#contrast

**Comment by britanyponvelle** [comment]
Rewritten content for addressing background colors:

>Choosing A Color Palette
Choose a primary color, a secondary color, and an accent color. Additional tints and shades of the chosen palette can help to unify the design. These values can add variety to a palette without additional colors. Use the IBM Design Language for a wider variety of colors, values, and neutrals. When choosing a background color for light or dark palettes, IBM Watson recommends using Neutral 2 and Grey 90, opposed to pure white and black, as some users are sensitive to brightness and high contrast colors.

We are using Grey 80 as the header on the website because it works better with our accent colors. However, I don't think specifying Grey 80 over Grey 90 in all case makes sense. If the point is to recommend a Grey that is not pure black, the next value is Grey 90. Thoughts?

**Comment by britanyponvelle** [comment]
Same goes for Neutral 2 (I think we should recommend Neutral 1 opposed to pure white). Saying Neutral 2 should be used at all times seems arbitrary to me.

**Comment by joshkimmell** [comment]
@britanyponvelle I can agree with that. 
The last sentence should read "**as** opposed to pure black and white"...

**Comment by britanyponvelle** [comment]
Thanks! I will fix that.

**Comment by Snugug** [comment]
Does that mean we're using pure black and pure white for text?

**Comment by britanyponvelle** [comment]
We are using Grey 90 and pure white for text.

**Comment by britanyponvelle** [comment]
@joshkimmell correct?

**Comment by britanyponvelle** [comment]
Colors have been decided and this page is done :+1:

**Comment by ryanbrownhill** [comment]
:+1: design done

**Comment by bobbinrobyn** [comment]
:+1:
