### ISSUE TITLE
Design for Typography Page

### ISSUE THREAD

**Issue by britanyponvelle** [IBM-Watson/design-library#139]
Visual design for Guidelines> Typography page.

**Comment by britanyponvelle** [comment]
Still working on the visual example for the Typographic Scale section. I've updated the content to this:

"IBM Design Language recommends using modular type scales to create harmonious proportions and structure; IBM Watson uses a subset of those scales. IBM Watson recommends the Major Third ratio for screen sizes under 500px, and establishing breakpoints for higher contrast on larger screens. This ratio is ideal for creating visual hierarchy on small screens without being too jarring."

![wdl-typography-large-05](https://cloud.githubusercontent.com/assets/9538528/6925292/0c899306-d7a4-11e4-930c-f761459bb9c2.png)

**Comment by britanyponvelle** [comment]
I want to do an animation of a browser getting wider for the type scale section to show the increasing type size based on breakpoints. @ryanbrownhill could you help me out with something like this?

![screen shot 2015-03-31 at 3 33 10 pm](https://cloud.githubusercontent.com/assets/9538528/6928673/48b67e86-d7bb-11e4-8d3b-108bacc2fbc3.png)
![screen shot 2015-03-31 at 3 32 57 pm](https://cloud.githubusercontent.com/assets/9538528/6928675/4b8f3f30-d7bb-11e4-902a-6faa2ebb3cdf.png)

**Comment by ryanbrownhill** [comment]
@britanyponvelle - Una has done something similar already - maybe we can reuse some of this code. [Responsive Animation](http://codepen.io/unax3/pen/hslpE)

@Snugug what do you think? Shall we do this is code or do it with a video or gif?

**Comment by britanyponvelle** [comment]
Here is a mockup of what I want to do:
![visual-scale-mockup](https://cloud.githubusercontent.com/assets/9538528/6946315/f98a090e-d864-11e4-83b1-1b9a4c1a2438.gif)

**Comment by britanyponvelle** [comment]
Here is a rendered version of this page:

http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/typography.html

I haven't added the gif because I am not sure how to build this yet. (for now I left a placeholder box). Thoughts?

**Comment by Snugug** [comment]
For the asides we have, like the mention of currently investigating usage rights, we shouldn't have these as `blockquotes`. A blockquote is meant to be ["…section that is quoted from another source."](http://html5doctor.com/element-index/#blockquote). Instead, notes like this should be `aside`s and styled differently.

**Comment by britanyponvelle** [comment]
@ryanbrownhill says he will help me make this visual example today.

@Snugug agreed. I will work on this.

**Comment by ryanbrownhill** [comment]
@una has done something similar on codepen - maybe we can reuse some of this code. [Responsive Animation](http://codepen.io/unax3/pen/hslpE)

@Snugug what do you think? Shall we do this is code or do it with a video or gif?

**Comment by britanyponvelle** [comment]
Updated typography content: http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/typography.html

@ryanbrownhill is working on the animation for the visual example

**Comment by kathrynmcelroy** [comment]
Text edits:
- change effect to affect, and getting rid of 'your' "When presenting large amounts of content, it is important to consider how multiple font downloads can affect the browser’s performance for the user."
- changed a few words for consistency across the sentence: "IBM Watson recommends the Major Third ratio for screen sizes under 500px and the establishment of breakpoints for higher contrast on larger screens. "
- getting rid of 'your' in the caption: "When the browser gets wider than 500px, headings adopt the Golden Ratio type scale to increse legibility for the user at larger screen sizes."

Design Feedback:
- I think the code boxes could use a little more padding
- there's some weird spacing happening on the page above and below headings: smaller above Performance, and waay bigger below Examples. See below:
![screen shot 2015-04-07 at 4 38 48 pm](https://cloud.githubusercontent.com/assets/5400092/7034103/cc3b85f6-dd44-11e4-9123-fbf5f3dc92e2.png)
![screen shot 2015-04-07 at 4 38 59 pm](https://cloud.githubusercontent.com/assets/5400092/7034102/cc3b7106-dd44-11e4-90ab-6d28791f4d69.png)

**Comment by britanyponvelle** [comment]
Thanks for the feedback! I need to adjust the spacing around the font combinations. Something is conflicting here.

**Comment by britanyponvelle** [comment]
http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/typography.html

Ready for review!

**Comment by joshkimmell** [comment]
@britanyponvelle Just viewed this in a small window... The animation isn't responsive.

**Comment by britanyponvelle** [comment]
Thanks for letting me know @joshkimmell ! I need to put it in a flex box.

**Comment by bobbinrobyn** [comment]
Also, the animation is a little pixelated on my screen. Maybe @ryanbrownhill has some advice about striking the optimal balance between performance and good resolution?

**Comment by britanyponvelle** [comment]
We had to compress the video to make the file smaller, which is why it looks that way. @Snugug do you have advice for finding a balance? @ryanbrownhill says if we increase the resolution the file will get much bigger.

**Comment by Snugug** [comment]
@joshkimmell @britanyponvelle You don't even need to do that, just add the following:

```css
video {
  max-width: 100%;
  height: auto;
}
```

As for the video being pixelated, right now it's `147kb` which is really quite large, even in the smaller `.webm` format.  On a Retina screen, it's hard to make video look great without totally blowing up the size. I'd say maybe increase the rendered video resolution to 125% of it's max width and let it scale down, but I wouldn't go much higher for fear of totally blowing up the video size. Ideally for such a simple video this should be smaller, but I wouldn't want the size going above `160kb`. Maybe look into blowing up the resolution and reducing the frame rate too.

**Comment by britanyponvelle** [comment]
Thanks @Snugug ! I added that to my CSS and it seems to be working:
http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/typography.html

I am going to work with @ryanbrownhill to figure out the resolution thing.

**Comment by britanyponvelle** [comment]
@IBM-Watson/design-acceleration This page is updated according to the content model :+1: ?

**Comment by ryanbrownhill** [comment]
:+1: design done

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by Snugug** [comment]
Waiting until there's a response from @britanyponvelle, although you're the owner of that, so I think that falls to you

**Comment by britanyponvelle** [comment]
:+1:
