### ISSUE TITLE
Design for Logo Page

### ISSUE THREAD

**Issue by britanyponvelle** [IBM-Watson/design-library#141]
Visual design for Guidelines> Logo page.

**Comment by britanyponvelle** [comment]
Blocked by #154

**Comment by britanyponvelle** [comment]
I am working on the content for this page in #154. It should be unblocked by OTD.

**Comment by britanyponvelle** [comment]
@IBM-Watson/design-acceleration I am working on updating the SVGs for this page today, but I consider the visual design done. :+1: ? (This content lives on the same page as #142) 
http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/wordmark-logotype.html

**Comment by ryanbrownhill** [comment]
:+1: this is the same as #142

**Comment by bobbinrobyn** [comment]
:+1: Ready to close

**Comment by Snugug** [comment]
Closed in favor of #142
