### ISSUE TITLE
Design for Wordmark Page

### ISSUE THREAD

**Issue by britanyponvelle** [IBM-Watson/design-library#142]
Visual design for Guidelines> Wordmark page.

- [x] Update colors for logo and wordmark

Tied to #141

**Comment by britanyponvelle** [comment]
@kathrynmcelroy @bobbinrobyn What was the reason for breaking up the Wordmark and Logo into two pages? Right now we have this content for the pages: 
![screen shot 2015-03-31 at 3 39 50 pm](https://cloud.githubusercontent.com/assets/9538528/6928941/fe95d94e-d7bc-11e4-9283-89b149f12671.png)

I don't think there is enough to break them into two seperate pages. Thoughts?

**Comment by joshkimmell** [comment]
I think for this, we need to involve Marketing, as well, but I'm not sure it should be separated. Logo do's and don'ts are key. Also, defining "logo" vs. "avatar."

**Comment by kathrynmcelroy** [comment]
@britanyponvelle Agreed, we can go back to "Logo and Wordmark" as the page title.

**Comment by britanyponvelle** [comment]
@joshkimmell does marketing have additional material about the do's and don'ts? 
What do you mean by defining "logo" vs. "avatar"?

**Comment by bobbinrobyn** [comment]
@britanyponvelle Josh means that our users tend to substitute the logo (the static graphic) in places where they should be using the avatar (the animated graphic with different states like listening, thinking, etc). So we need to have a big disclaimer about when to use the logo (in places like headers, for instance) and when to use the avatar (in places where a user is interacting with Watson).

**Comment by britanyponvelle** [comment]
ahh I see! Thanks @bobbinrobyn

**Comment by britanyponvelle** [comment]
@joshkimmell what would be the best way to get marketing involved in this? Should I be spearheading this content?

**Comment by joshkimmell** [comment]
I'll reach out to Marketing.

**Comment by britanyponvelle** [comment]
Blocked by #154

**Comment by britanyponvelle** [comment]
I am working on the content for this page in #154. It should be unblocked by OTD.

**Comment by britanyponvelle** [comment]
Ready for review! http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/wordmark-logotype.html

**Comment by britanyponvelle** [comment]
I have exported SVGs of the logotype and wordmark for download in:
- each primary color (Blue 60, Teal 60, and Orange 50) with Grey 90 for use on light backgrounds
- lighter versions (Blue 30, Teal 30, Orange 30) with Neutral 1 for use on dark backgrounds 
- neutral 1 for dark backgrounds
- grey 90 for light backgrounds

@channel did I miss anything?

**Comment by britanyponvelle** [comment]
@IBM-Watson/design-acceleration I am working on updating the SVGs for this page today, but I consider the visual design done. :+1: ?

**Comment by ryanbrownhill** [comment]
:+1: done just needs SVG updating.

**Comment by britanyponvelle** [comment]
Updated SVG in #169 so this can be closed :+1:

**Comment by bobbinrobyn** [comment]
:+1: Yay! Ready to close

**Comment by britanyponvelle** [comment]
:+1: 
forgot to leave mine!

**Comment by britanyponvelle** [comment]
Resolved in #183

**Comment by britanyponvelle** [comment]
:+1:
