### ISSUE TITLE
Define Page Organization

### ISSUE THREAD

**Issue by kathrynmcelroy** [IBM-Watson/design-library#153]
Alphabetical or in a defined order? This affects Style pages and Interaction Pages.

**Comment by kathrynmcelroy** [comment]
For the "Principles" pages, the order will be:
Introduction (includes Values)
Design Principles
Personality (when we add it in the future)

**Comment by kathrynmcelroy** [comment]
@Snugug If we decide to go with an alphabetical organization to start with, how difficult would it be to later change that to be a specific organization based on our user's priorities?

**Comment by Snugug** [comment]
It'd be a bit of a rewrite; I'd need to add in bits that weren't there before, but it's something we could work around.

**Comment by kathrynmcelroy** [comment]
@joshkimmell  Did we decide to go with alphabetical for the page organization? (for Guidelines)

**Comment by joshkimmell** [comment]
let's start with alphabetical

**Comment by kathrynmcelroy** [comment]
For the "Principles" pages, the order will be:
Getting Started
Design Principles
Personality (future)

For Guidelines pages - Specific order for sections, sub-sections are alphabetical:
Style
- Accessibility
- Color
- Iconography
- Grids
- Typography

Interaction
- Animation
- Signature Patterns

Branding
- Wordmark and Logo

**Comment by ryanbrownhill** [comment]
:+1: Alphabetical was decided

**Comment by britanyponvelle** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
Alphabetical for Guidelines & UI Patterns
Numerical order for Principles

:+1: ready to close
