### ISSUE TITLE
Write guidelines for Logo and Wordmark 

### ISSUE THREAD

**Issue by britanyponvelle** [IBM-Watson/design-library#154]
- [x] Explain the difference between the Watson "logo" and the "avatar"
- [x] Do's and Don'ts of logo and wordmark
- [x] SVG files: how to add color (Use color palette)
- [x] Provide assets to download

View the latest draft in the [wiki](https://github.com/IBM-Watson/design-library/wiki/Wordmark-and-Logotype-guidelines)

**Comment by britanyponvelle** [comment]
First draft: (Thoughts @joshkimmell  @poofichu @kathrynmcelroy @bobbinrobyn ?)


## Wordmark and Logotype
The IBM Watson wordmark and logotype serves as our principal visual reference. It is typeset in Helvetica Neue to align with IBM standards. They should be used in all internal and external communications that focus on the IBM Watson brand. 

**Visual Example**  
1. Wordmark preview
2. Logotype preview

### Specifications
**Spacing considerations**
Use only the supplied artwork when using the wordmark or logotype. It is important to include adequate spacing around these elements in order to distinguish 
**Visual Example**
1. Clear space around wordmark and logotype

**Incorrect Use**
As a rule of thumb, never distort or reconfigure the logotype. Never attempt to create the logotype yourself, change the font, or alter the size or proportions.
**Visual Example**
1. Good and bad example of logotype

### Logo vs. Avatar
The logo for IBM Watson serves as the visual representation of the brand; it should be used as a static element as it pertains to products. The [IBM Watson avatar](http://pages.design.ibm.com/rlhammon/watson-color-palettes/master/axure%20wireframes/guidelines.html) is recommended in situations where interaction is needed to enhance user experience.

**Comment by britanyponvelle** [comment]
First draft: 


## Wordmark and Logotype
The IBM Watson wordmark and logotype serves as our principal visual reference. It is typeset in Helvetica Neue to align with IBM standards. They should be used in all internal and external communications that focus on the IBM Watson brand. 

![screen shot 2015-04-03 at 10 56 18 am](https://cloud.githubusercontent.com/assets/9538528/6984592/15f1a9c6-d9f0-11e4-906a-fd6d86c070cb.png)

### Specifications
**Spacing considerations**
Use only the supplied artwork when using the wordmark or logotype. It is important to include adequate spacing around these elements to avoid clutter.

![ibm_watson_workmark_spacing](https://cloud.githubusercontent.com/assets/9538528/6984983/fed618ea-d9f3-11e4-93aa-553d4d48dcd0.png)

**Incorrect Use**
As a rule of thumb, never distort or reconfigure the logotype. Never attempt to create the logotype yourself, change the font, or alter the size or proportions.

![screen shot 2015-04-03 at 10 55 38 am](https://cloud.githubusercontent.com/assets/9538528/6984599/2a95696c-d9f0-11e4-9e04-cfeb170ce3f7.png)

### Logo versus Avatar
The logo for IBM Watson serves as the visual representation of the brand; it should be used as a static element as it pertains to products. The [IBM Watson avatar](http://pages.design.ibm.com/rlhammon/watson-color-palettes/master/axure%20wireframes/guidelines.html) is recommended in situations where interaction is needed to enhance user experience.

**Comment by britanyponvelle** [comment]
**Color**
The wordmark and logotype for IBM Watson should only appear in the approved color combinations. Any one of the three primary colors for IBM Watson maybe be used in combination with Grey 100 or Neutral 1 for light or dark backgrounds, respectively.

**Comment by ryanbrownhill** [comment]
@britanyponvelle I would get rid of "as a rule of thumb" in the **Incorrect usage*** section. Seems to relaxed like your giving permission to use it incorrectly. I would also do a side by side visual of the logo vs. avatar.

**Comment by britanyponvelle** [comment]
Thanks, Ryan! Definitely don't want it to sound that way. 


## Wordmark and Logotype
The IBM Watson wordmark and logotype serves as our principal visual reference. It is typeset in Helvetica Neue to align with IBM standards. They should be used in all internal and external communications that focus on the IBM Watson brand.

![screen shot 2015-04-03 at 10 56 18 am](https://cloud.githubusercontent.com/assets/9538528/6984592/15f1a9c6-d9f0-11e4-906a-fd6d86c070cb.png)

**Resource**
Wordmark and logotype SVG

### Specifications
**Spacing considerations**
Use only the supplied artwork when using the wordmark or logotype. It is important to include adequate spacing around these elements to avoid clutter.

![ibm_watson_workmark_spacing](https://cloud.githubusercontent.com/assets/9538528/6984983/fed618ea-d9f3-11e4-93aa-553d4d48dcd0.png)

**Incorrect Usage**
Never distort or reconfigure the logotype. Do not attempt to create the logotype yourself, change the font, or alter the size or proportions.

![screen shot 2015-04-03 at 10 55 38 am](https://cloud.githubusercontent.com/assets/9538528/6984599/2a95696c-d9f0-11e4-9e04-cfeb170ce3f7.png)

**Color**
The wordmark and logotype for IBM Watson should only appear in the approved color combinations. Any one of the [three primary colors](http://pages.design.ibm.com/rlhammon/watson-color-palettes/master/axure%20wireframes/guidelines.html) for IBM Watson maybe be used in combination with Grey 100 or Neutral 1 for light or dark backgrounds, respectively.

### Logo versus Avatar
The logo for IBM Watson serves as the visual representation of the brand; it should be used as a static element as it pertains to products. The [IBM Watson avatar](http://pages.design.ibm.com/rlhammon/watson-color-palettes/master/axure%20wireframes/guidelines.html) is recommended in situations where interaction is needed to enhance a user's experience.

**Visual example**
Avatar SVG and rendered animated avatar

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
@britanyponvelle In "Spacing Considerations" I would add the word _visual_ to help make the point more obvious: i.e. "elements to avoid _visual_ clutter"

Isn't Grey 100 the same as black? Or is there a slight difference?

And possibly we could be a tiny bit more explicit about the avatar usage: e.g. "The IBM Watson avatar is recommended to be used to communicate Watson's actions in instances when Watson interacts, aids, and responds to a user."

**Comment by bobbinrobyn** [comment]
I'm not super happy with that last sentence, but do you see what I mean? Maybe this is better: "The IBM Watson avatar is recommended in situations when Watson is interacting with, aiding, or responding to a user."

**Comment by britanyponvelle** [comment]
@bobbinrobyn you are right! I meant to type Grey 90 (since we are not recommending pure black in the "Color" section). 

>"The IBM Watson avatar is recommended in situations when Watson is interacting with, aiding, or responding to a user."

Agreed! I was struggling with that section. This is a great addition!

**Comment by bobbinrobyn** [comment]
@britanyponvelle Okay, awesome! The rest of this looks great. You did an excellent job with the "Do not" examples. I think @joshkimmell will especially appreciate no more cropped Watson logos...

**Comment by britanyponvelle** [comment]
Ha, thanks! 

**A question for all:** For the downloadable assets, should we provide:
1. only  positive (Grey 90) and negative (Neutral 1) versions
or 
2. Grey 90, Neutral 1, and combinations with each primary color (Blue 60, Orange 50, and Teal 60)

**Comment by bobbinrobyn** [comment]
I would provide them all... #peoplearelazy

But we also work with a talented crew of designers who are capable of adding colors themselves. Haha, so I could go either way.

**Comment by poofichu** [comment]
@britanyponvelle Yeah, the color part confused me a bit.  I would say for old, #fridaybraindead people like me include as many downloadable examples as possible

**Comment by britanyponvelle** [comment]
Word. I was getting confused typing it. I will export all of the things!

**Comment by kathrynmcelroy** [comment]
Visual examples of the acceptable color combinations would be helpful.

In the spacing section, is "x" the "x-height" of the wordmark/logotype? If so, we should show (with lines extended further into the wordmark space) that that's what "x" means. (we need to not assume that everyone immediately knows what an "x-height" means)

**Comment by kathrynmcelroy** [comment]
+1 to Robyn's suggestion for further avatar distinction

**Comment by britanyponvelle** [comment]
@kathrynmcelroy X represents the height of the wordmark, not the x-height of the typeface. I will play around with it to try to make that more clear

**Comment by kathrynmcelroy** [comment]
Gotcha! Thanks for the clarification.

**Comment by britanyponvelle** [comment]
Updated spacing example and avatar distinction:
@channel thoughts?

---

## Wordmark and Logotype
The IBM Watson wordmark and logotype serves as our principal visual reference. It is typeset in Helvetica Neue to align with IBM standards. They should be used in all internal and external communications that focus on the IBM Watson brand.

![screen shot 2015-04-03 at 10 56 18 am](https://cloud.githubusercontent.com/assets/9538528/6984592/15f1a9c6-d9f0-11e4-906a-fd6d86c070cb.png)

**Resource**
Wordmark and logotype SVG

### Specifications
**Spacing considerations**
Use only the supplied artwork when using the wordmark or logotype. It is important to include adequate spacing around these elements to avoid visual clutter.

![ibm_watson_workmark-test-05](https://cloud.githubusercontent.com/assets/9538528/7007021/8de3ddca-dc4b-11e4-9271-5c9a252d890a.png)

**Incorrect Usage**
Never distort or reconfigure the logotype. Do not attempt to create the logotype yourself, change the font, or alter the size or proportions.

![screen shot 2015-04-03 at 10 55 38 am](https://cloud.githubusercontent.com/assets/9538528/6984599/2a95696c-d9f0-11e4-9e04-cfeb170ce3f7.png)

**Color**
The wordmark and logotype for IBM Watson should only appear in the approved color combinations. Any one of the [three primary colors](http://pages.design.ibm.com/rlhammon/watson-color-palettes/master/axure%20wireframes/guidelines.html) for IBM Watson maybe be used in combination with Grey 90 or Neutral 1 for use on light or dark backgrounds, respectively.

### Logo versus Avatar
The logo for IBM Watson serves as the visual representation of the brand; it should be used as a static element as it pertains to products.
The [IBM Watson avatar](http://pages.design.ibm.com/rlhammon/watson-color-palettes/master/axure%20wireframes/guidelines.html) is recommended in situations when Watson is interacting with, aiding, or responding to a user.

**Visual example**
Avatar SVG and rendered animated avatar

**Comment by britanyponvelle** [comment]
Here is an alternate version of  the spacing example: 
![ibm_watson_workmark-test-06](https://cloud.githubusercontent.com/assets/9538528/7007069/ebc4cdf0-dc4b-11e4-8987-02cb5889faa3.png)

**Comment by britanyponvelle** [comment]
Alternative to spacing example:

![ibm_watson_workmark-test-blocks-06](https://cloud.githubusercontent.com/assets/9538528/7007138/893c1e44-dc4c-11e4-847f-4d74182d54c0.png)

**Comment by kathrynmcelroy** [comment]
I like the gray because it visually indicates the spacing without needing a key!

**Comment by britanyponvelle** [comment]
thanks @kathrynmcelroy !

**Comment by poofichu** [comment]
@kathrynmcelroy +1 to the grey!

**Comment by britanyponvelle** [comment]
@joshkimmell thoughts on the guidelines?

**Comment by joshkimmell** [comment]
Yep. I like the grey.

**Comment by britanyponvelle** [comment]
@joshkimmell @kathrynmcelroy @poofichu what do you think about this for distinction between the logo and avatar? The goal is to make it clear that the logo maybe be used alone, but not for reconfiguring the logotype.

---

### Logo versus Avatar
The logo for IBM Watson serves as the visual representation of the brand. The logo may be used outside of the logotype configuration as a static element as it pertains to products. The [IBM Watson avatar](http://pages.design.ibm.com/rlhammon/watson-color-palettes/master/axure%20wireframes/guidelines.html) is recommended in situations when Watson is interacting with, aiding, or responding to a user.

**Visual example**
Avatar SVG and rendered animated avatar

**Comment by britanyponvelle** [comment]
Here is the update in browser:

http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/wordmark-logotype.html

Question: for the "Logo versus Avatar" section, will we have the avatar to show as a visual example? for now I am leaving this blank.

**Comment by joshkimmell** [comment]
- Move color usage above incorrect usage and add examples of incorrect color usage to the later. 
- Not enough difference in color between H2, H3 and H5. Different treatment of H3, whether color, size or text-decoration would help.
- Eventually, we need to say something about not using the logo as a button to interact with, or *ASK* Watson.

**Comment by britanyponvelle** [comment]
Updated content in "Specifications"

http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/wordmark-logotype.html

**Comment by britanyponvelle** [comment]
Updated content:

---

## Wordmark and Logotype
The IBM Watson wordmark and logotype serves as our principal visual reference. It is typeset in Helvetica Neue to align with IBM standards. It should be used in all internal and external communications that focus on the IBM Watson brand.

**Resource**
Wordmark and logotype SVG

### Specifications
**Spacing considerations**
Use only the supplied artwork when using the wordmark or logotype. It is important to include adequate spacing around these elements to avoid visual clutter.

**Color Usage**
The wordmark and logotype for IBM Watson should only appear in the approved color combinations. Any one of the [three primary colors](http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/color.htmll) for IBM Watson may be used in combination with Grey 90 or Neutral 1 for use on light or dark backgrounds, respectively. For dark color palettes, use lighter values of the IBM Watson primary colors.

**Incorrect Usage**
Never distort or reconfigure the logotype. Do not attempt to create the logotype yourself, change the font, or alter the size or proportions.

### Logo versus Avatar
The logo for IBM Watson serves as the visual representation of the brand. The logo may be used outside of the logotype configuration as a static element as it pertains to products. The IBM Watson avatar is recommended in situations when Watson is interacting with, aiding, or responding to a user.

**Comment by britanyponvelle** [comment]
@kathrynmcelroy: @joshkimmell felt that the first sentence on this page is too vague:

> The IBM Watson wordmark and logotype serves as our principal visual reference.

Could you help me write something more direct?

**Comment by britanyponvelle** [comment]
For the intro paragraph:

The IBM Watson wordmark and logotype represents our brand and should be managed carefully. It is typeset in Helvetica Neue to align with IBM standards. When possible, it should be used in all internal and external communications that focus on the IBM Watson brand.

Thoughts?

**Comment by kathrynmcelroy** [comment]
Looks good! I like the new version better.

**Comment by ryanbrownhill** [comment]
:-1: ready to close via pull request #165

**Comment by britanyponvelle** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
:+1: ready to close
