### ISSUE TITLE
Contrast between black text and accent colors is insufficient on LCD projectors

### ISSUE THREAD

**Issue by pridkett** [IBM-Watson/design-library#155]
I was at a brief presentation of the emerging design library in Littleton last week and one of the things shared was the color guidelines (see: https://github.com/IBM-Watson/design-library/wiki/Color-Guidelines). While the colors render wonderfully on rich displays with good lighting (e.g. MacBook displays, HDTVs in rooms with proper lighting), on poor displays that color contrast is insufficient. In particular, black text on Blue 40 and Teal 40 were extremely difficult to read using a fairly "average" LCD projector with mediocre lighting:

![image](https://cloud.githubusercontent.com/assets/160672/7006574/4cc6c064-dc50-11e4-8219-6507aff3b9e0.png)

This was a comment that was echoed by several other workshop participants who saw the same screen.

**Comment by Snugug** [comment]
Do we want to indicate that these colors are for software and print and not for presentations?

**Comment by pridkett** [comment]
@Snugug software is not always used on a MacBook Pro with a retina display. Although things are getting better even with cheap displays, I tested it on my Acer Chromebook and the contrast, although better than on a projector, was still poor in a fully lit room (no direct lighting incident on the display).

**Comment by Snugug** [comment]
@pridkett While I agree with you, this is something that needs to be taken up with the Design Language team. The text color recommendations are based on the [WCAG 2.0 Color Contrast guidelines](http://www.w3.org/TR/WCAG/#visual-audio-contrast). Pure black text on Blue 40 [passes AA color contrast standards](http://leaverou.github.io/contrast-ratio/#black-on-%235596e6) and pure black text on Teal 40 [passes AAA color contrast standards](http://leaverou.github.io/contrast-ratio/#black-on-%2300b4a0) which is the highest level of accessibility that can be achieved (to put in perspective, the aim is to have all of our work AA accessible at minimum)

**Comment by Snugug** [comment]
(removing milestone as this is a question)

**Comment by pridkett** [comment]
@Snugug sounds good - you guys know more about this than I do. Thanks for the link to the explanation. I'm going to mark this as closed as I've raised the issue and it has been addressed to my satisfaction.
