### ISSUE TITLE
404 Error page

### ISSUE THREAD

**Issue by joshkimmell** [IBM-Watson/design-library#156]

**Comment by kathrynmcelroy** [comment]
For initial release, the main purpose of the 404 page is to redirect the user to one of the three categories. It will be a great place to give just a tiny bit of info about each category to help the user choose where to go next.

Initial designs.
![img_6145](https://cloud.githubusercontent.com/assets/5400092/7125488/d50f6ff6-e1f6-11e4-8573-10c06be4f309.jpg)

Based on our content modeling, and discussing with Robyn and Britany, we decided that an aside would be the most appropriate treatment for this information.

Updated design for coding:
![img_6146](https://cloud.githubusercontent.com/assets/5400092/7125534/4e8578c6-e1f7-11e4-9ee7-4895c558b62f.jpg)

Tagging @poofichu to code this up for the prototype.

**Comment by joshkimmell** [comment]
This looks promising.

**Comment by Snugug** [comment]
What's the status on this?

**Comment by poofichu** [comment]
@snugug Write this in HTML or Markdown file?

Reference:
https://help.github.com/articles/custom-404-pages/

**Comment by Snugug** [comment]
Either or. Make sure it goes in the `language/`

**Comment by poofichu** [comment]
@channel http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/404.html

Ready for review!

**Comment by bobbinrobyn** [comment]
Are those blurbs the same ones that live on the homepage? Because I have some recommendations to make about wording.

And @poofichu, will those titles have the same arrow icon like they do on the homepage? Or no?

**Comment by poofichu** [comment]
@bobbinrobyn I wasn't planning on them having the same icons as the homepage, but we can most definitely do that. 

And yes!!  The content is shared.

**Comment by poofichu** [comment]
Team, we need to decide if this is the way we want to display this content.  We could mimic the same structure we have going for the homepage: issue #121

Thoughts?

**Comment by bobbinrobyn** [comment]
I know the layouts are different, but my thought is that since the content is almost identical, maybe go ahead and include the icons and make it perfectly identical.

Otherwise, it looks great to me! Give it a footer and it will be good to go.

**Comment by britanyponvelle** [comment]
^agreed. I think we should mimic the structure of the home page, since this content is the same

**Comment by poofichu** [comment]
http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/404.html

@bobbinrobyn and I both took a look at this, and we seem to like this the best.  If we're doing the box structure of the homepage, it just didn't seem to fit here.  Keeping it as a list type format was clean and simple.

**Comment by britanyponvelle** [comment]
Makes sense to me! 

:+1:

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by poofichu** [comment]
@joshkimmell @Snugug @ryanbrownhill Can I get a :+1: or some comments up in heeerrree

**Comment by ryanbrownhill** [comment]
Are we going to do the "card" look for the principles, guidelines, ui patterns like we have on the homepage for the 404 page?

http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/index.html

**Comment by poofichu** [comment]
@ryanbrownhill No sir, no cards.  I would have had to play with the background colors of the cards since the homepage is an exception.  I think list view works here.

**Comment by ryanbrownhill** [comment]
:+1: ok just double checking

**Comment by poofichu** [comment]
@Snugug I think we're good to go with this page.  The only thing I can see running into a problem with converting this page to a markdown file is the icons next to the call to action links under each section.  Thoughts? Advice?  Happy comments?

**Comment by Snugug** [comment]
Yeah, that'll be a problem, but you can mix HTML in to your Markdown if you really need to.

**Comment by poofichu** [comment]
Okay, I'll submit the pull request with HTML in there around just the icon part.  Do I need to unicode my < > or anything like that?

**Comment by Snugug** [comment]
Shouldn't need to

**Comment by poofichu** [comment]
@Snugug submit as 404.md in language/ folder?

**Comment by Snugug** [comment]
@poofichu Nope. just `language/404.md`

**Comment by poofichu** [comment]
@Snugug what type is it?  It ain't no guideline.

**Comment by Snugug** [comment]
It's, like the home page, a 1 off

**Comment by poofichu** [comment]
So no type?

**Comment by Snugug** [comment]
nopr

**Comment by bobbinrobyn** [comment]
Ready to close? :+1:

**Comment by ryanbrownhill** [comment]
once it gets merged in

**Comment by britanyponvelle** [comment]
:+1:
