### ISSUE TITLE
Determine and purchase URL

### ISSUE THREAD

**Issue by joshkimmell** [IBM-Watson/design-library#161]
We need a URL for the site.

**Comment by joshkimmell** [comment]
ibmwatsondesign.com, ibmwatson.io, iamwatson.com/guide/

**Comment by bobbinrobyn** [comment]
Rules for naming external URLs on ibm.com – http://w3-03.ibm.com/transform/sas/as-web.nsf/ContentDocsByTitle/External+URL+Naming+Policy

**Comment by joshkimmell** [comment]
ibmwatsondesigngui.de is available

**Comment by Snugug** [comment]
Okay, but fo real real, what's the status on this?

**Comment by bobbinrobyn** [comment]
@joshkimmell I immediately see "gui". Which is funny, because we are helping designers create interfaces. But possibly not what we're going for..."

**Comment by joshkimmell** [comment]
watsondesign.guide
watsondesignguide.com

**Comment by Snugug** [comment]
Purchased. Done.
