### ISSUE TITLE
UI Pattern IA

### ISSUE THREAD

**Issue by Snugug** [IBM-Watson/design-library#172]
IA (source order, structure, etc…) for UI Patterns section.

Spun out of #93

**Comment by bobbinrobyn** [comment]
This is the IA that @kathrynmcelroy and I discussed. Anyone have thoughts?
![img_3080 copy](https://cloud.githubusercontent.com/assets/9341504/7279347/da0c5528-e8e0-11e4-9c7b-75f7a5ea05a8.jpg)

**Comment by Snugug** [comment]
Really not a fan of accordions. All of that content gets loaded initially so it's not saving anyone on perf (or you click on one and need to wait for it to open). It's also not more parse-able than just a list of links to individual pages. I'd recommend that over accordions. Possibly with the short description too.

FWIW, I don't view this as IA, I view this as wireframing. IA for a page should be agnostic of final layout or implementation details and include the attributes that are needed.

**Comment by bobbinrobyn** [comment]
@snugug That's fair, but wireframing often helps to visualize various IA options, in a way that tree diagrams and lists of attributes do not.

The basic IA decision we're making is whether all of the elements (or components, or layouts) should display on a single page or whether each individual element (or component, or layout) should have its own page.

SINGLE PAGE
**Pros**
Less links in the sidebar
There are many different options for navigating through the long-scroll page
**Cons**
Slower initial load time (but barely! – we're not loading any images, it's all just HTML & CSS)
Potentially a long list of links at the top of the page, difficult to scan
A lot to scroll through

MANY PAGES
**Pros**
Faster initial load time
Easier to scan an individual page
**Cons**
So many links in the sidebar (this will not work for mobile)
Having to load a page for every pattern you want to view
No intro page/paragraph to introduce the section (e.g. "Elements")

**Comment by Snugug** [comment]
One more reason I'm not a fan of accordions: they hide all of the content in a non-searchable way, so if someone wants to try and find in page (which I do often, standard `cmd+f`), they can only search pattern names, not inside the descriptions

**Comment by Snugug** [comment]
So it's not loading a lot of images, but it's loading a lot of DOM elements and manipulating them, which is slow for parsing and means lots of things that need to update on resize (on-page perf vs download perf)

**Comment by bobbinrobyn** [comment]
At a high level, this is the new page structure for UI Patterns:

**Documentation**
Getting Started
Settings
Animation
Javascript Standards

**Patterns**
Elements
Components
Layouts

**Comment by bobbinrobyn** [comment]
All right, y'all. After much discussion with @Snugug, we're opting for 1 pattern per page (as opposed to displaying all of the elements on a single page, all of the components on a single page, and all the layouts on a single page). **This may change** after the initial launch, depending on how well it does in user testing. But for now, here are the arguments in favor of this decision:

1.  "Drop-dead easy" URLs
2. Better for the DOM & on-page performance
3. Better for heavy components

**Comment by bobbinrobyn** [comment]
"But what about the crazy long list of pages in the sidebar?" you may ask (like I did). We're going to get around that by displaying the full list of elements on the intro Elements page, the full list of components on the Components page, and the full list of layouts on the Layouts page. The individual pages will *not* display in the sidebar.

**Comment by bobbinrobyn** [comment]
This is the URL structure:
/Home

/Principles --> goes to /Principles/IntroduceCognitive
/Principles/IntroduceCognitive
/Principles/InformInteractions
/Principles/OfferControl

/Guidelines --> goes to /Guidelines/Style/Accessibility

/Guidelines/Style/ --> goes to /Guidelines/Style/Accessibility
/Guidelines/Style/Accessibility
/Guidelines/Style/Color
/Guidelines/Style/Grids
/Guidelines/Style/Typography

/Guidelines/Interaction --> goes to /Guidelines/Interaction/Animation
/Guidelines/Interaction/Animation
/Guidelines/Interaction/SignaturePatterns
/Guidelines/Interaction/SignaturePatterns/Avatar

/Guidelines/Branding --> goes to /Guidelines/Branding/Wordmark
/Guidelines/Branding/Wordmark

/UIPatterns --> Goes to /UIPatterns/Documentation/GettingStarted

/UIPatterns/Documentation --> goes to /UIPatterns/Documentation/GettingStarted
/UIPatterns/Documentation/GettingStarted
/UIPatterns/Documentation/Settings
/UIPatterns/Documentation/Animation
/UIPatterns/Documentation/JavascriptStandards

/UIPatterns/Patterns --> goes to /UIPatterns/Patterns/Elements
/UIPatterns/Patterns/Elements

/UIPatterns/Patterns/Elements/anchorlink
/UIPatterns/Patterns/Elements/blockquote
/UIPatterns/Patterns/Elements/body
/UIPatterns/Patterns/Elements/button
[...]
/UIPatterns/Patterns/Components
/UIPatterns/Patterns/Layouts

**Comment by bobbinrobyn** [comment]
And this is the wireframe for how the information will be laid out on an individual page: http://pages.design.ibm.com/rlhammon/watson-color-palettes/master/axure%20wireframes/#p=components

**Comment by bobbinrobyn** [comment]
So with that, I think we're ready to :+1: and close. Thoughts @IBM-Watson/design-acceleration?

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by britanyponvelle** [comment]
:+1: woo!

**Comment by poofichu** [comment]
:+1: woo! woo!

**Comment by bobbinrobyn** [comment]
@Snugug It's all you – do you think this is ready to close?

**Comment by Snugug** [comment]
I'm not entirely sure I understand the wireframes, but I think we all understand how things are being laid out, so I'm OK with closing this.
