### ISSUE TITLE
Responsive refinement for main nav

### ISSUE THREAD

**Issue by bobbinrobyn** [IBM-Watson/design-library#175]
Determine breakpoint for when the links move to a second line under the logo (it should be < 900 px)

**Comment by Lhuihui** [comment]
Hey, everyone!

I've made another breakpoint at 700px for main nav.

Original:
![screen shot 2015-04-21 at 1 37 12 pm](https://cloud.githubusercontent.com/assets/2365989/7259878/0188a4f4-e82c-11e4-9e6c-aaf6424aa767.png)

Proposed:
![screen shot 2015-04-21 at 3 14 38 pm](https://cloud.githubusercontent.com/assets/2365989/7261745/adae1a54-e839-11e4-8289-8bb5459d64de.png)

**Comment by bobbinrobyn** [comment]
Looks good, Eva!

**Comment by ryanbrownhill** [comment]
Yes better! :+1:

**Comment by britanyponvelle** [comment]
This looks much better! Can we see what the sub nav would look like if the grey box spanned only 50% of the container?
Just as a test to see what that would look like :)

**Comment by Lhuihui** [comment]
Hi, everyone! Britany, Sam and I are exploring ideas about how the header navigation should look like under 300px. Welcome for your feedback

Proposed1:
![screen shot 2015-04-22 at 4 53 06 pm](https://cloud.githubusercontent.com/assets/2365989/7290739/f55a5ff0-e949-11e4-80a1-67e2671e58de.png)
![screen shot 2015-04-22 at 4 53 49 pm](https://cloud.githubusercontent.com/assets/2365989/7290743/fb521718-e949-11e4-9de6-a899b49c7ba0.png)
Concerns: Header nav' presentation of active/hover status is changing when it goes to bigger screen, which might cause confusion. Header nav is sharing the same structure as sub nav. Hierarchy and connection between them might not be clear to user.

Proposed2:
![screen shot 2015-04-22 at 11 34 46 pm](https://cloud.githubusercontent.com/assets/2365989/7290789/b4acc8e8-e94a-11e4-8fd0-99fc255c243d.png)
![screen shot 2015-04-22 at 11 34 57 pm](https://cloud.githubusercontent.com/assets/2365989/7290790/b835b916-e94a-11e4-922e-e4d9528e1c88.png)
Concerns: Alignment feels strange

Proposed3:
![screen shot 2015-04-22 at 11 40 55 pm](https://cloud.githubusercontent.com/assets/2365989/7290799/d49c2630-e94a-11e4-8e65-f79843be8464.png)
![screen shot 2015-04-22 at 11 41 05 pm](https://cloud.githubusercontent.com/assets/2365989/7290802/d7a04b7c-e94a-11e4-82a5-f402d1274fa0.png)
Underline is a little bit thinner and closer to text. Use the indented structure to show some hierarchy.

**Comment by Lhuihui** [comment]
Hi, all! During the discussion between Sam, Britany and I, we came up four breakpoints for header navigation.

Under 300px:
![screen shot 2015-04-23 at 2 08 22 pm](https://cloud.githubusercontent.com/assets/2365989/7305270/40f7af3a-e9c2-11e4-85fe-c4c806022e0b.png)
The underline is thinner and closer to the text. Vertical align. 1em margin-left 

300px - 460px:
![screen shot 2015-04-23 at 2 12 11 pm](https://cloud.githubusercontent.com/assets/2365989/7305355/c5bb5398-e9c2-11e4-9017-978c1596e215.png)
"Principles", "Guidelines" and "UI Patterns" is inline aligned. Each of them has a 6.25em width and header navigation is centered.

460px - 580px:
![screen shot 2015-04-23 at 2 17 04 pm](https://cloud.githubusercontent.com/assets/2365989/7305445/7283cf38-e9c3-11e4-8372-a16c4ba46fc4.png)
Give some space between "Principles", "Guidelines" and "UI Patterns"

580px - 700px:
![screen shot 2015-04-23 at 2 18 22 pm](https://cloud.githubusercontent.com/assets/2365989/7305473/a56e9996-e9c3-11e4-9269-8c303e52d8e3.png)
Give more space between "Principles", "Guidelines" and "UI Patterns"

beyond 700px:
![screen shot 2015-04-23 at 2 19 27 pm](https://cloud.githubusercontent.com/assets/2365989/7305487/c849fa78-e9c3-11e4-89bf-6bd1e862aedc.png)
Header navigation go to the top right corner.

For more detailed information, review code here:
https://git.design.ibm.com/xluo/evaacceleration/blob/master/sass/regions/_heading.scss
https://git.design.ibm.com/xluo/evaacceleration/blob/master/sass/global/_variable.scss
http://pages.design.ibm.com/xluo/evaacceleration/master/

**Comment by britanyponvelle** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by britanyponvelle** [comment]
@joshkimmell @bobbinrobyn @poofichu :+1:  ?

**Comment by joshkimmell** [comment]
Ah... okay. 
:+1:

**Comment by poofichu** [comment]
YES :+1:

**Comment by bobbinrobyn** [comment]
Yes! :+1:

**Comment by bobbinrobyn** [comment]
Ready to close?

**Comment by britanyponvelle** [comment]
yes!
