### ISSUE TITLE
Refine bottom nav

### ISSUE THREAD

**Issue by bobbinrobyn** [IBM-Watson/design-library#176]
- [ ] Align the center point to the main body copy
- [ ] Move the icons to the outside (the <- icon sits far left, the -> icon sits far right)
- [ ] Decrease the height of the buttons?

**Comment by Lhuihui** [comment]
Explored some ideas about this

Original:
![screen shot 2015-04-22 at 11 43 14 am](https://cloud.githubusercontent.com/assets/2365989/7279890/d15c79cc-e8e4-11e4-9cf4-41fbb6949dcc.png)

Proposed 1
![screen shot 2015-04-22 at 11 39 45 am](https://cloud.githubusercontent.com/assets/2365989/7279908/e7979a8c-e8e4-11e4-9a54-8d29cd40a4c6.png)

![screen shot 2015-04-22 at 11 46 01 am](https://cloud.githubusercontent.com/assets/2365989/7279965/3334e30a-e8e5-11e4-84ad-f4d94c59e6ca.png)

Proposed 2:
![screen shot 2015-04-22 at 11 39 45 am](https://cloud.githubusercontent.com/assets/2365989/7279982/5253a64a-e8e5-11e4-87c8-5ad48912f58f.png)

![screen shot 2015-04-22 at 11 33 59 am](https://cloud.githubusercontent.com/assets/2365989/7279987/58fe29e8-e8e5-11e4-8585-56f66d616973.png)

**Comment by britanyponvelle** [comment]
I vote for option 2. It makes more sense to keep the "next button" in-line with the main content, rather than the middle of the screen

**Comment by ryanbrownhill** [comment]
Agreed Option 2 - via @britanyponvelle reasoning

**Comment by Snugug** [comment]
I'm not a big fan of option 2, especially large. For me, It draws too much attention to those buttons and seriously outweighs the previous button and most everything else on the page.

**Comment by Snugug** [comment]
IMO also throws off three balance of the page. Have you tried one that doesn't have a full bleed? Just constrained to the content area at half each?

**Comment by britanyponvelle** [comment]
Do you think the button outweighs everything else on the page because of how wide it is on large screens? I think right now it feels heavier because there isn't  styling within the main content yet. When there is other color on the page (headings, etc.) I don't think it is as prominent. Eva and I will play with this more today though! 

thoughts @IBM-Watson/design-acceleration ?

**Comment by bobbinrobyn** [comment]
I vote for option 2, and I think it's good that it outweighs the previous button. We're likely trying to convince most users to go to the next page, not the previous one. Let's see it with all the main content styled, and then it will be easier to tell if it's too much orange.

**Comment by Snugug** [comment]
On wide screens, it's the amount of color. Even when we get the rest of our content in it, we use color sparingly throughout body copy, so having a giant bar of color is going to stand out no matter what content we have.

**Comment by ryanbrownhill** [comment]
I honestly need to see it with the rest of the styling in order to gage the hierarchy.

**Comment by Lhuihui** [comment]
Here is another option of being constrained to the content area at half each 
![screen shot 2015-04-23 at 4 55 48 pm](https://cloud.githubusercontent.com/assets/2365989/7308415/dd639700-e9d9-11e4-9458-e38868e48799.png)

**Comment by britanyponvelle** [comment]
I think this feels more structured than "Proposed 1" because the buttons are more clearly related to the main content, although I still think "Proposed 2" is the stronger option. In my opinion the wider buttons at the bottom of the page balances out the dark grey header at the top. Another reason is if we do need to add a footer (which @joshkimmell is working on getting content for)  the smaller buttons from the third option would sit kind of awkwardly on top of it.

@IBM-Watson/design-acceleration thoughts?

**Comment by bobbinrobyn** [comment]
My vote is for the long bottom nav that extends across the full width of the page. I don't have much of an opinion on where the break is between the previous and the next buttons.

The third option looks awkward to me. It's hard to tell why they're constrained, and it doesn't relate as well to the header bar.

**Comment by joshkimmell** [comment]
I agree. I'm still convinced that proposed 2 is the way to go. I do like the reduced height.

**Comment by britanyponvelle** [comment]
:+1: 
option 2

**Comment by britanyponvelle** [comment]
We will update the bottom arrow to the glyph version of the arrow, so we can reduce the size under 32 x 32px

![screen shot 2015-04-24 at 3 40 01 pm](https://cloud.githubusercontent.com/assets/9538528/7328278/ced97b08-ea99-11e4-8558-9dc9854c434e.png)


I work with Eva to update this on Monday

**Comment by britanyponvelle** [comment]
Trying out a few more options for this (sans full-width bars)

opt. 1

![screen shot 2015-04-25 at 11 02 20 am](https://cloud.githubusercontent.com/assets/9538528/7333658/1abf8708-eb3d-11e4-9f88-d1c8fc6f4c28.png)

opt. 2

![screen shot 2015-04-25 at 11 05 06 am](https://cloud.githubusercontent.com/assets/9538528/7333659/225c69b8-eb3d-11e4-9bb1-1ddab0d93538.png)

opt. 3

![screen shot 2015-04-25 at 11 17 58 am](https://cloud.githubusercontent.com/assets/9538528/7333660/27ebbf14-eb3d-11e4-92ea-7d9256ff9f65.png)

**Comment by Snugug** [comment]
I personally like Option 1 of these new options the best, followed by 2

**Comment by poofichu** [comment]
I'm with Sam.

On Saturday, April 25, 2015, Sam Richard <notifications@github.com> wrote:

> I personally like Option 1 of these new options the best, followed by 2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IBM-Watson/design-library/issues/176#issuecomment-96233866>
> .
>


-- 
************************************************
Jessica Tremblay
512-585-2715
jessicatremblay.com

**Comment by britanyponvelle** [comment]
I agree, I favor option 1 the most because the arrow with the circle is more touch-friendly. 
Also, in option 1 & 2 we would have to use Orange 60, instead of Orange 50, to be accessible  at 16 px on a Neutral 2 background

**Comment by joshkimmell** [comment]
I'm okay with this as long as we have a footer that serves as a visual anchor. I think that's why I preferred the large buttons. I know I'm on the hook for footer content.

**Comment by poofichu** [comment]
@joshkimmell agreed with the large buttons when there's footer content.  I really liked them :dancer:

**Comment by britanyponvelle** [comment]
Just to clear this up... 
@poofichu you prefer the large buttons when there is footer content or without? 

I understood @joshkimmell's comment as he is okay with not using the large buttons if there footer content.

**Comment by britanyponvelle** [comment]
Please correct me if I am misunderstanding !

**Comment by poofichu** [comment]
@britanyponvelle I haven't seen the buttons paired alongside footer content yet.  I just really really really really loved the large ones.

**Comment by britanyponvelle** [comment]
Actually this could be easier...

:+1: If you agree with this solution (with or without the footer, as we don't have that content yet)

![screen shot 2015-04-25 at 11 02 20 am](https://cloud.githubusercontent.com/assets/9538528/7350605/cbf7a45e-ecc5-11e4-9889-d0541d703d4b.png)

**Comment by ryanbrownhill** [comment]
:+1: love this solution (above) makes the focus on the content and not the buttons.

**Comment by poofichu** [comment]
What are we looking at for smaller screens?

**Comment by britanyponvelle** [comment]
:+1: 

I give this a thumbs up because we use color subtly to indicate action everywhere else on the page, so to me it makes sense to use orange  this way. Although I do like the orange bars, it does compete with other things on the page.

@poofichu it would be right aligned as well, or we can float the to the sides of the browser at certain breakpoints 
![screen shot 2015-04-27 at 10 23 07 am](https://cloud.githubusercontent.com/assets/9538528/7350875/745303c2-ecc7-11e4-9635-fee914c951bb.png)

**Comment by bobbinrobyn** [comment]
That's really nice!

**Comment by Snugug** [comment]
I really dig that.

**Comment by poofichu** [comment]
Cool beans :+1:

**Comment by britanyponvelle** [comment]
I'm not sure if we could incorporate something like this by next week... but I think a small animation like this could make it better!

![sp-arrow](https://cloud.githubusercontent.com/assets/9538528/7356036/541d4b16-eceb-11e4-82ad-fef2ea9ccbb0.gif)

**Comment by poofichu** [comment]
Yes to small animations!!  I feel like there are other places site wide that could benefit from those as well.  Maybe a larger discussion is needed.

**Comment by britanyponvelle** [comment]
@poofichu agreed!

**Comment by joshkimmell** [comment]
Yes! @ryanbrownhill is going to be looking at this site-wide and will, based on his work with IBM Design Language, make some recommendations.

**Comment by poofichu** [comment]
hot :fire: :fire:

**Comment by Lhuihui** [comment]
Everybody, here is our bottom page nav!

![screen shot 2015-04-29 at 3 29 16 pm](https://cloud.githubusercontent.com/assets/2365989/7400739/b903fa3a-ee84-11e4-8a63-6ad0d25eb428.png)

I used the current longest title to decide the breakpoint(475px). It will become one line.
![screen shot 2015-04-29 at 3 28 29 pm](https://cloud.githubusercontent.com/assets/2365989/7400763/d70e6010-ee84-11e4-9e24-b827fd014a62.png)

**Comment by Lhuihui** [comment]
@Snugug Since the position bottom page nav is more tied with main content now, I moved the code inside the main content session instead of footer.

**Comment by bobbinrobyn** [comment]
Looks great, @Lhuihui!

**Comment by ryanbrownhill** [comment]
:+1: @Lhuihui

**Comment by ryanbrownhill** [comment]
Per @britanyponvelle comment above about the hover state I mocked up the animation - (Although we should be using our custom eases for now I just used an ease in)

![codepen-hover-2](https://cloud.githubusercontent.com/assets/9538395/7423396/4b949a32-ef5a-11e4-87d1-330d87530732.gif)

http://codepen.io/ryanbrownhill/pen/Ejjvvd?editors=110

**Comment by Lhuihui** [comment]
@ryanbrownhill Great!

**Comment by britanyponvelle** [comment]
awesome @ryanbrownhill !

:+1:

**Comment by ryanbrownhill** [comment]
@Snugug What is the plan for merging Eva's code?

**Comment by Snugug** [comment]
@ryanbrownhill @Lhuihui The plan is having her issue a pull request and us working through it like all other PRs.

@Lhuihui If you haven't already, please read over [Developing for the Design Library](https://github.com/IBM-Watson/design-library/wiki/Developing-for-the-Design-Library) and make sure your computer is set up and ready to work, as well as the [Contributing Guidelines](https://github.com/IBM-Watson/design-library/blob/develop/CONTRIBUTING.md). You'll be contributing directly to the Design Library, so we're going to ask you to follow those instructions. If you need help, you can partner with anyone in Austin (or me) to help get you set up and ready to go.

**Comment by Lhuihui** [comment]
@Snugug Ryan has helped me to make it running. Thanks @ryanbrownhill .  My question is should I contribute to _layout.html or create new files under subcontent folders(i.e. _headerimg.html)

**Comment by Snugug** [comment]
@Lhuihui This is for refining the bottom nav? If so, it's part of `_layout.html`. The `subcontent` folder is only for templates supporting [secondary content models](https://github.com/IBM-Watson/design-library/wiki/Content-Models#secondary-content-types)

**Comment by Lhuihui** [comment]
@Snugug Based on our latest design, it makes more sense to put bottom nav inside the subcontent now. Header nav, sub nav and footer might be belong to _layout.html   I'm not sure where the header image fits in since it only appears at homepage. Do you think we should have two layout html files for homepage and all other pages?

**Comment by Snugug** [comment]
@Lhuihui Sub nav is not subcontent, it is a form of navigation. The home page is a one-off page that contains its own HTML content, but the layout (header, optional sidebar, optional sub-nav, footer) is the same

**Comment by Lhuihui** [comment]
@Snugug Gotcha :-) So we will have an index.html for homepage, and _layout.html for header, optional sub-nav, and footer. Is it right?

BTW, I was saying bottom nav(as following) which should belong to subcontent. How do you think? :-)
![screen shot 2015-05-04 at 4 33 22 pm](https://cloud.githubusercontent.com/assets/2365989/7462981/5ce94e76-f27b-11e4-8b6c-d796392e094b.png)

**Comment by Snugug** [comment]
Yes. `_layout.html` is the layout of the overall page, the items in `language` are the content are of the layout

**Comment by Snugug** [comment]
I’m writing the code to find the next/previous links for a page. What happens at the edges? From one subsection to another, is the title the title of the page going to or the subsection? What about main sections? Do we next/previous between main sections (get to the end of principles, next is to guidelines?)

My thinking:

* If you're at the beginning or end of a main section, we don't have next/previous to the next/previous main section
* If you're on a sub section, next/previous crosses subsection borders (do we need a way to indicate you're crossing sub-section borders?

**Comment by joshkimmell** [comment]
@snugug: I agree with your thinking.

**Comment by britanyponvelle** [comment]
:+1: 

I don't think indication of crossing sub-section borders is necessary.

**Comment by ryanbrownhill** [comment]
@snugug: I agree with only adding next/previous with just subsections. I am
confused what you mean by indicating boarders of subsections.

On Tuesday, May 5, 2015, Josh Kimmell <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> @snugug <https://github.com/snugug>: I agree with your thinking.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IBM-Watson/design-library/issues/176#issuecomment-99079018>
> .
>


-- 
-Ryan G. Brownhill
ryanbrownhill.com
ryanbrownhill@gmail.com

**Comment by Snugug** [comment]
@ryanbrownhill Moving from *Styling* to *Interaction*, for instance, would be moving across borders of subsections

**Comment by ryanbrownhill** [comment]
Oh Gotcha. I don't think there is a need to indicate between them.

On Tuesday, May 5, 2015, Sam Richard <notifications@github.com> wrote:

> @ryanbrownhill <https://github.com/ryanbrownhill> Moving from *Styling*
> to *Interaction*, for instance, would be moving across borders of
> subsections
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IBM-Watson/design-library/issues/176#issuecomment-99080994>
> .
>


-- 
-Ryan G. Brownhill
ryanbrownhill.com
ryanbrownhill@gmail.com

**Comment by poofichu** [comment]
Getting on the train :train: and agreeing with both @britanyponvelle and @ryanbrownhill

**Comment by kathrynmcelroy** [comment]
Agreed :+1:

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by britanyponvelle** [comment]
@eva for small browsers, can the link the previous page be flush right? In the screen shot you posted it doesn't look like it is anchored to anything.

**Comment by ryanbrownhill** [comment]
Based on the :+1: 's above the decision was to:

- Have next/previous within sub-sections with no indication between sub-sections borders.
- Not have next/previous to navigate between main sections

**Comment by Snugug** [comment]
Launched!
