### ISSUE TITLE
Responsive refinement for header image

### ISSUE THREAD

**Issue by Lhuihui** [IBM-Watson/design-library#177]

**Comment by Lhuihui** [comment]
This is original one:
![screen shot 2015-04-21 at 11 18 07 am](https://cloud.githubusercontent.com/assets/2365989/7257152/1957737a-e819-11e4-8afa-b06be31032ab.png)
 
Issue about this: when browser size becomes too wide, the logo is too separate from the main content of the site.

Proposed one:
![screen shot 2015-04-21 at 11 19 17 am](https://cloud.githubusercontent.com/assets/2365989/7257212/873456e2-e819-11e4-9c8d-5152d6bd88de.png)

The logo background is constrained within the container of the content. So it will move with the content.

**Comment by Lhuihui** [comment]
More screenshots:
original:
![screen shot 2015-04-21 at 11 30 41 am](https://cloud.githubusercontent.com/assets/2365989/7257261/ebe4d95e-e819-11e4-9893-f5054de5faa1.png)

proposed:
![screen shot 2015-04-21 at 11 30 28 am](https://cloud.githubusercontent.com/assets/2365989/7257268/f70c8048-e819-11e4-9123-c6e9294b57f7.png)

**Comment by britanyponvelle** [comment]
I think the placement of the graphic feels more balanced here. Is there a way to avoid the right side of the graphic getting cut off?

**Comment by ryanbrownhill** [comment]
@Lhuihui agreed - if we get rid of the cropping I think it works great!

**Comment by Lhuihui** [comment]
@britanyponvelle @ryanbrownhill  Yep. Here is the non-crop version :-)

![screen shot 2015-04-24 at 10 14 45 am](https://cloud.githubusercontent.com/assets/2365989/7321996/e06ed536-ea6a-11e4-9f36-e6228d262c7b.png)

**Comment by britanyponvelle** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
Need @Lhuihui PR to close this.

**Comment by Lhuihui** [comment]
According to the current homepage design, there is no sub-nav any more. That effect the header img a little bit. Let me change it quickly and do PR.

**Comment by Lhuihui** [comment]
@Snugug Changed the code according to latest design. https://git.design.ibm.com/xluo/evaacceleration/blob/master/sass/regions/_banner.scss
https://git.design.ibm.com/xluo/evaacceleration/blob/master/index.html
http://pages.design.ibm.com/xluo/evaacceleration/master/

Please let me know if you want me to merge the code or you prefer making this more under your control.

**Comment by Snugug** [comment]
@Lhuihui See https://github.com/IBM-Watson/design-library/issues/176#issuecomment-98363919. We're going to have you issue a PR to bring this in, with full code review/testing, etc…

**Comment by Snugug** [comment]
Part of #121

**Comment by Snugug** [comment]
Resolved by #301
