### ISSUE TITLE
Update Animation description in Accessibility Guidelines

### ISSUE THREAD

**Issue by britanyponvelle** [IBM-Watson/design-library#182]
The description for the Animation section in Style> Accessibility is out of date. Update description to "When there is an animation that last longer than 5 seconds, provide the user a way to pause, stop, or hide the animation."

**Comment by britanyponvelle** [comment]
Resolved in #183

**Comment by britanyponvelle** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
:+1:
