### ISSUE TITLE
Content & design for Getting Started page

### ISSUE THREAD

**Issue by bobbinrobyn** [IBM-Watson/design-library#184]
This page lives here: /UIpatterns/documentation/gettingstarted

- [ ] Write content in an easy to understand form (assume *no* prior knowledge)
- [ ] Design page
- [ ] Format for production

**Comment by bobbinrobyn** [comment]
@Snugug Are you going to write this? And/or should we put it on hold and move it to 1.1?

**Comment by Snugug** [comment]
Needs to be available for 1.0

**Comment by poofichu** [comment]
What's the status on this @bobbinrobyn @Snugug ?
