### ISSUE TITLE
Content & design for Settings page

### ISSUE THREAD

**Issue by bobbinrobyn** [IBM-Watson/design-library#185]
This page lives here: /UIpatterns/documentation/settings

 - [ ] Write content (assume baseline knowledge of development)
 - [ ] Design page
 - [ ] Format for production

**Comment by bobbinrobyn** [comment]
@Snugug Are you going to write this? And/or should we put it on hold and move it to 1.1?

**Comment by Snugug** [comment]
This needs to be available for our first release

**Comment by poofichu** [comment]
@bobbinrobyn @Snugug what's the status on this?
