### ISSUE TITLE
Content & design for Elements page

### ISSUE THREAD

**Issue by bobbinrobyn** [IBM-Watson/design-library#188]
This page lives here: /UIpatterns/patterns/elements

- [x] Write intro paragraph
- [x] Design page
- [ ] Format for production

**Comment by bobbinrobyn** [comment]
Intro paragraphs:

**UI Patterns**
This is a collection of customizable, reusable code and documentation that can be used to prototype cognitive applications and build them consistently. It is a starting point of common elements, components, and layouts that can and should be customized; it is not meant to be used as a definitive prescription for how Watson applications are to be built. The UI patterns displayed here adhere to modern web standards and the principles and guidelines in the Watson Design Guide.

**Elements**
An element is the building block of a user interface. Buttons and form elements are examples of individual elements. A combination of elements is used to create larger components and layouts.

**Comment by bobbinrobyn** [comment]
This is a reminder that we need to update the short description for Anchor Link: https://github.com/IBM-Watson/design-library/blob/develop/patterns/base/a/pattern.yml

**Comment by bobbinrobyn** [comment]
Starting to compile all the content here: https://github.com/IBM-Watson/design-library/wiki/Elements

**Comment by bobbinrobyn** [comment]
This is a reminder that we need to update the YAML file for Label: https://github.com/IBM-Watson/design-library/blob/develop/patterns/base/label/pattern.yml

**Comment by bobbinrobyn** [comment]
This is a reminder that we need to find the correct YAML file for Select: https://github.com/IBM-Watson/design-library/blob/develop/patterns/base/select/pattern.yml

**Comment by bobbinrobyn** [comment]
@britanyponvelle All the content for this page has been compiled in the [wiki](https://github.com/IBM-Watson/design-library/wiki/Elements)!

**Comment by britanyponvelle** [comment]
Here are all of the elements listed in a single column:
http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/elements.html

I don't think this is ideal... but I know we can make it better. I am going to play with columns and adding visual breaks/headings between alphabetized content (A, B, C...) to make this easier to skim

**Comment by bobbinrobyn** [comment]
@Snugug New content type: "Forever long list"

**Comment by britanyponvelle** [comment]
Here are a couple of options for "forever long lists"

Option 1:
![list-1](https://cloud.githubusercontent.com/assets/9538528/7308033/79119ad4-e9d6-11e4-9073-3ea0349a3535.jpg)

Visual indicator on the side connecting titles beginning with the same letter
Pros: 
- A common pattern for grouping similar elements without adding a specific title
Cons: 
- Might not be immediately recognizable that the grouping is based on the alphabetical list

Option 2:
![list-2](https://cloud.githubusercontent.com/assets/9538528/7308107/1f3d980e-e9d7-11e4-9f50-adcc83a5e863.jpg)
Pros: Easy to skim long lists and find the letter you are looking for
Cons: We would need a rule for short lists that only have a few items

Thoughts?

**Comment by britanyponvelle** [comment]
A couple of other options:

1. Groups of letters (A-E, F-N, O-Z, etc) at the of top of the page, linking to sub-sections
2. Listing all letters at the top of the page, linking to sub-sections

![img_7206](https://cloud.githubusercontent.com/assets/9538528/7310886/8dec0e94-e9f9-11e4-98bd-7fc24aa58a3c.JPG)

**Comment by bobbinrobyn** [comment]
This is a wireframe for one of the individual element pages: http://pages.design.ibm.com/rlhammon/watson-color-palettes/master/axure%20wireframes/#p=components

Note: it will not have the Elements title or the paragraph at the top. Instead, it will start with the Button title.

**Comment by bobbinrobyn** [comment]
I did a quick round of user testing to see how we should title the various input elements.

OPTION 1
Email Input
Password Input
Search Input
etc

**OPTION 2** <-- winner
Input – Email
Input – Password
Input – Search
etc

I tested with 3 developers, and they all agreed that Option 2 was best. I've updated the titles in the wiki, but the YAML files will need to be updated for each of the inputs, as well.

**Comment by britanyponvelle** [comment]
Here is a mockup of the Elements page! 
http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/elements.html

Thoughts?

**Comment by britanyponvelle** [comment]
I think there is too much space between elements, but this was the best I could do today, lol.

**Comment by britanyponvelle** [comment]
![screen shot 2015-04-24 at 3 18 59 pm](https://cloud.githubusercontent.com/assets/9538528/7327756/5349fcaa-ea95-11e4-8edf-fb4a30c43e5d.png)

![screen shot 2015-04-24 at 3 19 21 pm](https://cloud.githubusercontent.com/assets/9538528/7327758/575d13c2-ea95-11e4-8f3f-c5a234131e1d.png)

**Comment by bobbinrobyn** [comment]
@britanyponvelle Obviously we're all saying this out loud in ATX, but just let the whole interwebs know... you are awesome. And that list is awesome.

**Comment by Snugug** [comment]
https://www.youtube.com/watch?v=QK8mJJJvaes&t=3m14s

**Comment by britanyponvelle** [comment]
Yas :raised_hands:

**Comment by ryanbrownhill** [comment]
:dancer: go @britanyponvelle! I approve :+1:

**Comment by bobbinrobyn** [comment]
Wooo, yay! :+1: 

And hopefully this means that #189 and #190 will go super quick, since they're basically the same page.

**Comment by britanyponvelle** [comment]
@bobbinrobyn yes mam it should! :)

**Comment by britanyponvelle** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1: done

**Comment by poofichu** [comment]
:+1: :yum:

**Comment by ryanbrownhill** [comment]
@Snugug Should this have a Markdown or how should we be going about getting this into production?

**Comment by Snugug** [comment]
Markdown files for the content, in `language`. I haven't figured out how I want to build/render the listing, so don't worry about that yet

**Comment by Snugug** [comment]
What are the rules around dividing up into alphabetical groupings @britanyponvelle?

**Comment by britanyponvelle** [comment]
I grouped them as closely as possible, so A—G (7 letters), H—N (7 letters), O—T (6 letters), U—Z (6 letters)

**Comment by Snugug** [comment]
Cool, just making sure!

**Comment by britanyponvelle** [comment]
:) :+1:

**Comment by ryanbrownhill** [comment]
@Snugug what should the links to the elements be in the markdown?
 
We basically have the markdown done in the wiki but all the links are dummy links. 
https://github.com/IBM-Watson/design-library/wiki/Elements

**Comment by Snugug** [comment]
@ryanbrownhill No links. Just the intro paragraph. I'll take care of rendering the links dymanically
