### ISSUE TITLE
Content & Design for Components page

### ISSUE THREAD

**Issue by bobbinrobyn** [IBM-Watson/design-library#189]
This page lives here: /UIpatterns/patterns/components

- [x] Write intro paragraph
- [x] Design page
- [ ] Format for production

**Comment by bobbinrobyn** [comment]
**Components**
A component is a combination of elements. Navigation and search are examples of components. A combination of elements and components is used to create larger layouts.

**Comment by bobbinrobyn** [comment]
Content for this page is in the [wiki](https://github.com/IBM-Watson/design-library/wiki/Components)

**Comment by bobbinrobyn** [comment]
This is a wireframe for one of the individual component pages: http://pages.design.ibm.com/rlhammon/watson-color-palettes/master/axure%20wireframes/#p=components

Note: it will *not* have the Components title or the paragraph at the top. Instead, it will start with the Radio Group title.

**Comment by britanyponvelle** [comment]
I attempted to mock up the code blocks, but ended up with this beautiful mess:
http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/components.html

![screen shot 2015-04-27 at 11 25 50 am](https://cloud.githubusercontent.com/assets/9538528/7352300/54a5975c-ecd0-11e4-96e8-22bde4fbb2a0.png)

I found some resources saying to use ```<code>  </code>``` and ```<pre> </pre>``` but I'm not having any luck. Does anyone have a resource I could use to fix this?

**Comment by britanyponvelle** [comment]
Woo! I managed to get the code to show in the box, although it is hanging out on the right side now...

![screen shot 2015-04-27 at 1 42 04 pm](https://cloud.githubusercontent.com/assets/9538528/7354805/63c8be86-ece3-11e4-99ef-b487e3a6115f.png)

![screen shot 2015-04-27 at 1 42 27 pm](https://cloud.githubusercontent.com/assets/9538528/7354807/66140f74-ece3-11e4-8528-afd830ec9a09.png)

.../facepalm

**Comment by bobbinrobyn** [comment]
For Designcamp, I made this [little guy](http://orangeteam.stage1.mybluemix.net/robyn/index.html). Maybe you can pick through my source code to see how I did it? Or I can dig through it to try to remember :flushed:

**Comment by britanyponvelle** [comment]
Awesome, thanks @bobbinrobyn ! I will take a look :)

**Comment by britanyponvelle** [comment]
@Snugug look!! GETTING SOMEWHERE.

![screen shot 2015-04-28 at 12 07 20 pm](https://cloud.githubusercontent.com/assets/9538528/7375573/31a154e2-ed9f-11e4-83aa-f747962750f5.png)

**Comment by britanyponvelle** [comment]
Changed to IBM Design colors... this needs work. What do you guys think about the dark box vs a lighter box?

http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/components.html

**Comment by britanyponvelle** [comment]
@IBM-Watson/design-acceleration thoughts on the dark color scheme for code blocks?

![screen shot 2015-04-29 at 9 45 33 am](https://cloud.githubusercontent.com/assets/9538528/7393655/a1971fb0-ee54-11e4-891d-e55d49c67606.png)

We are using prism for syntax highlighting. The background is Grey 70 and the text are hues from the 20 scale

**Comment by britanyponvelle** [comment]
Looking for feedback on color, height of code block, and whether we should include horizontal scrolling

**Comment by ryanbrownhill** [comment]
@britanyponvelle :+1: I like it! 
I wonder if it should be more contrasty?

**Comment by Snugug** [comment]
I'm a big fan of the [Monokai](https://atom.io/themes/monokai) syntax highlighting theme. I wonder if we could come close to emulating that?

I think our best bet, in general, is to try and create a theme that's as close as possible to one people already know.

**Comment by Snugug** [comment]
If you want to install Monokai for Sublime Text to see what it looks like, check this theme out:

https://github.com/jonschlinkert/sublime-monokai-extended

**Comment by britanyponvelle** [comment]
@Snugug I started with the Okaidia theme [(mentioned here)](https://github.com/IBM-Watson/design-library/issues/71) and picked the closest color from the IBM palette. 
Do you think that Monokai theme is more standard?

**Comment by britanyponvelle** [comment]
I made a few adjustments in the earlier version. This is closest I can get to Okaidia:

![screen shot 2015-04-29 at 11 29 16 am](https://cloud.githubusercontent.com/assets/9538528/7395943/2380fdd0-ee63-11e4-884e-e4db4606454f.png)

Thoughts?

**Comment by Snugug** [comment]
Okaidia is a base theme from Prism which is close enough to Monokai that I like to use it as a starting point. I think people will be more familiar with Monokai, but we're customizing.

I also recommend you trying it out with different languages (CSS, Sass, and JavaScript being the big 3 we should try with) so we can see how the colors look with different languages.

**Comment by britanyponvelle** [comment]
That makes sense! I was using the [this code](https://github.com/PrismJS/prism/blob/gh-pages/themes/prism-okaidia.css) as a starting point to play with colors. Is there a page like this I can sue for Monokai?

**Comment by Snugug** [comment]
Sorry, should have been more clear to begin with!

Not quite with the CSS, but there's an XML file you can look at

https://github.com/jonschlinkert/sublime-monokai-extended/blob/master/Monokai%20Extended.tmTheme

**Comment by britanyponvelle** [comment]
Here is an example of html, css, javascript, and Sass code blocks:

![okaidia-html-large](https://cloud.githubusercontent.com/assets/9538528/7398451/b977102a-ee74-11e4-8946-2f08a324b9f6.png)
![okaidia-html-small](https://cloud.githubusercontent.com/assets/9538528/7398453/bb82150e-ee74-11e4-9662-64976464a9be.png)
![screen shot 2015-04-29 at 1 34 44 pm](https://cloud.githubusercontent.com/assets/9538528/7398455/c14273b2-ee74-11e4-8f0a-41a2846b0cc8.png)
![screen shot 2015-04-29 at 12 06 00 pm](https://cloud.githubusercontent.com/assets/9538528/7398456/c2e26592-ee74-11e4-826f-98fcd046ae3f.png)
![screen shot 2015-04-29 at 12 06 15 pm](https://cloud.githubusercontent.com/assets/9538528/7398458/c4b1103a-ee74-11e4-8b42-a6cb0c55dcae.png)

**Comment by britanyponvelle** [comment]
Here is an example of html, css, javascript, and Sass code blocks for Okaidia! I am going to work on a page using Monokai next so we can compare.

![okaidia-html-large](https://cloud.githubusercontent.com/assets/9538528/7398451/b977102a-ee74-11e4-8946-2f08a324b9f6.png)
![okaidia-html-small](https://cloud.githubusercontent.com/assets/9538528/7398453/bb82150e-ee74-11e4-9662-64976464a9be.png)
![screen shot 2015-04-29 at 1 34 44 pm](https://cloud.githubusercontent.com/assets/9538528/7398455/c14273b2-ee74-11e4-8f0a-41a2846b0cc8.png)
![screen shot 2015-04-29 at 12 06 00 pm](https://cloud.githubusercontent.com/assets/9538528/7398456/c2e26592-ee74-11e4-826f-98fcd046ae3f.png)
![screen shot 2015-04-29 at 12 06 15 pm](https://cloud.githubusercontent.com/assets/9538528/7398458/c4b1103a-ee74-11e4-8b42-a6cb0c55dcae.png)

**Comment by britanyponvelle** [comment]
View it live here: http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/components.html

**Comment by britanyponvelle** [comment]
Here I switched yellow 20 to yellow 10:

![screen shot 2015-04-29 at 1 44 28 pm](https://cloud.githubusercontent.com/assets/9538528/7398654/fb11b412-ee75-11e4-86cb-b5f91879a3b5.png)

**Comment by bobbinrobyn** [comment]
Yes! Better! Do y'all agree?

**Comment by ryanbrownhill** [comment]
:+1: yes better! I like the higher contrast.

**Comment by joshkimmell** [comment]
:+1: Looks great!

**Comment by britanyponvelle** [comment]
Doing my best to mimic Monokai, but having some trouble extracting what I need from the XML file (there are many lines) Here is what I have so far...

![screen shot 2015-04-29 at 2 46 34 pm](https://cloud.githubusercontent.com/assets/9538528/7399897/a33e1934-ee7e-11e4-89af-9410a2eb8bc7.png)

**Comment by Snugug** [comment]
Maybe this will help:

https://gist.github.com/asaaki/1007420

It actually looks like Okaidia is much closer to the monokai I’m expecting to see than I thought. I’m being terribly unhelpful, I know, but it’s tag color, for instance, is exactly what I’d expect from monokai

**Comment by britanyponvelle** [comment]
@Snugug does this look closer?

![screen shot 2015-04-29 at 12 06 00 pm](https://cloud.githubusercontent.com/assets/9538528/7401902/4b06d990-ee8d-11e4-8702-97a18c1805e0.png)

**Comment by britanyponvelle** [comment]
@Snugug does this look closer?

![screen shot 2015-04-29 at 4 30 37 pm](https://cloud.githubusercontent.com/assets/9538528/7401916/5c2057a6-ee8d-11e4-8900-575e03996098.png)

**Comment by britanyponvelle** [comment]
http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/components.html

**Comment by Snugug** [comment]
I'm of no help to you today. I appreciate you putting up with me.

Yes, except for the strings; they should be a different color. Your yellow from before was good. It was mostly the pink/blue tags

**Comment by Snugug** [comment]
Please don't hurt me, but https://github.com/IBM-Watson/design-library/issues/189#issuecomment-97535274 is pretty close to what I was expecting. I've just been a crappy contributor today. I'm sorry :\

**Comment by britanyponvelle** [comment]
Haha that is totally fine!! Luckily I have discovered "commenting things out" so switching back is super easy. No hitting necessary :)

**Comment by Snugug** [comment]
Yay!

**Comment by britanyponvelle** [comment]
@Snugug does this look any closer? I updated the strings to yellow, and it seems to be working every where except the Sass example. Prism didn't have a Sass download, so I'm not sure how to implement that. Can I set up some time with you tomorrow?

http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/components.html

![screen shot 2015-04-29 at 5 08 14 pm](https://cloud.githubusercontent.com/assets/9538528/7402525/6c490ed4-ee92-11e4-9b04-aa03af297dc3.png)
![screen shot 2015-04-29 at 5 08 28 pm](https://cloud.githubusercontent.com/assets/9538528/7402527/6c4b1422-ee92-11e4-8373-ca025f64c9fd.png)
![screen shot 2015-04-29 at 5 08 36 pm](https://cloud.githubusercontent.com/assets/9538528/7402526/6c4b22aa-ee92-11e4-8756-ca7a55122c5b.png)

**Comment by britanyponvelle** [comment]
Or, if this looks "right-ish" I can submit a PR and we can get down in the weeds and make changes from there

**Comment by Snugug** [comment]
@britanyponvelle Submit a PR and we can play from there. It looks pretty good.

The component in Prism for Sass is `prism-scss` and the language is `scss`.

**Comment by britanyponvelle** [comment]
Will do! @ryanbrownhill and I are going to tag team PRs today

**Comment by ryanbrownhill** [comment]
This issue will be closed once #208 gets merged
