### ISSUE TITLE
Update patterns template

### ISSUE THREAD

**Issue by bobbinrobyn** [IBM-Watson/design-library#191]
Once we have the content and design finished for #188 Elements, #189 Components, and #190 Layouts, we should update the template to make sure it's displaying all of the correct information for each pattern, in the right order.

https://github.com/IBM-Watson/design-library/blob/develop/library/templates/_pattern.html

**Comment by bobbinrobyn** [comment]
Blocked by #188, #189, and #190

**Comment by bobbinrobyn** [comment]
Some thoughts:

+ We don't need the "Rendered Pattern" and "Rendered Code" headings
+ At this point, the README will only include a pattern's long description
+ We need to add something to display the "Application Methods" variable

**Comment by Snugug** [comment]
No longer blocked on #190.

**Comment by bobbinrobyn** [comment]
@Snugug: You said that someone else could handle this issue, and I'm happy to attempt it, but I don't want to mess anything up. Should I just try something on my own branch? Or wait for you?

**Comment by Snugug** [comment]
@bobbinrobyn Either or? If you'd like to try it, it won't break anything in a branch. If it doesn't work, you've learned. Otherwise, I can work on it

**Comment by Snugug** [comment]
I was just removing the block because it isn't blocked on that

**Comment by ryanbrownhill** [comment]
@bobbinrobyn The PR's for the content are done :tada: Yayy! Were you planning on working on this as a next step?

**Comment by bobbinrobyn** [comment]
@ryanbrownhill Just kidding! I forgot there were those to-dos I listed up there. And I didn't see that @snugug said I could work on this. So I will do that today!

**Comment by bobbinrobyn** [comment]
I'm just over here taking liberties and inventing new functions...

How does this look as the template to pull in Application Methods, @snugug?
```
  <div library-class="pattern--methods" class="base--STYLED">
    {{ pattern.applicationMethods | safe -}}
  </div>
```
