### ISSUE TITLE
Update readme & YAML for each pattern

### ISSUE THREAD

**Issue by bobbinrobyn** [IBM-Watson/design-library#192]
Currently, there's a little bit of a inconsistency between the README for each pattern (for example, this guy: https://github.com/IBM-Watson/design-library/blob/develop/patterns/base/a/README.md) and the content model.

The README lists something called "Available Classes"
The content model calls that same information "Application Methods"

We need to resolve this inconsistency.

What that means is taking the "Available Classes" content *out* of the README and putting it in that pattern's YAML file under a variable called "Application Methods." This will enable us to treat the README and the application methods as separate information that can be styled and displayed differently.

(Also, at some point @Snugug will add a "Settings" variable to each YAML file.)

**Comment by Snugug** [comment]
Putting this on hold until @Lhuihui is done updating the headers
