### ISSUE TITLE
Create Sub-Content Templates

### ISSUE THREAD

**Issue by Snugug** [IBM-Watson/design-library#193]
The following sub-content types need [macro templates](https://github.com/IBM-Watson/design-library/tree/develop/library/templates/subcontent).

~~-[Value](https://github.com/IBM-Watson/design-library/wiki/Content-Models#value)~~
- [x] [Example](https://github.com/IBM-Watson/design-library/wiki/Content-Models#example) (compare)
- [x] [Example](https://github.com/IBM-Watson/design-library/wiki/Content-Models#example) (stand-alone)
- [x] [Aside](https://github.com/IBM-Watson/design-library/wiki/Content-Models#aside)
- [x] [Block Quote](https://github.com/IBM-Watson/design-library/wiki/Content-Models#block-quote)
- [x] [Color Swatches](https://github.com/IBM-Watson/design-library/wiki/Content-Models#color-swatch)
- [x] [Detail](https://github.com/IBM-Watson/design-library/wiki/Content-Models#detail)

**Comment by Snugug** [comment]
@IBM-Watson/pattern-library-owners Are we still using Value sub-content types anywhere? I couldn't find an example.

**Comment by britanyponvelle** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
@Snugug: Do we need a new content type & template for long lists? Like the list of elements on the Elements page (#188)?

**Comment by Snugug** [comment]
@bobbinrobyn No, I don't think so. It's just a definition list.

**Comment by Snugug** [comment]
Truthfully, I think Values just wind up being that too

**Comment by bobbinrobyn** [comment]
Okay, sounds good.

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
So we're not building out a values template. Should we decide to add a Values page, we'll use a definition list.

**Comment by ryanbrownhill** [comment]
:+1: close via @bobbinrobyn comments above.

**Comment by Snugug** [comment]
@
