### ISSUE TITLE
Design for Video Player Controls

### ISSUE THREAD

**Issue by ryanbrownhill** [IBM-Watson/design-library#202]
Customizing the design for video players that align with the design language.

Extended from #148

**Comment by ryanbrownhill** [comment]
Per @joshkimmell comment on #148 
The controls on movie two doesn't work.

**Comment by poofichu** [comment]
http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/animation.html

Just look at the controls for the first video.  Iconfont is used.

**Comment by ryanbrownhill** [comment]
@poofichu nice - are those the ibm design icons?

**Comment by poofichu** [comment]
@ryanbrownhill Sure are!

@britanyponvelle @bobbinrobyn @joshkimmell @Snugug Can I get comments or thumbs up?

**Comment by joshkimmell** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
:+1: Woooo! Looks great.

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by poofichu** [comment]
@britanyponvelle watcha think?

**Comment by britanyponvelle** [comment]
:+1:

**Comment by Snugug** [comment]
Design: :+1: 
Need to work on actual code/accessibility. Especially keyboard accessibility.

**Comment by poofichu** [comment]
@Snugug can you be specific?  Tabbing works as well as hitting spacebar (your favorite) to play/pause the video.

**Comment by Snugug** [comment]
When in Chrome, without using a mouse, if I tab to a button in the controls the controls don't appear. Play/pause and backwards/forwards do work.

**Comment by poofichu** [comment]
Closing this!!  Going to make a pull request for #148
