### ISSUE TITLE
How should navigation work in small screen

### ISSUE THREAD

**Issue by Lhuihui** [IBM-Watson/design-library#221]
Need to come up an efficient way to let users know where they are and easily navigate between pages.

**Comment by britanyponvelle** [comment]
My proposal is to have a "Back to Top" link/ button at the bottom of every page

Smashing Magazine does it here:

![screen shot 2015-05-04 at 5 12 44 pm](https://cloud.githubusercontent.com/assets/9538528/7463673/06fce4e0-f281-11e4-85c5-98112d581fd5.png)
![screen shot 2015-05-04 at 5 13 02 pm](https://cloud.githubusercontent.com/assets/9538528/7463672/06fbb480-f281-11e4-9ea2-c4431230f632.png)

**Comment by britanyponvelle** [comment]
With no sticky nav

**Comment by ryanbrownhill** [comment]
Britany Ponvelle [4:51 PM] 
@eva has tested it and says that users  felt when the sub-nav is gone, having a header nav sticking on top is confusing.

Sam Richard [4:53 PM] 
I’m in favor of `back to top` being available on all screen sizes

Ryan Brownhill [4:56 PM] 
I think the back to top should show only when the user has scrolled past the nav.
Only visible when it is necessary. :ghost: (edited)

Sam Richard [4:58 PM] 
@ryan_brownhill: binding to scroll is really crappy for performance. I was also only thinking of it being available in the footer, not as like a floating element (I hates me a floating overlaid element)

Ryan Brownhill [5:00 PM] 
Ooo we don't want :shit: performance. In that case I am ok with it being in the footer. :footprints:  My only concern is that what if they are in the middle of a very long page - they don't have any access to the scroll to top.

Summary: 
When the sub-nav is gone, having a header nav sticking on top is confusing.
Binding to scroll is not good for performance and should be avoided. 

Options: 
- Add `scroll to top` to footer
- Don't include `scroll to top` let them scroll.

**Comment by ryanbrownhill** [comment]
I am in favor for adding scroll to top in the footer like @britanyponvelle showcased [above](https://github.com/IBM-Watson/design-library/issues/221#issuecomment-98865890).

**Comment by Lhuihui** [comment]
Like Britany's proposal +1

**Comment by ryanbrownhill** [comment]
@IBM-Watson/design-acceleration :+1: ?

**Comment by britanyponvelle** [comment]
I mocked it up so we can see the "Back to top" button next to the footer. I tried the teal, to mimic the paragraph link styling, but when it's stacked above the orange 60 nav button it feels too busy. I think the grey will work best here.

![screen shot 2015-05-04 at 9 37 08 pm](https://cloud.githubusercontent.com/assets/9538528/7466325/3be106f8-f2a6-11e4-8627-472310754671.png)

![Uploading Screen Shot 2015-05-04 at 9.36.49 PM.png…]()


http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/color.html

**Comment by britanyponvelle** [comment]
I mocked it up so we can see the "Back to top" button next to the footer. I tried the teal, to mimic the paragraph link styling, but when it's stacked above the orange 60 nav button it feels too busy. I think the grey will work best here.

Thoughts?

![screen shot 2015-05-04 at 9 37 08 pm](https://cloud.githubusercontent.com/assets/9538528/7466325/3be106f8-f2a6-11e4-8627-472310754671.png)

![screen shot 2015-05-04 at 9 36 49 pm](https://cloud.githubusercontent.com/assets/9538528/7466337/5f9515da-f2a6-11e4-8708-f7328ae52175.png)



http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/color.html

**Comment by Snugug** [comment]
D

**Comment by Snugug** [comment]
Resolved by #277

**Comment by Snugug** [comment]
Launched!
