### ISSUE TITLE
Design Motion Interactions

### ISSUE THREAD

**Issue by joshkimmell** [IBM-Watson/design-library#225]
Hover states, content display, etc.

**Comment by ryanbrownhill** [comment]
Hover state I mocked up for the bottom nav animation - (Although we should be using our custom eases for now I just used an ease in)

![codepen-hover-2](https://cloud.githubusercontent.com/assets/9538395/7423396/4b949a32-ef5a-11e4-87d1-330d87530732.gif)

http://codepen.io/ryanbrownhill/pen/Ejjvvd?editors=110

**Comment by britanyponvelle** [comment]
:+1: hover state

**Comment by ryanbrownhill** [comment]
Hover State implemented in PR #277

**Comment by Snugug** [comment]
If this isn't in progress, can it be closed?
