### ISSUE TITLE
Correctly ordered folders

### ISSUE THREAD

**Issue by bobbinrobyn** [IBM-Watson/design-library#233]
Add appropriate prefixes to folders so that they display in the correct order (per the [information architecture](https://github.com/IBM-Watson/design-library/wiki/Information-Architecture-for-the-final-site) spelled out in the wiki)

**Comment by bobbinrobyn** [comment]
@Snugug: I think I read something you wrote about the correct way to go about numbering & naming folders, but now I can't find it :( Is this is the naming convention I should use?

01 - principles
02 - guidelines
03 - ui-patterns

**Comment by bobbinrobyn** [comment]
@Snugug: For instances where we want the folders to appear in alphabetical order, no prefixes are necessary, right?

![screen shot 2015-05-06 at 11 03 28 am](https://cloud.githubusercontent.com/assets/9341504/7497365/8e851860-f3df-11e4-97e7-95b7cc76cf08.png)

**Comment by Snugug** [comment]
On hold until the following are resolved:

- #253 
- #252 
- #251 
- #247 
- #245 
- #241 
- #237 
- #235 
- #231 
- #219

**Comment by Snugug** [comment]
All of those are merged! @bobbinrobyn go for it!

**Comment by bobbinrobyn** [comment]
Wooo! My moment to shine :star2:!

**Comment by bobbinrobyn** [comment]
Just kidding. Haha, that might be too much excitement for renaming folders.

**Comment by bobbinrobyn** [comment]
@Snugug, just so I'm 100% sure before I do all of them, is this the right way to rename folders? With the 01 and the dash?

01 - principles
02 - guidelines
03 - ui-patterns
