### ISSUE TITLE
Update Videos to have Play/Pause control

### ISSUE THREAD

**Issue by britanyponvelle** [IBM-Watson/design-library#238]
In our Animation [Accessibility guidelines](http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/accessibility.html), we state "When there is an animation that last longer than 5 seconds, provide the user a way to pause, stop, or hide the animation.", but we do not give the user that option to do so on some of our gifs. 

This issue was brought up from a couple of designers on Watson who have been looking at the prototype.

These pages need updating:
- [ ] [Accessibile animation example](http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/accessibility.html)
- [ ] [Responsive typography example](http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/typography.html)
- [ ] [Responsive Grids example](http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/grids.html)

**Comment by Snugug** [comment]
My recommendation is that we make these all videos and ensure that they have controls

**Comment by ryanbrownhill** [comment]
They all are .webm files already so it should be activating the player controls.

**Comment by Snugug** [comment]
Fabulous. In that case, we can close this. Videos rendered through our templates have controls on them.

**Comment by ryanbrownhill** [comment]
:ok_hand: Closing because assets are already videos and its about play controls activation.
