### ISSUE TITLE
Create Icon Font

### ISSUE THREAD

**Issue by poofichu** [IBM-Watson/design-library#254]
Create icon font within IcoMoon and also come up with all the accessible related ligatures.

**Comment by poofichu** [comment]
@Snugug Us doing this... does it depend on the icon licensing at all?

**Comment by Snugug** [comment]
Haha. now that's a good question.

**Comment by poofichu** [comment]
Yay!  We got clearance.

Now to fill out all the information correctly:
![image](https://cloud.githubusercontent.com/assets/6757613/7540723/78618036-f575-11e4-87e7-82df59947787.png)

**Comment by Snugug** [comment]
CC-BY
https://creativecommons.org/licenses/by/4.0/#

**Comment by poofichu** [comment]
Also, ligatures for each icon. Yay.  Here's what I have so far (totally up for discussion):

![image](https://cloud.githubusercontent.com/assets/6757613/7540959/28ee0086-f577-11e4-8931-13814f877a25.png)

@bobbinrobyn @Snugug @kathrynmcelroy ?

**Comment by bobbinrobyn** [comment]
Looks good to me! The only one I would add to is maybe putting "file" as another ligature for document_glyph

**Comment by Snugug** [comment]
@poofichu Why don't we standardize on the `(thing)` convention for all of our ligatures

**Comment by bobbinrobyn** [comment]
Also, how is the distinction between `previous_glyph` and `previous` going to work if you use the ligature "back"? Will the parentheses make it distinct?

**Comment by Snugug** [comment]
Why do we have two different icons for those things?

**Comment by Snugug** [comment]
We're already going to have a problem as `(back)` contains `back`

**Comment by bobbinrobyn** [comment]
I could be wrong, but I think the `next` and `previous` icons with the arrow in a circle are specific to our bottom navigation and not used anywhere else.

**Comment by Snugug** [comment]
Why don't we use the `next_glyph` and `_previous_glyph` there too?

**Comment by bobbinrobyn** [comment]
Possibly because the circled arrow is nicer...? Haha, at least in my opinion. I also thought it was what IBM Design Language used, but that is not true – they just use a little ` > ` in their bottom nav

**Comment by poofichu** [comment]
The reason we have two is because of size.  When you get down to glyph size (24) it's recommended to use the glyph as opposed to the full version.

**Comment by poofichu** [comment]
Here we go:

![image](https://cloud.githubusercontent.com/assets/6757613/7541929/955d62b4-f57e-11e4-8f58-236fdf4a15c4.png)

**Comment by Snugug** [comment]
We need an upward arrow for "top" as well

**Comment by poofichu** [comment]
Aww crap.  Forgot about that guy.

**Comment by poofichu** [comment]
![image](https://cloud.githubusercontent.com/assets/6757613/7542166/2d7fe35e-f580-11e4-872b-aa56dd87c0e8.png)

**Comment by Snugug** [comment]
:+1:

**Comment by poofichu** [comment]
@Snugug When creating a PR for this, where do I place said files?

**Comment by Snugug** [comment]
`library/fonts`

**Comment by poofichu** [comment]
![image](https://cloud.githubusercontent.com/assets/6757613/7543797/1328ae34-f58d-11e4-978d-ed1f001f4451.png)

**Comment by Snugug** [comment]
I'd rename the fonts `wdg`.

* Put all of the items in `fonts` into `library/fonts/wdg`
* Put `selection.json` into `library/fonts/wdg`
* Put `liga.js` into `library/js`

The rest can be ignored

**Comment by Snugug** [comment]
We also need positive and negative sentiment `(yes)` and `(no)`
