### ISSUE TITLE
Create Visual Examples for Performance Guidelines

### ISSUE THREAD

**Issue by poofichu** [IBM-Watson/design-library#263]
Reference #215 
and http://una.im/slides-nom-nom-perf/img/Jakob-Nielsen-response-time-infographic.jpg

**Comment by poofichu** [comment]
@Snugug I'll wait till we have content to see what other examples we can make.

**Comment by Snugug** [comment]
Writing this I think I know what I'd like the visuals to be:

- Response time inforgraphic
- Video comparing time completion in 100ms, 250ms, 1s, 3s, 5s, and 10s
- Video based on Notifying Users About Interface Delays (loading indicator appears after 100ms, removing loading indicator in favor of message saying "check back", or something like that, in the awesome wireframe format being used)
- Video comparing same motion at 10fps, 24fps, 30fps, and 60fps

**Comment by Snugug** [comment]
@ryanbrownhill I think the video comparing different FPS will be the hardest to make simply because of what it's asking? Do you have any insight into that?

**Comment by ryanbrownhill** [comment]
@Snugug Rendering out videos at different FPS isn't too hard. Maybe we just do the extremes (10fps vs 60fps) because the nuances between all of them together are very hard to see with an untrained eye. 

This shouldn't be too difficult as long as whatever we animate is moving very fast it will be easy to spot the difference.

**Comment by Snugug** [comment]
Oh I was thinking of one video showing the same thing at different frame rates; that way they could see a direct comparison in real time. I think something in the middle, 24 or 30, works be good too.

**Comment by ryanbrownhill** [comment]
I was imagining a videos for FPS and time completion side by side. Kinda like this Slide 66 from [this deck](https://speakerdeck.com/davatron5000/rwd-bloat)

![screen shot 2015-05-11 at 10 14 30 am](https://cloud.githubusercontent.com/assets/9538395/7568112/977a707e-f7c6-11e4-930f-77e3586d5a24.png)

**Comment by Snugug** [comment]
Side by side is fine (that's what I'm thinking too), but is only effective (especially for FPS) if triggered at the same time (so, the same video).

**Comment by ryanbrownhill** [comment]
@Snugug Correct that is what I was thinking! :ok_hand: 
What site do we want to use as an example? our prototype?

**Comment by Snugug** [comment]
Time completion I'd use our site (once we get the styling in) vs the Design Language site. That video is actually super simple stupid to make; Web Page Test will do it for us.

For FPS, I'd make a simple animation like you've done for animation, just at different FPS.

**Comment by ryanbrownhill** [comment]
Okey, sounds like a plan. I will work on the FPS. My plan is to use our loader for that? Or I should I create another animation?

On Hold until site done: Time Completion Example

**Comment by poofichu** [comment]
![image](https://cloud.githubusercontent.com/assets/6757613/7573490/ae6b7a9c-f7eb-11e4-9871-ea7a431d0789.png)

@Snugug @ryanbrownhill thoughts?  I kept the Watson logo off because we don't brand any of the other visual example.

**Comment by Snugug** [comment]
The only thing I'd say is to ensure that all of the scale is correct; that 0.1 seconds is 1/10 of 1 second, and 10 seconds is really 10 1 second chunks (which it all appears to be) So :+1:

**Comment by Snugug** [comment]
Maybe add in one of the smaller perf numbers, like 3 seconds, and point that 40% of users will leave a site there?

**Comment by ryanbrownhill** [comment]
FPS / Hertz Comparison.

![frame-rate-comparison](https://cloud.githubusercontent.com/assets/9538395/7574733/24df4808-f7f5-11e4-9e91-9ade691b105d.gif)

**Comment by Snugug** [comment]
I like it.

**Comment by bobbinrobyn** [comment]
Cool!

**Comment by poofichu** [comment]
SO GOOD :dancer:

**Comment by poofichu** [comment]
![image](https://cloud.githubusercontent.com/assets/6757613/7575128/1f9a8e04-f7f8-11e4-8061-106da152fe65.png)

Like zis?

**Comment by bobbinrobyn** [comment]
That's a pretty sweet performance graphic :)

**Comment by Snugug** [comment]
:+1: Adding that provides value for why we'd re-make that image

**Comment by poofichu** [comment]
![image](https://cloud.githubusercontent.com/assets/6757613/7575202/a937e8b4-f7f8-11e4-9631-5334fa858f24.png)

Moved source to bottom per @bobbinrobyn 's suggestion

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by joshkimmell** [comment]
:+1: so cool, you guys!

**Comment by Snugug** [comment]
There's a weird teal line on the side of the perf video :\

**Comment by ryanbrownhill** [comment]
.... Yep that is what happens when we compress it with MP4... I was having
a similar problem earlier. I believe it has to have a certain aspect ratio.
I will look into it when I get into work.

On Thursday, May 14, 2015, Sam Richard <notifications@github.com> wrote:

> There's a weird teal line on the side of the perf video :\
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IBM-Watson/design-library/issues/263#issuecomment-102003297>
> .
>


-- 
-Ryan G. Brownhill
ryanbrownhill.com
ryanbrownhill@gmail.com

**Comment by Snugug** [comment]
:ok_hand:
