### ISSUE TITLE
Update Patterns to Align With Guidelines

### ISSUE THREAD

**Issue by Snugug** [IBM-Watson/design-library#267]
There are a few things we do throughout our patterns that no longer align to our guidelines. Specifically, I'm seeing colors being used (especially in greyscale) that aren't part of our greyscale, use of alpha transparency, and mixing with black/white for tint/shade instead of using `color-tint` and `color-shade` functions from [IBM Design Colors](https://github.com/IBM-Design/colors#color-tint) to actually move up and down the color tints and shades.

We need to go through all of our patterns and ensure they're conforming to our guidelines as we've set them out.

**Comment by britanyponvelle** [comment]
@snugug can you give me an example of this?

**Comment by Snugug** [comment]
@britanyponvelle I think I may have fixed it in #277, but I see the following still:

* `./base/button/sass/_button.scss:    background-color: color('gray');`
* `./base/checkbox/sass/partials/_extends.scss:      border: setting-get('input border width') solid color('gray', 30);`
* `./base/code/sass/partials/_extends.scss:  outline: 1px solid rgba(color('gray'), .25);`
* `./base/input/sass/partials/_settings.scss:  'input border color': color('gray', 30),`
* `./base/pre/sass/partials/_extends.scss:  border: 1px solid rgba(color('gray'), .25);`
* `./base/radio/sass/partials/_extends.scss:      border: setting-get('input border width') solid color('gray', 30);`
* `./base/table/sass/partials/_extends.scss:  background-color: color('gray');`

**Comment by Snugug** [comment]
Let's get #277 merged in and then we can look at those.

**Comment by Snugug** [comment]
@britanyponvelle @poofichu One of you want to take a swing at this?

**Comment by poofichu** [comment]
Monday, I'll take it.
