### ISSUE TITLE
Intro for Patterns Sections

### ISSUE THREAD

**Issue by Snugug** [IBM-Watson/design-library#270]
Each pattern section (base/components, maybe layouts) need an intro paragraph and related Language markdown file. Guideline content type. If we don't want to include one for Layouts quite yet because we don't have any, that's cool, let's not include it,

- [x] `ui-patterns/patterns/base` - Base Elements
- [x] `ui-patterns/patterns/components` - Components
- [x] `ui-patterns/patterns/layouts` - Layouts

**Comment by bobbinrobyn** [comment]
@Snugug: Should there be some kind of template in the markdown file that brings in the list/links to individual pattern pages?

**Comment by Snugug** [comment]
@bobbinrobyn Nope. #271 resolves that

**Comment by bobbinrobyn** [comment]
Excellent. So literally all we're needing is:

```
---
type: guideline
title: Elements
---
Paragraph about elements goes here.
```

**Comment by Snugug** [comment]
Yes
