### ISSUE TITLE
Missing Content for 1.0 Release

### ISSUE THREAD

**Issue by Snugug** [IBM-Watson/design-library#276]
I'm going through all pages and looking for where content is missing/needs updating. The following needs updating:

- [x] `/guidelines/style/typography` - Visual Display of typeface combinations is missing, only visual alternatives available

**Comment by bobbinrobyn** [comment]
@britanyponvelle: Is this something you want me to work on? It looks like a super simple fix.

**Comment by poofichu** [comment]
I got this ;)
