### ISSUE TITLE
Proof read markdown

### ISSUE THREAD

**Issue by joshkimmell** [IBM-Watson/design-library#278]
Read through all the copy for grammatical errors/typos

**Comment by joshkimmell** [comment]
- [ ] Accessibility
- [ ] Color
- [ ] Grids
- [ ] Typography
- [ ] Animation
- [ ] Wordmark and Logo

**Comment by bobbinrobyn** [comment]
Hey! Kathryn has an Evernote in WDL Shared called "Full site feedback" that has a bunch of the little copy editing changes she was recommending.

**Comment by bobbinrobyn** [comment]
@joshkimmell ^^^

**Comment by bobbinrobyn** [comment]
@joshkimmell: Are you good if I take on some of this today?

**Comment by joshkimmell** [comment]
Sure…. I’ve already taken the accessibility and color pages.

**Comment by bobbinrobyn** [comment]
@joshkimmell: Are you going to submit PRs for the changes you made to Accessibility & Color? And did you see the changes Kathryn recommended for those pages? If you need help, just let me know!

**Comment by bobbinrobyn** [comment]
@IBM-Watson/design-acceleration: I'll proofread Grids tomorrow, submit a PR, and then this issue will be resolved!

**Comment by joshkimmell** [comment]
Yes. I'll submit them tomorrow.
