### ISSUE TITLE
Update Library to Guide

### ISSUE THREAD

**Issue by Snugug** [IBM-Watson/design-library#312]
There are a bunch of places where we use `library` and it should be `guide`. We should fix that.

- [x] Changelog (#313)
- [x] Contributing Guidelines (#313)
- [x] Readme (#313)
- [x] Bower.json (#313)
- [x] Wiki (#329)
- [x] Labels
- [x] Library folder
- [ ] Repo itself

**Comment by Snugug** [comment]
Last thing we're going to do for this milestone

**Comment by Snugug** [comment]
Update Library to be called Site in repo

**Comment by bobbinrobyn** [comment]
@Snugug @poofichu I have written down that I would help with this, but now I can't remember exactly what I said I would do. Do I need to go through the current website to look for instances where we say "library" or go through the GitHub wiki to look for that?
