### ISSUE TITLE
Clean Up Wiki

### ISSUE THREAD

**Issue by Snugug** [IBM-Watson/design-library#329]
Our Wiki has a bit of cruft in it that we should include for launch. We should clean it up.

- [x] Remove duplicate content from wiki
- [x] Update initial page with intro
- [x] Group content together on home page
- [x] Create custom sidebar with custom page groupings for easy navigation

**Comment by bobbinrobyn** [comment]
I can tackle this today!

**Comment by bobbinrobyn** [comment]
![screen shot 2015-05-18 at 11 34 42 am](https://cloud.githubusercontent.com/assets/9341504/7685194/ec40eb70-fd51-11e4-99fe-e21466e0f1a5.png)

What do y'all think about these categories for the wiki sidebar?

**Comment by bobbinrobyn** [comment]
@Snugug, what did you mean by "group content together on home page?"

**Comment by Snugug** [comment]
@bobbinrobyn Basically, these groups on the home page of the Wiki too

**Comment by Snugug** [comment]
Also, :+1:

**Comment by kathrynmcelroy** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
Okay, closing this issue! (No PR)
