### ISSUE TITLE
Wordmark and Logo page - image sizing

### ISSUE THREAD

**Issue by joshkimmell** [IBM-Watson/design-library#339]
Logo image is too large (left)... compare to logo image on prototype (right)

**Comment by joshkimmell** [comment]
![screen shot 2015-05-18 at 4 54 10 pm](https://cloud.githubusercontent.com/assets/8161298/7691363/77253476-fd7f-11e4-97ac-303aed5b19b2.png)

**Comment by joshkimmell** [comment]
@channel: is it me or is the background color white?

**Comment by Snugug** [comment]
@joshkimmell In the prototype, that logo was hand-corrected which, when not hand-coding each individual example, we can't do.

**Comment by Snugug** [comment]
But yes, the wordmark and logo examples need to be updated so similar examples are the same size

**Comment by Snugug** [comment]
@bobbinrobyn @poofichu How do we want to proceed knowing we can't add styling specifically to that image

**Comment by poofichu** [comment]
@joshkimmell @bobbinrobyn We have a choice between the way it was previous (look at Josh's screenshot above) vs. this awesomeness.  Thoughts?

![image](https://cloud.githubusercontent.com/assets/6757613/8188474/3c905604-1424-11e5-94e1-99f399c52d6a.png)

**Comment by poofichu** [comment]
Small screen:
![image](https://cloud.githubusercontent.com/assets/6757613/8188501/5c4a035a-1424-11e5-8068-655c177c9a73.png)

**Comment by bobbinrobyn** [comment]
Yes! :+1:

**Comment by kathrynmcelroy** [comment]
Yes to the new version!

**Comment by bobbinrobyn** [comment]
Yes to the new version!
