### ISSUE TITLE
Investigate a Sticky Footer

### ISSUE THREAD

**Issue by Snugug** [IBM-Watson/design-library#342]
Our footer currently doesn't stick to the bottom of the screen if the screen height is larger than the content. Investigate ways to allow it to stick to the bottom of the screen without JavaScript

**Comment by joshkimmell** [comment]
Also, the top padding of the footer on the home page differs from the rest of the site.

**Comment by Snugug** [comment]
Resolved by https://github.com/IBM-Watson/design-library/pull/345
