### ISSUE TITLE
CSS? Error in Firefox???

### ISSUE THREAD

**Issue by joshkimmell** [IBM-Watson/design-library#343]
Error occurs (so far) only in Firefox.

**Comment by joshkimmell** [comment]
![screen shot 2015-05-19 at 11 15 43 am](https://cloud.githubusercontent.com/assets/8161298/7708599/6486056e-fe1c-11e4-8872-39ce435b34b9.png)

**Comment by Snugug** [comment]
I'm unable to reproduce.

Please provide your version of Firefox, that Firefox is updated, and try refreshing with a clean cache

**Comment by Snugug** [comment]
![Same page, working in Firefox](https://cloud.githubusercontent.com/assets/377188/7708636/05e46d44-fe25-11e4-8663-91a72de4181d.png)

**Comment by joshkimmell** [comment]
![screen shot 2015-05-19 at 11 46 12 am](https://cloud.githubusercontent.com/assets/8161298/7708645/ac4cc9f0-fe1c-11e4-97bd-8f202ae2a1a6.png)

**Comment by joshkimmell** [comment]
Kathryn saw it, too

**Comment by Snugug** [comment]
The current version of Firefox ESR is 31.7.0

Please try refreshing the site again.

**Comment by Snugug** [comment]
And updating Firefox

**Comment by Snugug** [comment]
Do you have any Firefox plugins or software running that may interfere with the rendering of a page?

**Comment by joshkimmell** [comment]
I doubt that Kathryn and I have the same plugins.

**Comment by Snugug** [comment]
I understand that you both saw that error, but checking in the latest version of Firefox ESR with no plugins it renders normally. I'm trying to debug the reason you're seeing issues

**Comment by joshkimmell** [comment]
I know... Removed FF. Installing fresh version from IBM App Store.

**Comment by joshkimmell** [comment]
It installed the same version

**Comment by joshkimmell** [comment]
cleared the cache and the page loaded correctly

**Comment by Snugug** [comment]
Awesome.
