### ISSUE TITLE
Provide rendered examples

### ISSUE THREAD

**Issue by kevinSuttle** [IBM-Watson/design-library#37]
This would be handy.

**Comment by Snugug** [comment]
Yup, that's on the list, just haven't gotten around to it. It's high in our backlog

**Comment by kevinSuttle** [comment]
:+1:

**Comment by Snugug** [comment]
Waiting on merge to `master` for RC2 to complete

**Comment by joshkimmell** [comment]
Rendered examples of what?

**Comment by Snugug** [comment]
Patterns.

**Comment by bobbinrobyn** [comment]
Are we providing an entire rendered page of patterns? Or is this referring to each individual pattern page?

**Comment by Snugug** [comment]
This is what we've been discussing.

**Comment by joshkimmell** [comment]
yup... got it.

**Comment by Snugug** [comment]
This is done. 

Example rendered component:

http://watsondesign.guide/ui-patterns/patterns/base/button/
