### ISSUE TITLE
Back to Top on Homepage

### ISSUE THREAD

**Issue by poofichu** [IBM-Watson/design-library#370]
Fix me!

Needs some padding/margin/rhythm love around it.

![image](https://cloud.githubusercontent.com/assets/6757613/7711065/b7c65a4c-fe2d-11e4-8401-e523b0415b1c.png)

**Comment by Snugug** [comment]
Fix me isn't good enough. What's wrong with it?

**Comment by Snugug** [comment]
https://github.com/IBM-Watson/design-library/blob/develop/library/sass/components/_home.scss
