### ISSUE TITLE
Refine Viewport on Mobile for UI Patterns Page

### ISSUE THREAD

**Issue by ryanbrownhill** [IBM-Watson/design-library#383]
The viewport for the UI Patterns page renders differently then Principles & Guidlines

**Comment by ryanbrownhill** [comment]
![img_5447](https://cloud.githubusercontent.com/assets/9538395/7728417/b89f65ba-fed4-11e4-9ba7-994d62315395.PNG)
![img_5446](https://cloud.githubusercontent.com/assets/9538395/7728416/b89ecd58-fed4-11e4-9176-03da2cf6cb06.PNG)

**Comment by Snugug** [comment]
Duplicate of #390
