### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by bobbinrobyn** [IBM-Watson/design-library#391]
- [x] three primary colors
- [x] Linda van Deursen
- [x] Sass and CSS Development Guidelines
- [x] JavaScript Development Guidelines
- [x] typographic scale

http://watsondesign.guide/guidelines/branding/wordmark/
![image](https://cloud.githubusercontent.com/assets/9341504/7731115/d6181eac-fee3-11e4-9bba-7d420b46b891.png)

http://watsondesign.guide/guidelines/style/grids/
![image](https://cloud.githubusercontent.com/assets/9341504/7733111/9e2d287a-fef2-11e4-9d15-056a32add8f0.png)

http://watsondesign.guide/ui-patterns/documentation/getting-started/
![image](https://cloud.githubusercontent.com/assets/9341504/7734458/c2f14c82-fefb-11e4-8be5-a5ff7af36c38.png)
![image](https://cloud.githubusercontent.com/assets/9341504/7734474/d9c1b424-fefb-11e4-93d2-3fd5cb42339b.png)

http://watsondesign.guide/guidelines/style/grids/
![image](https://cloud.githubusercontent.com/assets/9341504/7757171/e27c2264-ffc5-11e4-8a52-1efc1ec5b506.png)

**Comment by bobbinrobyn** [comment]
Okay, upon further investigation the Linda van Deursen quote is not supposed to be a link. It's just being styled as one because of this template (even though it doesn't have a linkToSource attribute). Is there something we can put in the template to say "don't wrap in <a> tags if there's no linkToSource"?

![image](https://cloud.githubusercontent.com/assets/9341504/7757430/deb9ddc2-ffc7-11e4-8d21-9476ad0ac0de.png)

![image](https://cloud.githubusercontent.com/assets/9341504/7757436/f0cd8f5e-ffc7-11e4-9d38-2f9f4ffaf8d7.png)

**Comment by bobbinrobyn** [comment]
^^^ @Snugug or @poofichu?

**Comment by bobbinrobyn** [comment]
Also @Snugug, do we have Sass, CSS, and JavaScript development guidelines? Right now those pages do not exist :/

I'll leave it for now, but I think we should take out those two sentences if we don't actually have those pages.

**Comment by Snugug** [comment]
Sass and JS dev guidelines being released in 1.1

**Comment by Snugug** [comment]
add `(coming soon)`

**Comment by Snugug** [comment]
@bobbinrobyn How goes this?
