### ISSUE TITLE
"Settings" column displays when there are no settings

### ISSUE THREAD

**Issue by joshkimmell** [IBM-Watson/design-library#409]

**Comment by joshkimmell** [comment]
![image](https://cloud.githubusercontent.com/assets/8161298/7770888/918fb8aa-0058-11e5-8fd5-7aeb9c7ef52f.png)

**Comment by Snugug** [comment]
https://github.com/IBM-Watson/design-library/blob/develop/library/templates/_pattern.html

**Comment by Snugug** [comment]
```
{% if pattern.metadata.settings %}
// code for settings column
{% endif %}
```

**Comment by Snugug** [comment]
@bobbinrobyn How goes this?

**Comment by bobbinrobyn** [comment]
Done and done.
