### ISSUE TITLE
Add "title" to Color Page Content Model

### ISSUE THREAD

**Issue by poofichu** [IBM-Watson/design-library#429]
For the new redesign, I need to add a title to the content model:

![image](https://cloud.githubusercontent.com/assets/6757613/8308478/937161d2-198a-11e5-9c6d-62750323d7ec.png)

**Comment by Snugug** [comment]
The [Group Swatches](https://github.com/IBM-Watson/design-library/wiki/Content-Models#color-swatch) display of color palettes expects an `instructions` attribute explaining the array of colors. Have you tried that?

**Comment by poofichu** [comment]
Not needed anymore.  Page went a different direction.
