### ISSUE TITLE
Contributing Guidelines

### ISSUE THREAD

**Issue by Snugug** [IBM-Watson/design-library#66]
Write contributing guidelines

**Comment by una** [comment]
Also, not just contributing docs, but docs that outline how to navigate through this code base and how we are naming variables, using settings, etc.

We need to avoid linking out to external sources and provide real information within this project that specifically relates to this project. Having a developer go on a chase for information will decrease clarity and increase ramp up time.

**Comment by ryanbrownhill** [comment]
:+1: can close when #171 is merged
