### ISSUE TITLE
Style Tile for Library

### ISSUE THREAD

**Issue by Snugug** [IBM-Watson/design-library#68]
Determine style tile for design library

**Comment by britanyponvelle** [comment]
[  ] Get existing style tile work from Jeri
[  ] Determine necessary  elements for style tile
[  ] Test chosen color palettes from color workshop 
[ x ] Explore other style tile examples

**Comment by britanyponvelle** [comment]
@Snugug can you label this "visual"?

**Comment by britanyponvelle** [comment]
See progress on the style tile here: http://pages.design.ibm.com/jeribowers/wdl-style-tile/master/index.htm

**Comment by britanyponvelle** [comment]
Here is a overview of the elements I think we'll need in the style tile:
- [ ] Tag
- [ ] in-line code snippet
- [ ] block code snippet
- [ ] link
- [ ] call-out box
- [ ] h1 - h6
- [ ] small meta text
- [ ] body text
- [ ] strong text
- [ ] emphasized text
- [ ] unordered list
- [ ] Primary button
- [ ] Secondary button
- [ ] Tertiary button

![screen shot 2015-03-04 at 9 59 20 am](https://cloud.githubusercontent.com/assets/9538528/6487237/97b72d58-c255-11e4-979f-168309ddaafd.png)

**Comment by britanyponvelle** [comment]
And here is a closer look at sections:

Headings & Body Text
![screen shot 2015-03-04 at 10 04 15 am](https://cloud.githubusercontent.com/assets/9538528/6487300/fc521552-c255-11e4-9ca3-df7dc9a42a3f.png)

Links, Bullets, code snippets, block quote
![screen shot 2015-03-04 at 10 06 08 am](https://cloud.githubusercontent.com/assets/9538528/6487324/2709dd34-c256-11e4-8163-0d6a11d82fbb.png)

Navigation
![screen shot 2015-03-04 at 10 07 53 am](https://cloud.githubusercontent.com/assets/9538528/6487359/56f569fa-c256-11e4-88ae-efecb73e50bf.png)

Tags and Buttons
![screen shot 2015-03-04 at 10 08 18 am](https://cloud.githubusercontent.com/assets/9538528/6487369/677dc11e-c256-11e4-954f-e5694234e628.png)

Call-out Box
![screen shot 2015-03-04 at 10 08 55 am](https://cloud.githubusercontent.com/assets/9538528/6487388/856ff728-c256-11e4-8431-bd31db55051d.png)

**Comment by Snugug** [comment]
Have we looked at this for accessibility? For instance, the link color is only accessible for text above 18pt font or 14pt if bold.

I'm also a little unsure of the font sizes that are provided. `.33`em is roughly `6px` font size, where as `5.610em` is roughly `90px`. The `pt` sizes are also incorrect; `12pt` == `16px` == `1em` == `100%`. Can you please provide updated font sizes to [reflect font sizing on the web](http://websemantics.co.uk/resources/font_size_conversion_chart/)

We already have button styles in place; are these meant to change those button styles, or are we to update our button and form styling to match this style tile? Ideally our design library would use our pattern library to build itself.

Finally, are the colors presented representative of our "light" color palette for the pattern library? If so, we should codify that.

**Comment by Snugug** [comment]
Another thought; the indentation for lists looks to be very large; thoughts on making it either in-line with the flow of the text coming from it (so the left edge of the bullet/number lines up with the left edge of a paragraph's text) or [hanging the bullets](http://www.markboulton.co.uk/journal/five-simple-steps-to-better-typography-part-2)?

**Comment by joshkimmell** [comment]
I'm not a fan of hanging bullets. The point of a list is to differentiate itself from the body of the content. I agree with making the list element (bullet or number) in-line with the rest of the body.

**Comment by britanyponvelle** [comment]
@Snugug sorry about that, I mistyped "pt". I've updated it now. Does that look right? Agreed on hanging bullets. Doing that now.

**Comment by Snugug** [comment]
The sizes look much better now.

Do the colors come from the IBM Design colors or from our workshop or both (or neither)?

**Comment by britanyponvelle** [comment]
@Snugug these are IBM design colors. @bobbinrobyn is working on matching the colors from the color workshop to IBM Design colors, so as she works on that I can test those.

**Comment by Snugug** [comment]
Awesome, thanks!

Can you include what the colors are?

**Comment by britanyponvelle** [comment]
Yes, I can definitely do that! I will work on including those today. Also, I was not meaning to replace the existing button styles. How do I find out what the existing style for those are? I wanted to include them on the style tile for color testing.

**Comment by Snugug** [comment]
Partner with @una so she can show you what we have already.

**Comment by Snugug** [comment]
@britanyponvelle @bobbinrobyn For lists, do we want text for the 2nd line of a list to wrap under the bullet or be flush with the start of the line of text?

![List item position inside](https://cloud.githubusercontent.com/assets/377188/6490423/333cbd4c-c274-11e4-92b8-812dd2afaa6f.png)

![List item position outside](https://cloud.githubusercontent.com/assets/377188/6490429/3977e8da-c274-11e4-9925-1deac6e31e96.png)

**Comment by Snugug** [comment]
And for ordered lists, do we want numbers, numbers with leading zeros, roman numerals, alphas? What [style](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type)

**Comment by britanyponvelle** [comment]
@Snugug I think text for bullets should be flush at the start of the next line of text. It's less distracting and easier to make out individual points. 

For ordered lists, I prefer numbers without zeros in case there are any long lists. Roman numerals aren't as common, and leading with zero doesn't really add anything beneficial.  Thoughts?

**Comment by britanyponvelle** [comment]
@Snugug @joshkimmell For Beta 1, what kind of deliverable did you have in mind specifically?

**Comment by britanyponvelle** [comment]
Updated: lists, unordered lists, Electricity color palette (using IBM Design colors)
![screen shot 2015-03-04 at 4 18 56 pm](https://cloud.githubusercontent.com/assets/9538528/6494869/87695978-c28a-11e4-9086-09ccef12228b.png)

**Comment by Snugug** [comment]
Liking how this is coming together. I'm going to update the the list PR with the new direction.

The link color here is much better than it previously was and now passes AA accessibility for any size text. You can check accessibility [here](http://leaverou.github.io/contrast-ratio/). The blockquote text color only passes AA accessibility standards for text size `18pt` (not `px`) or higher, or `14pt` bold text.

**Comment by Snugug** [comment]
I'm also curious: are you building these style tiles to test different color palettes, or are we narrowing down which palette we're going to use for the actual site? If it's the later, that's related to #94 and we're going to need both dark and light palettes.

**Comment by britanyponvelle** [comment]
@Snugug Ok great! Thanks for the link. To answer your second question, it's a bit of both. Right now we are using it to test color palettes to narrow down which palette we will use for the actual site. The decision for which palette we will be using will be primarily based on user testing @bobbinrobyn is doing.

**Comment by Snugug** [comment]
@britanyponvelle is it safe to say these are the font sizes for our headers? If so, might I suggest that they'e a little big? 90px for a h1 and 67px for an h2 are kinda huge and are going to overwhelm content around it. Think of what a 90px h1 would look like on a mobile device; it'd take up almost 1/5 of a the screen. To give you a reference, the browser default is 32px.

I assume these sizes were chosen based on the Design Language's [Type Scales](http://www.ibm.com/design/language/framework/visual/typography.shtml) (or modular scales, which appear to have been updated to allow for more than just the perfect fourth scale).

If you haven't read it already, I highly recommend reading [More Meaningful Typography](http://alistapart.com/article/more-meaningful-typography) to learn about why we should use modular scales when designing typography. One of the more powerful things you can do when creating modular scales is to create a double stranded scale; one that has more than 1 important number (base font size) or more than 1 type scale (ratio). They let us fill in the gaps that may be present in a single stringed scale. Tim Brown (who wrote More Meaningful Typography) and Scott Kellum (Sr Front End for Vox) have made a [modular scale site](http://www.modularscale.com/?1,3&em&1.333&sass&text) where you can play with multi stranded scales visually (I've added one with two bases initially). It'll even tell you what modular scale number you should use (the `ms()` part) and what Sass settings to use for the `modular-scale` Sass plugin

Finally, something to think about is [responsive typography](http://shop.oreilly.com/product/0636920034063.do) and how our type will look at different screen sizes. I wouldn't drop our body copy below 1em, but shaking up our scale and line height (which we need to include here too) at smaller sizes due to a smaller measure, and larger at larger screens. Mark Bolton's [Five simple steps to better typography](http://www.markboulton.co.uk/journal/five-simple-steps-to-better-typography) is a little outdated but provides a good overview of how the core pieces of typography work together.

**Comment by Snugug** [comment]
For what it's worth, when I'm working on determining typography, I doit from the view of an article: how would all of these pieces work together in long-form text. This I find provides me with the best overall legibility for the core of my typography, while allowing one-offs like callout font sizes to live on their own. Something to consider.

**Comment by britanyponvelle** [comment]
Thanks for the references, Sam. I've reworked the typography section a bit. I narrowed the H tags down to support the content in the content model Kathryn and Robyn are working on. The base size is still 1 em, but I incorporated 2 ratios for determine type size: Perfect Fourth and Major Third. Perfect Fourth ratio for desktops and tablets, making H1 about 2.5 the size of the body text for clearer contrast. Major Third ratio for phone screen sizes, making H1 only twice the size of the body text so it doesn’t overwhelm the content. Thoughts? @joshkimmell @Snugug @poofichu 

![screen shot 2015-03-05 at 2 22 20 pm](https://cloud.githubusercontent.com/assets/9538528/6514087/62b22ff4-c345-11e4-9f13-3ed7bdb17652.png)

Here is a closer look at the typography section:
![screen shot 2015-03-05 at 2 21 51 pm](https://cloud.githubusercontent.com/assets/9538528/6514100/81e1fba2-c345-11e4-884a-a8bcdfec78fb.png)

**Comment by britanyponvelle** [comment]
Thanks for the references, Sam. I've reworked the typography section a bit. I narrowed the H tags down to support the content in the content model Kathryn and Robyn are working on. The base size is still 1 em, but I incorporated 2 ratios for determine type size: Perfect Fourth and Major Third. Perfect Fourth ratio for desktops and tablets, making H1 about 2.5 the size of the body text for clearer contrast. Major Third ratio for phone screen sizes, making H1 only twice the size of the body text so it doesn’t overwhelm the content. Thoughts? @joshkimmell @Snugug @poofichu

![wdl-style-tile-01](https://cloud.githubusercontent.com/assets/9538528/6514495/868dc656-c348-11e4-92d2-ad7d3f583066.png)

![screen shot 2015-03-05 at 3 01 44 pm](https://cloud.githubusercontent.com/assets/9538528/6514504/9b066ffc-c348-11e4-80a5-080647540fd4.png)

**Comment by Snugug** [comment]
Awesome. I did. If you could include the modular scale size that'd be awesome.

As for swapping from one scale to another, phone/tablet/desktop aren't really good descriptors; their sizes vary widely and often overlap with each other. Instead of talking about them in terms of device categories (and in general when we do responsive work), I'd encourage you to throw these into the browser and see what size the browser is when you want to switch from one to another.

I also notice that in these new tiles you've dropped H4-6 styling

**Comment by britanyponvelle** [comment]
Yes, I can definitely include a scale! And I will work on putting type in the browser tomorrow and change "desktop and phone". I knew that wouldn't fly :) I am new to designing in the browser, but up to the challenge. 

Also, I dropped the H4-H6 because I didn't think we would need them for the content we will have on the site. I was thinking we could style them later if we find we need more sizes.

**Comment by Snugug** [comment]
:stuck_out_tongue_closed_eyes: 

Awesome! If you'd like to pair with me tomorrow on that I've got some time.

For the H4-H6, they have semantic meaning even if they won't be used often, so we should include some styling for them. It doesn't need to be much, just enough to have a distinct visual hierarchy (or enough to distinguish them from paragraph text)

**Comment by britanyponvelle** [comment]
Okay, great! I will shoot you a message tomorrow. 

I will work on H4-H6. Also, for the modular scale size, did you have something like this in mind:
![screen shot 2015-03-05 at 5 11 29 pm](https://cloud.githubusercontent.com/assets/9538528/6516836/09c0d13c-c35b-11e4-8348-ce03770df00f.png)

or 

![screen shot 2015-03-05 at 5 11 22 pm](https://cloud.githubusercontent.com/assets/9538528/6516849/1a144d0c-c35b-11e4-827c-4f140f508998.png)

or something else?

**Comment by Snugug** [comment]
Actually, much easier than that. If you use the modular scale link that I sent, simply set it to one setting and copy/paste the link here, then set the other one and do the same. That'll provide me with everything I need to know!

**Comment by britanyponvelle** [comment]
Ah, ok! Here it is: http://www.modularscale.com/?16&px&1.333,1.25&web&text

**Comment by Snugug** [comment]
Awesome, thanks!

**Comment by britanyponvelle** [comment]
Updated H4-6 tags

![wdl-style-tile-v2-01](https://cloud.githubusercontent.com/assets/9538528/6518781/7c89a6e8-c370-11e4-8d83-b58691ac155d.png)

![wdl-style-tile-typography-03](https://cloud.githubusercontent.com/assets/9538528/6518797/d3c6dcbe-c370-11e4-894a-995e521b2cb9.png)

**Comment by britanyponvelle** [comment]
Updated H4-6 tags

![wdl-style-tile-v3-01](https://cloud.githubusercontent.com/assets/9538528/6518818/1d81b59a-c371-11e4-9ddb-94b8c817e279.png)

![wdl-style-tile-v3-03](https://cloud.githubusercontent.com/assets/9538528/6518817/1d817e72-c371-11e4-9924-99dcd9259243.png)

**Comment by britanyponvelle** [comment]
Here is the typography in browser: http://pages.design.ibm.com/blponvel/wdl-typography-test/gh-pages/

Working on updating it to Helvetica Neue (This is regular Helvetica) thanks for the reminder @joshkimmell /doh

**Comment by Snugug** [comment]
Was this completed?

**Comment by britanyponvelle** [comment]
Yep, if everyone is on board with these decisions so far I think we can close it. @joshkimmell @poofichu 

I've updated the tile with the newest info (breakpoints and headings)
![wdl-style-tile-v4-01](https://cloud.githubusercontent.com/assets/9538528/6609400/d7c1b1f6-c81e-11e4-9752-b8bdbdf1eef0.png)

**Comment by britanyponvelle** [comment]
@Snugug Josh gave the ok to close this issue. The elements are there, but we will continue to use the tile to help us iterate the visual design of the site.

**Comment by Snugug** [comment]
Yup, closing it just means we're done with this work, not that we won't build on it. Closing!

**Comment by britanyponvelle** [comment]
Iteration update: 
- Added secondary colors using lighter tints to brighten up the palette
- moved orange 30 to the secondary palette, and orange 50 to primary so it can be integrated easier
- experimenting with buttons
- took line numbers out of code snippets and added a stronger weight

![wdl-style-tile-v5-04](https://cloud.githubusercontent.com/assets/9538528/6626835/c709861e-c8c7-11e4-8811-b1aea180c135.png)

![wdl-style-tile-v5-05](https://cloud.githubusercontent.com/assets/9538528/6626838/cd261ef4-c8c7-11e4-87e9-6c4ce9dae5a0.png)

**Comment by britanyponvelle** [comment]
updated:

![wdl-style-tile-v2-06](https://cloud.githubusercontent.com/assets/9538528/6968686/321049c2-d92e-11e4-91de-b63a512a5c03.png)
