### ISSUE TITLE
Design for Library

### ISSUE THREAD

**Issue by Snugug** [IBM-Watson/design-library#71]
# Pages:

Principles
- [x] Introduction #121 
- [x] Design Principles #116 

Guidelines
- [x] Color #138 
- [x] Typography #139 
- [x] Iconography #147 
- [x] Accessibility #140 
- [x] Grids #146 
- [x] Animation #148 
- [x] Signature Patterns #149 
- [x] Logo #141 
- [x] Wordmark #142 

UI Patterns
- [x] Elements #163

**Comment by britanyponvelle** [comment]
@Snugug can you label this "visual"?

**Comment by britanyponvelle** [comment]
- [ ] Use style tiles and wireframes from Kathryn and Roybn to create mockup

**Comment by britanyponvelle** [comment]
@kathrynmcelroy, can you update @poofichu and I on your timeline for #70 and #69 so we can make a plan to work alongside each other this week? They are a bit of a blocker for this issue (which is also due at Beta 2)

**Comment by kathrynmcelroy** [comment]
@britanyponvelle I'll update you after my catch-up chat with Josh this morning.

**Comment by britanyponvelle** [comment]
#123 is a bit of a blocker. @poofichu and I are going to work along @kathrynmcelroy when she begins to develop the wireframes.

**Comment by britanyponvelle** [comment]
Mockup of color page for browsers larger than 1000px:

![wdl-large-color-06](https://cloud.githubusercontent.com/assets/9538528/6902805/bf7f52da-d6db-11e4-81f4-e9ea227a17a5.png)

**Comment by britanyponvelle** [comment]
Here is a mockup of the UI Patterns page:

![wdl-patterns-button-07](https://cloud.githubusercontent.com/assets/9538528/6905487/f2e6da6e-d6ed-11e4-88fc-6fa8f051743d.png)

I'm still working on getting the code snippets right. @Snugug what are your thoughts on having multiple colors assigned to bits of code, vs. all one color?

**Comment by poofichu** [comment]
Just to add my 2 cents...  I like the simple one you have here on [http://pointnorth.io/#content-modeling](North).  It's simple black and white.  If we do add colors, I would like to avoid bright blues, pinks, and greens like you have on the [http://pointnorth.io/#general-coding-syntax](Coding Syntax Page)

**Comment by britanyponvelle** [comment]
ahh yes thanks for the feedback! The dark background with white text helps the code stand out from the rest of the page. I can try that as well.

**Comment by Snugug** [comment]
@britanyponvelle We should also talk about the code snippets. We're going to be using [Prism](http://prismjs.com/) for syntax highlighting; we should design the styling taking into account the advanced syntax highlighting that can be applied using it (and potentially bring it into the pattern library as a more advanced code snippet)

**Comment by britanyponvelle** [comment]
Mockup of dark background for code snippets:

![wdl-patterns-button-v2](https://cloud.githubusercontent.com/assets/9538528/6906262/58ba9678-d6f3-11e4-9e12-a3e4ad6652af.png)

**Comment by Snugug** [comment]
Right now, `available classes` isn't a separate piece of content, it's part of the documentation. Should we spin them out into separate attributes?

**Comment by poofichu** [comment]
@Snugug Does Prism just handle all the color styling itself?  Or can we control some of it?

**Comment by Snugug** [comment]
@poofichu Prism gives us tokens we can style

**Comment by britanyponvelle** [comment]
ahh I see. So depending one weather we choose a light or dark background, we can place in IBM colors that are accessible. Is there a way I can see each of the colors they have here and their associations? So I can match the IBM Design colors.

**Comment by Snugug** [comment]
If you take a look at the different themes, you can see how stuff gets associated (basically, any of the token classes). I like [Okaidia](https://github.com/PrismJS/prism/blob/gh-pages/themes/prism-okaidia.css) the best (if you click the different themes, you can see how they apply)

**Comment by britanyponvelle** [comment]
On the Okaiadia page there are 9 different colors listed for tokens. Is that how many colors we will need to define?

**Comment by Snugug** [comment]
Yup. Looks that way.

**Comment by britanyponvelle** [comment]
I took the colors on the Okaiadia page, and matched IBM colors, so we have: colors on the 20 scale, grey 20, grey 70, and neutral 2.

![wdl-elements-large](https://cloud.githubusercontent.com/assets/9538528/6920741/fa14ac38-d785-11e4-9085-e1da48e32d5d.png)


![wdl-elements-small](https://cloud.githubusercontent.com/assets/9538528/6920742/fa19c1f0-d785-11e4-86ad-0966fda01ef7.png)

**Comment by Snugug** [comment]
@britanyponvelle Awesome. I just opened #137 to bring these officially into our pattern library. To provide some insight, syntax highlighting is only applied to blocks of code, not inline code (which will inherit our default inline code styling).

**Comment by britanyponvelle** [comment]
Ok, great! Thanks. I was unsure about the inline code.

**Comment by britanyponvelle** [comment]
@poofichu @joshkimmell What do you think about these treatments for block quotes and the "aside" boxes?

![block-quote-aside-box-07](https://cloud.githubusercontent.com/assets/9538528/7047136/3d50e106-ddd0-11e4-813c-4d4a308e4fdd.png)

**Comment by Snugug** [comment]
I'd avoid the bar on the side for the `aside` as it's a common pattern for `blockquotes` and users may get confused.

I'd also have us avoid using the same (or similar ) styling for `blockquote` and `aside`

**Comment by britanyponvelle** [comment]
Agreed, the two should be different. If the side bar stays for the `block quote`, we won't use it for  `aside`

**Comment by poofichu** [comment]
I still like the orange bar on the side for `blockquote`.  And I'm kind of digging the blue bar on top for the `aside`

**Comment by britanyponvelle** [comment]
Here is the `aside` box with the grey
http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/typography.html

Caption size text and 75% width. Thoughts? I will test the teal too!

**Comment by britanyponvelle** [comment]
Teal option:
![teal-bar-small](https://cloud.githubusercontent.com/assets/9538528/7048578/7c93e058-ddd9-11e4-893b-f603bc2f16b3.png)
![teal-bar-large](https://cloud.githubusercontent.com/assets/9538528/7048581/80aac300-ddd9-11e4-8dee-68fd14c58c9f.png)

Grey option:
![grey-bar-small](https://cloud.githubusercontent.com/assets/9538528/7048586/87b9e5e0-ddd9-11e4-9a23-5423b69c5746.png)
![grey-bar-large](https://cloud.githubusercontent.com/assets/9538528/7048588/8999725e-ddd9-11e4-8dad-f79bb3dd5a5b.png)

**Comment by britanyponvelle** [comment]
I think the teal breaks up the black text nicely without making itself the focal point.

**Comment by joshkimmell** [comment]
agreed.

**Comment by bobbinrobyn** [comment]
I'm a fan of the teal bar!

**Comment by britanyponvelle** [comment]
:+1:

**Comment by poofichu** [comment]
:+1:

**Comment by britanyponvelle** [comment]
I took another stab at the `aside` and `caption`. The caption needed a little more love (especially for situations where there isn't much text and in it's own column). We need to make sure `aside` , `caption` , and `block-quote` are easily distinguishable, but have similar styles so I've put them next to each other here:

![screen shot 2015-04-09 at 10 39 48 am](https://cloud.githubusercontent.com/assets/9538528/7070613/bc9f1aec-dea5-11e4-96e1-c28d2805a40e.png)

**Comment by joshkimmell** [comment]
@britanyponvelle Which is the `caption` and which is the `aside`?

**Comment by ryanbrownhill** [comment]
I like this direction! Just to make sure I am understanding these right: The first one is `aside`, second one `block-quote`, & third `caption`

Maybe we should make all the strokes the same weight?

**Comment by britanyponvelle** [comment]
1. aside
2. block quote
3. aside

**Comment by britanyponvelle** [comment]
1. aside
2. block quote
3. caption

**Comment by Snugug** [comment]
So for some definitions, to ensure we're all talking about the same things:

* **aside** - content tangentially related to the content around it
* **blockquote** - direct quoted text from an external source
* **figcaption** - Caption or legend for a parent `figure` element
* **footer** - Metadata about the enclosing section, like who wrote it, links to related docs, copyright data, etc…

**Comment by britanyponvelle** [comment]
@Snugug yes on my end

**Comment by ryanbrownhill** [comment]
:+1: 
@Snugug shall we close this because this issue was divided into individual issues based on pages?

**Comment by britanyponvelle** [comment]
:+1: 
There is nothing in this issue that isn't covered in their individual issue pages, so I think we can close.

**Comment by britanyponvelle** [comment]
(see issue #s in the checklist at the top of the page)
