### ISSUE TITLE
Design for Navigation of Library

### ISSUE THREAD

**Issue by una** [IBM-Watson/design-library#74]

**Comment by britanyponvelle** [comment]
[  ] Work with Robyn and Kathryn on IA to determine appropriate navigation style
[  ] Explore color options for navigation
[  ] Check accessibility standards

**Comment by britanyponvelle** [comment]
@Snugug can you label this "visual"?

**Comment by britanyponvelle** [comment]
@kathrynmcelroy @joshkimmell  #93 is due at the same time (end of Beta 2). Can we get together and determine how we will work along side each other, since this issue and #71 should be using the IA you are working on.

**Comment by britanyponvelle** [comment]
@kathrynmcelroy @poofichu 
[MailChimp](http://ux.mailchimp.com/patterns) has a nice navigation for smaller screens. I don't think the hamburger menu at the top makes sense, but the box/ color indicating  where you are in the site is helpful!
![mailchimp-small](https://cloud.githubusercontent.com/assets/9538528/6753213/6b5a1e5c-cee2-11e4-9ec1-ca1fee29227f.png)
![mailchimp-smalll-drop](https://cloud.githubusercontent.com/assets/9538528/6753307/0292d35e-cee3-11e4-989e-d568c9870780.png)

**Comment by britanyponvelle** [comment]
I also like the way [Google Material](http://www.google.com/design/spec/what-is-material/material-properties.html#) does a good job of solving the multiple navigation problem. They have one on the side for high level navigation, and then in-line navigation links for 2nd tier sections

![google-material](https://cloud.githubusercontent.com/assets/9538528/6753870/2eb27300-cee7-11e4-9e15-b056acb3726f.png)

![google-material-drop](https://cloud.githubusercontent.com/assets/9538528/6753882/3707764a-cee7-11e4-8ba3-e0e8b9b5bf47.png)

**Comment by britanyponvelle** [comment]
http://www.wearehive.co.uk/

I think the way they handle primary and secondary navigation is successful for small screen sizes. The three primary sections are always top right, and then if you click in to work, each secondary is listed at the top. It pushes the content down a bit, but you know what is available as soon as you click into the section. It also translates to desktop well (although I think the text is too big on that side. Mobile looks better) Thoughts on this style? 
@Snugug @kathrynmcelroy

**Comment by Snugug** [comment]
@britanyponvelle I agree, I like the way they've done that. My only concern with their design is the animation of the height of the nav, which like I said is hard to do (they're actually changing the height `1px` at a time until they reach the height they want). We may want to consider sliding instead of animating height, and if we're going to animate, it should follow #128

**Comment by britanyponvelle** [comment]
Quick mock up : @kathrynmcelroy 

![screen shot 2015-03-25 at 3 06 51 pm](https://cloud.githubusercontent.com/assets/9538528/6834233/ae9552d2-d300-11e4-940a-058e2e469619.png)

**Comment by britanyponvelle** [comment]
Quick mock up : @kathrynmcelroy 

![screen shot 2015-03-25 at 3 06 51 pm](https://cloud.githubusercontent.com/assets/9538528/6834233/ae9552d2-d300-11e4-940a-058e2e469619.png)

![screen shot 2015-03-25 at 3 11 05 pm](https://cloud.githubusercontent.com/assets/9538528/6834311/3403518a-d301-11e4-8267-b82755a1b038.png)

**Comment by britanyponvelle** [comment]
Quick mock up : @kathrynmcelroy 

![screen shot 2015-03-25 at 3 22 41 pm](https://cloud.githubusercontent.com/assets/9538528/6834555/e0746b24-d302-11e4-83a9-8dc1630032dd.png)

![screen shot 2015-03-25 at 3 22 03 pm](https://cloud.githubusercontent.com/assets/9538528/6834559/e7349484-d302-11e4-874d-c29780958a08.png)

**Comment by kathrynmcelroy** [comment]
Ready for testing!!! http://pages.design.ibm.com/kemcelroy/menu-test/master/

**Comment by Snugug** [comment]
I like the orange, but then again I always like orange.

**Comment by Snugug** [comment]
@kathrynmcelroy I'd make the slide happen faster, `.8s` for an animation is an eternity; I'd suggest something close to `.3s`. @ryanbrownhill thoughts?

**Comment by kathrynmcelroy** [comment]
Great feedback. This menu is designed for testing the Information Architecture of the menu system that I'm working on with @britanyponvelle. I'll be testing this afternoon and tomorrow morning, and this will lead to a finalized IA and navigation design!

**Comment by kathrynmcelroy** [comment]
Updated with some "content" to jump to: http://pages.design.ibm.com/kemcelroy/menu-test/master/master/

**Comment by kathrynmcelroy** [comment]
Updated prototype for testing IA #93 and Navigation: http://pages.design.ibm.com/kemcelroy/menu-test/master/

- added "content" to jump to
- changed animation speed

**Comment by ryanbrownhill** [comment]
@Snugug @kathrynmcelroy yep .3s is the default recommended speed. (we could go a little faster .1 or .2 because its not traveling a very far distance to expand) Overall, it looks great! Can't wait to implement our easing curve in there! :+1:

**Comment by britanyponvelle** [comment]
Mock up for browser smaller than 1000px:

V1:
![nav-blue-small](https://cloud.githubusercontent.com/assets/9538528/6869907/a43b537e-d466-11e4-9bba-ddcd86b6d2d5.png)

V2:
![nav-dark-small](https://cloud.githubusercontent.com/assets/9538528/6869908/a7c258e4-d466-11e4-9df7-af7ce4797f34.png)

Mock up for browser bigger than 1000px:

V1:
![nav-blue-large-expanded](https://cloud.githubusercontent.com/assets/9538528/6869943/f49569cc-d466-11e4-8bd8-9942a9c82abc.png)
![nav-blue-large](https://cloud.githubusercontent.com/assets/9538528/6869952/01364520-d467-11e4-9944-f8bf5458b364.png)

V2:
![nav-dark-large](https://cloud.githubusercontent.com/assets/9538528/6869986/26814352-d467-11e4-8d6f-f8cc9ec755d3.png)
![nav-dark-large-expanded](https://cloud.githubusercontent.com/assets/9538528/6869987/2a60a134-d467-11e4-9961-255aa75f779e.png)

@poofichu @joshkimmell Thoughts on colors?

**Comment by Snugug** [comment]
One thing we should keep in mind is that we don't want navigation/content disparity between different screen sizes. We can rearrange how things get displayed, but we should try not to hide/show different navigation/content at different sizes; users want all of it and want it to be consistent.

**Comment by britanyponvelle** [comment]
Browser smaller than 1000px:

Teal:
![nav-small-teal-guidelines](https://cloud.githubusercontent.com/assets/9538528/6870669/68ed08b2-d46b-11e4-8ea0-7859a2ba61b8.png)
![nav-small-teal-principles](https://cloud.githubusercontent.com/assets/9538528/6870670/68efda24-d46b-11e4-921b-f6c2541abc8b.png)

Blue:
![nav-small-blue-guidelines](https://cloud.githubusercontent.com/assets/9538528/6870677/71d31d2c-d46b-11e4-9e81-0f42c88f1ddb.png)
![nav-small-blue-principles](https://cloud.githubusercontent.com/assets/9538528/6870678/71d8185e-d46b-11e4-93cd-c695da677b8e.png)

Thoughts? @poofichu @joshkimmell

**Comment by Snugug** [comment]
I like the teal more than I like the blue

**Comment by joshkimmell** [comment]
What about orange/blue/teal?

**Comment by ryanbrownhill** [comment]
I agreed I like the teal better. Looking at it on my phone I think the leading needs to be increased - the hit states seem a little small.

**Comment by britanyponvelle** [comment]
@ryanbrownhill thanks! I increased the leading to 1.6em.
@joshkimmell I use going to use the orange for headings

Blue/ Teal:
![nav-small-blue-guidelines-v2](https://cloud.githubusercontent.com/assets/9538528/6871360/fbfd00b8-d46f-11e4-84a2-be362aea2c02.png)
![nav-small-blue-principles-v2](https://cloud.githubusercontent.com/assets/9538528/6871361/fc00899a-d46f-11e4-851b-37fd02f799e7.png)

Teal:
![nav-small-teal-guidelines-v2](https://cloud.githubusercontent.com/assets/9538528/6871365/023bdd82-d470-11e4-8ec1-e4cd6adad5f9.png)
![nav-small-teal-principles-v2](https://cloud.githubusercontent.com/assets/9538528/6871366/0253f584-d470-11e4-89be-7e4e005bc2d9.png)

**Comment by britanyponvelle** [comment]
Browser larger than 1000px:

Blue/ Teal:
![nav-large-blue-guidelines](https://cloud.githubusercontent.com/assets/9538528/6871742/ad644a94-d472-11e4-91f0-7b8083740003.png)
![nav-large-blue-principles](https://cloud.githubusercontent.com/assets/9538528/6871741/ad62bfa8-d472-11e4-9977-36bad3c8915b.png)

Teal:
![nav-large-teal-guidelines](https://cloud.githubusercontent.com/assets/9538528/6871747/b57c04a6-d472-11e4-819d-13fd1bb27924.png)
![nav-large-teal-principles](https://cloud.githubusercontent.com/assets/9538528/6871748/b57d5770-d472-11e4-9bba-ca1bdb3aa671.png)

**Comment by Snugug** [comment]
@britanyponvelle So is the idea that on small screens the menu will fold out from underneath when tapped on and slide out from the right on larger screens? Does tapping on the title on large screens open the introduction page for that section, and not on small screens (because it can't if it's a toggle as well)?

**Comment by britanyponvelle** [comment]
The idea is that when you land on the site, the principles page would already have the secondary nav open, and would stay open (both mobile and desktop). The same goes for Guidelines and UI Patterns. @kathrynmcelroy tested this, and said she will share it with you at your meeting later

**Comment by britanyponvelle** [comment]
The Guidelines/ UI page would have the primary, secondary, and tertiary links at all times

**Comment by britanyponvelle** [comment]
Mockup of H1, H2 H3, links, and resources panel for browsers larger than 1000px

![main-large-color-19](https://cloud.githubusercontent.com/assets/9538528/6874023/31c501ca-d482-11e4-99b6-9c9cff44980d.png)

**Comment by britanyponvelle** [comment]
@joshkimmell @Snugug @poofichu @ryanbrownhill @kathrynmcelroy 
here are some light and dark versions. Thoughts?

![main-large-v2-19](https://cloud.githubusercontent.com/assets/9538528/6875417/58e85d10-d48c-11e4-8083-165217c70e4c.png)
![main-large-v2-20](https://cloud.githubusercontent.com/assets/9538528/6875418/58ea1d1c-d48c-11e4-89c4-b0e846e38569.png)

**Comment by Snugug** [comment]
I like 19 better than 20

**Comment by kathrynmcelroy** [comment]
I like 20! the lighter side bar really makes the page easier to read and feels more open.

**Comment by bobbinrobyn** [comment]
I think 20 works better, because it takes some of the emphasis off the side nav. Having that navigation is important, but it's definitely not the MOST important content.

**Comment by Snugug** [comment]
What about 20 with teal in the sidebar instead of orange?

**Comment by bobbinrobyn** [comment]
Yep, I think that would be great. Josh asked Britany to try adding more color, but I think it would be more consistent to have all the navigation color accents be the same color.

**Comment by kathrynmcelroy** [comment]
I do like the teal. Example of side bars that I just showed Britany: https://stripe.com/docs/api#authentication

**Comment by britanyponvelle** [comment]
I think the teal in both the main nav and side nav is working! If we are going to choose two colors for those, they would need to be really different since they would be right next to one another on mobile. So I propose either teal and teal, or orange and blue.

![main-large-teal-20](https://cloud.githubusercontent.com/assets/9538528/6875638/7429e59c-d48e-11e4-99c5-a132c7246e24.png)

**Comment by Snugug** [comment]
Unfortunately, the teal on grey [isn't accessible at the sizes we have them](http://leaverou.github.io/contrast-ratio/#rgb%280%2C133%2C133-on-rgb%28236%2C236%2C236%29) so I'd recommend only using it as an accent color.

**Comment by Snugug** [comment]
Actually, the teal on that black up top [isn't accessible at all](http://leaverou.github.io/contrast-ratio/#rgb%280%2C133%2C133%29-on-rgb%2850%2C%2050%2C%2050%29), so we need new colors :cry:

**Comment by Snugug** [comment]
(I'm assuming we're using Teal 60 here)

**Comment by britanyponvelle** [comment]
@joshkimmell and @kathrynmcelroy had the idea of a side bar that adjusts with the content to give the main content more breathing room

Colors:
Teal 30 on Grey 80
Teal 60 on Grey 10, Neutral 4, and Neutral 2

![main-large-small-side-bar-22](https://cloud.githubusercontent.com/assets/9538528/6876167/c8cc34f2-d492-11e4-8356-27a38b421bd7.png)

**Comment by britanyponvelle** [comment]
Same as above ^ for browsers smaller than 1000px

![nav-light-22](https://cloud.githubusercontent.com/assets/9538528/6876489/02b25aae-d496-11e4-866f-9e432876d193.png)

**Comment by britanyponvelle** [comment]
Same as above ^ for browsers smaller than 1000px

![nav-light-21](https://cloud.githubusercontent.com/assets/9538528/6876510/2bef3ba8-d496-11e4-8701-25ab1d02521b.png)

**Comment by poofichu** [comment]
I LOVE THIS.

My only comment would be to explore the body link color.  Blind/old people like me can't see and determine it's a link at first glance.  Maybe play with underline?

**Comment by poofichu** [comment]
AND ALSO

Play with Second and Third tier font styles.  They look pretty similar right now.  Uppercase vs lower case maybe?  Play with font weights?

**Comment by Snugug** [comment]
As a general best practice, all links should have underlines of some sort.

**Comment by britanyponvelle** [comment]
Agreed on differentiating the links from the body text. 
Another thought: should the links that navigate the user to a different page be treated differently than links that download assets? (for example: ASE download link)

Mocked up:
- underlined links
- different color for downloads
- adjusted weights for H tags

![main-large-link-v3](https://cloud.githubusercontent.com/assets/9538528/6876959/8c1884a4-d49a-11e4-8725-5ca9f1e9e299.png)

**Comment by bobbinrobyn** [comment]
Yes yes yes. @britanyponvelle It's looking awesome. Hierarchy is great. The only thing with the download link is that I would include some kind of icon that indicates a download. If it's that chain link icon, maybe put it closer to the actual download?

**Comment by britanyponvelle** [comment]
Because there is a download icon, isn't there? :) heh heh. I will fix that....

**Comment by britanyponvelle** [comment]
Updated:
- got rid of "style" section
- added download icon

@Snugug @joshkimmell @kathrynmcelroy 

![main-large-v4-23](https://cloud.githubusercontent.com/assets/9538528/6877568/23d059ca-d4a0-11e4-9058-8adb722387da.png)

**Comment by britanyponvelle** [comment]
In an effort to try to wrap up decisions on nav styling, I'm looking for feedback on these options:
- Indentation on side navigation bar
- side bar that sticks to the left side of browser, or floats left of main content.

Browser larger than 1000px: **v1**
Indentation on side bar, floats left to main content
![wdl-large-nav-style-02](https://cloud.githubusercontent.com/assets/9538528/6898009/f3fcba94-d6bc-11e4-970f-78bfd3bbeda8.png)

Browser larger than 1000px: **v 2**
No indentation on side bar. Can float left to main content, or stick to the left side of browser.
![wdl-large-nav-style-03](https://cloud.githubusercontent.com/assets/9538528/6898062/4e097630-d6bd-11e4-9d5b-95602f290e81.png)

Browser larger than 1000px: **v3**
No indentation on side bar, and sticks to the left side of browser.
![wdl-large-nav-style-06](https://cloud.githubusercontent.com/assets/9538528/6898080/732de3a6-d6bd-11e4-9e93-cb55a3989513.png)

Browser smaller than 1000px: **v1**
Nav with indentation
![wdl-small-nav-style-01](https://cloud.githubusercontent.com/assets/9538528/6898135/dbf61f52-d6bd-11e4-9fe0-ac03e552c36c.png)

Browser smaller than 1000px: **v1**
Nav without indentation
![wdl-small-nav-style-05](https://cloud.githubusercontent.com/assets/9538528/6898145/e5880fbc-d6bd-11e4-8a27-472fe1c8ddcc.png)

**Comment by bobbinrobyn** [comment]
I vote for v2 (no indentation, floats to the left of main content) but maybe with a tad bit more space between the end of one section and the start of the next one (e.g. between "Grids" and "Interaction"). I think the versions without indentation help those top-level sections look more like categories and less like their own pages. It's looking good!

**Comment by kathrynmcelroy** [comment]
Navigation is looking good. I like the look of the non-indented (since most of the high-level links style, interaction, branding don't have their own pages). But copy does have a page, so I think it would be best to do indented so it looks more like you can click the "Copy" link, or add a page under "Copy" instead and go with non-indented.

**Comment by britanyponvelle** [comment]
Could we call the section with copy, "Tone" or "Voice"? So it would be Voice> Copy

**Comment by britanyponvelle** [comment]
@poofichu and I user tested these navigation styles with 8 designers (Watson and Studio):
[Indented & Bold Headings](http://pages.design.ibm.com/tremblay-us/menu-test/master/bold-titles-indent/)
[Indented & Non-Bolded Headings](http://pages.design.ibm.com/tremblay-us/menu-test/master/)
[In-line & Bold Headings](http://pages.design.ibm.com/tremblay-us/menu-test/master/bold-titles/)

From our research, the conclusion is that In-line and Bolded Headings are accessible, easier to scan, and headings are recognizable as headings (vs links).

We will continue in this direction!
![screen shot 2015-03-30 at 11 54 16 am](https://cloud.githubusercontent.com/assets/9538528/6901533/823076a0-d6d3-11e4-85d9-30ae66df421b.png)

**Comment by joshkimmell** [comment]
Yay!

**Comment by britanyponvelle** [comment]
Here is the most recent version of nav:
If everyone votes :+1: I think we can close this!

![screen shot 2015-03-30 at 3 18 09 pm](https://cloud.githubusercontent.com/assets/9538528/6905873/991ebce2-d6f0-11e4-8630-3d79e14f512b.png)
![screen shot 2015-03-30 at 3 18 30 pm](https://cloud.githubusercontent.com/assets/9538528/6905874/99211bfe-d6f0-11e4-9def-188b8bb0f543.png)

**Comment by britanyponvelle** [comment]
Here is the most recent version of nav:
If everyone votes :+1: I think we can close this!

![screen shot 2015-03-30 at 3 24 10 pm](https://cloud.githubusercontent.com/assets/9538528/6905926/e765cb8e-d6f0-11e4-84dc-089c249f2635.png)
![screen shot 2015-03-30 at 3 18 09 pm](https://cloud.githubusercontent.com/assets/9538528/6905931/ec9875de-d6f0-11e4-8f9c-b6dd1c229666.png)

**Comment by ryanbrownhill** [comment]
:+1: 
Also don't close until there is a pull request :stuck_out_tongue:

**Comment by britanyponvelle** [comment]
I have been thinking about the colored bar on the left nav bar, and I think it might be a good idea to leave it off. It doesn't really add any extra value (especially on small screens since it's so far right) and kind of feels like decoration right now. Thoughts on something like this?

![nav-large](https://cloud.githubusercontent.com/assets/9538528/7005853/c4560ce8-dc41-11e4-8801-e6adbac7741c.png)
![nav-small](https://cloud.githubusercontent.com/assets/9538528/7005855/c65f2952-dc41-11e4-9637-ad9c10eb2d17.png)

**Comment by britanyponvelle** [comment]
with hover states: 
http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/typography.html

**Comment by una** [comment]
I love the navigation on the header bar. As far as the sidebar goes, I am unsure about the hover state being bolded because it causes a jump in the width of the text (extra padding for each character due to the increased weight). Perhaps try using an icon on the left of the item to indicate hover? 

Also, when you hover over the already-selected state, the font weight becomes lighter than its current state. On that note, how many font weights are we including on this (seems like 3 just for hover states right now)?

**Comment by kathrynmcelroy** [comment]
I agree that the color bar isn't helping much on the right side, but it could live on the left as a quicker visual indicator.

**Comment by britanyponvelle** [comment]
@una I agree on the multiple bolded weights. There should only be one, which could have gotten mixed up in the prototype. Right now we have 400 as body text, and either 600 or 700 for bold. Thanks for the heads up :)

**Comment by britanyponvelle** [comment]
@kathrynmcelroy I like that suggestion! I will play around with that today.

**Comment by poofichu** [comment]
I'm with @kathrynmcelroy on that one.  The side navigation needs just a little something more as an effective active page indicator.

**Comment by bobbinrobyn** [comment]
Passing along some user feedback... the bottom nav looks very similar to Material Design. When this finally does go public, she worries that people will think it looks like we stole it from them.

I realize there are arguments for and against. It's not like Google has dibs on that navigation pattern, and it's something we're borrowing from IBM Design. But I thought it was worth it to at least mention!

**Comment by britanyponvelle** [comment]
That is good feedback... I just looked and it is very similar. That being said, the IBM Design is also similar. I will chew on this...

**Comment by Snugug** [comment]
![Chewing](http://i.imgur.com/rCHESpZ.gif)

**Comment by bobbinrobyn** [comment]
Hehehe. That's so good @Snugug

**Comment by joshkimmell** [comment]
@poofichu The menu is "jumpy" in smaller format.

**Comment by poofichu** [comment]
@joshkimmell You're going to have to be more specific than that.  I'm heading upstairs.

**Comment by joshkimmell** [comment]
"jumpy".... you know... "jumpy"

**Comment by Snugug** [comment]
Is this complete?

**Comment by britanyponvelle** [comment]
I say :+1:

**Comment by ryanbrownhill** [comment]
:+1: Yep
