### ISSUE TITLE
Form Input Types

### ISSUE THREAD

**Issue by una** [IBM-Watson/design-library#77]
Check all of the form input types for correct docs and styling from the Jira list

**Comment by Snugug** [comment]
Can we get some checkboxes so we have an idea of how far along we are?

**Comment by Snugug** [comment]
![screen shot 2015-03-10 at 3 36 26 pm](https://cloud.githubusercontent.com/assets/377188/6583547/482b112e-c73b-11e4-9f96-766886cab6f4.png)

**Comment by una** [comment]
thanks for fetching that!

image: No longer doing
color, date, datetime-local: done
file: depends on button #109 
search: needs icon situation sorted #111
