### ISSUE TITLE
Determine Name for Design Guide

### ISSUE THREAD

**Issue by Snugug** [IBM-Watson/design-library#86]
We need a name

**Comment by joshkimmell** [comment]
Hows about "Blue" y'all?

**Comment by bradbecker** [comment]
Since it's going to be cognitive components we might end up calling them Cogs

-b

**Comment by Snugug** [comment]
Blue's too generic (in fact I think anything with Blue will be too generic for Watson specifically, doubly so as we're trying to get away from Blue I thought?).

They aren't all going to be cognitive components, most of them in fact won't be. Most of them will be smaller bits that are needed to make up the UI, with a few more complex ones/combinations being specifically cognitive.

**Comment by joshkimmell** [comment]
What about spinning this as literally the face of Watson? Let's brainstorm around that. I think "Cogs" sounds like unimportant pieces of a machine. Not humane or natural at all.

**Comment by joshkimmell** [comment]
countenance, aspect, bearing, facet

**Comment by joshkimmell** [comment]
I'll work with Hayley to come up with a name.

**Comment by kathrynmcelroy** [comment]
She mentioned a naming convention she'd like to try with us. "[Product] Design Guide"

But feel free to follow up with her to finalize.

**Comment by bradbecker** [comment]
I assume this is just for the design guide side not the pattern library

-b

**Comment by joshkimmell** [comment]
yeah... well... we should come up with a good name for the open source patterns hosted on github separately. It looks like IBM Design will dictate what the guide is named.

**Comment by joshkimmell** [comment]
Closing this as Determine name for the design guide.
