### ISSUE TITLE
Color Palette Recommendations

### ISSUE THREAD

**Issue by britanyponvelle** [IBM-Watson/design-library#95]
- [x] Choose a color system based on refined color palettes
- [x] Write recommendations for choosing colors
- [x] Get feedback from Watson team
- [ ] Get feedback from Studio team
- [ ] Add to branch
- [ ] Submit pull request

**Comment by Snugug** [comment]
Blocked on #94

**Comment by poofichu** [comment]
![image](https://cloud.githubusercontent.com/assets/6757613/6560416/de6d23f0-c657-11e4-888d-24e5d3de9e5f.png)
Working on developing a color hierarchy system for the visual guidelines.  How do we like this visual approach?  The lightest grey being the star of the show (backgrounds) followed by most used colors afterwards.

**Comment by ryanbrownhill** [comment]
@poofichu I like it --- I think it shows proportions of colors nicely.

**Comment by britanyponvelle** [comment]
This is great! I like this approach because it is a good representation of balancing primary, secondary, and accent colors with neutral colors to create a focal point. I was wondering why you chose to make a triangle? I took a stab at applying the idea to a golden rectangle which is pretty straightforward. Showing the primary, secondary, and accent color(s) in relation to one another can be an easy way to depict color should have a heavier visual weight. 

![color-hierarchy-proposal](https://cloud.githubusercontent.com/assets/9538528/6619682/e72e93d6-c899-11e4-92bf-68a51e87ef21.png)

**Comment by ryanbrownhill** [comment]
@poofichu I love representing hierarchy of color this way. We* think the triangles are unique but the rectangles more understandable. We also believe there should be color hierarchy like this for both light and dark UI.

We* = @britanyponvelle @una @joshkimmell

**Comment by britanyponvelle** [comment]
First draft:

## Color
Color is a crucial component of our visual vernacular, helping to unify the look and feel of all communications. The IBM core color system comprises a wide spectrum of colors; IBM Watson relies on a defined subset of those colors to establish its unique presence while nodding to the broader IBM agenda.

**Visual example:**  
1. list of Watson colors, HEX codes

**Resources:** .ASE File 

### Choosing Your Color Palette
The IBM Watson color system consists of a set of primary colors and secondary colors, with additional color values as support. The colors chosen for IBM Watson are flexible distinguish Watson as a brand. Carefully choose colors that reinforce the personality and set the tone of your product. The balance of color usage is important to in order to align and unify communications with the IBM Watson visual expression. Use ample white space and neutrals to create balance and direct users' attention. Use tints and shades of your primary or secondary colors to unify your design. These values can add variety to your palette without  additional colors. Use color psychology to evoke desired feelings or moods from users. For example, while warm colors can impress a sense of energy, cool colors can feel soothing. 

**Visual example:**  
1. color hierarchy chart  

![Color Hierarchy Chart](https://cloud.githubusercontent.com/assets/9538528/6619682/e72e93d6-c899-11e4-92bf-68a51e87ef21.png)
Choose a primary color, a secondary color, and an accent color. Balance with ample white space for emphasis to help your users make clear decisions.

### Accessibility
When choosing colors for desktop experiences, it is important to adhere to the IBM Design Language recommendations for accessibility. Never rely on color as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element.  

**Resources:** Link to IBM Design accessibility recommendations for color values

**Comment by bobbinrobyn** [comment]
Update: I'm user testing today and tomorrow, getting feedback from the larger Watson group tomorrow afternoon, then determining colors by Monday at the latest.

**Comment by bobbinrobyn** [comment]
Can we change this to in progress?

**Comment by britanyponvelle** [comment]
Draft 2:

## Color
Color is a crucial component of our visual vernacular, helping to unify the look and feel of all communications. The IBM Design core color system comprises a wide spectrum of colors; IBM Watson relies on a defined subset of those colors to establish its unique presence while respecting the broader IBM Design guidelines.

**Visual example:**
1. list of Watson colors, HEX codes

**Resources:** .ASE File

### Choosing Your Color Palette
The IBM Watson color system consists of a set of primary colors and secondary colors, with additional color values as support. The colors chosen for IBM Watson are flexible distinguish Watson as a brand across all user experiences. Carefully choose colors that reinforce Watson's personality (link to personality) and set the tone of your product.

Color is a powerful communication tool to determine hierarchy on a page. Use ample white space and neutrals to create balance and to direct users' attention. Use tints and shades of your primary or secondary colors to unify your design. These values can add variety to your palette without additional colors. It is essential to understand color psychology to evoke desired feelings or moods from users. For example, while warm colors can impress a sense of energy, and cool colors can feel soothing.

**Visual example:**
1. color hierarchy chart

![Color Hierarchy Chart](https://cloud.githubusercontent.com/assets/9538528/6619682/e72e93d6-c899-11e4-92bf-68a51e87ef21.png)
Choose a primary color, a secondary color, and an accent color. Balance with ample white space for emphasis to help your users make clear decisions.

**Comment by britanyponvelle** [comment]
Update on colors from our meeting today: 
@bobbinrobyn 

![wdl-color-examples-01](https://cloud.githubusercontent.com/assets/9538528/6761739/29400e5e-cf24-11e4-9e93-bf690f83fc20.png)
![wdl-color-examples-02](https://cloud.githubusercontent.com/assets/9538528/6761740/2940d028-cf24-11e4-9805-ab11bdcf53cc.png)

**Comment by Snugug** [comment]
I swear I've got blue 60 written down somewhere from the color workshop… Maybe it was blue 50…

**Comment by joshkimmell** [comment]
For the ratio, we need a dark palette ratio, too.

**Comment by britanyponvelle** [comment]
@joshkimmell I'll add it to the vis To Do list. 


Also, question for color recommendations: @bobbinrobyn @poofichu @joshkimmell 

If we are making Blue 60 the primary color of Watson, does this also mean the it needs to be the primary color in everyone's palettes? I was under the impression it didn't. In this case, wouldn't the secondary color be more prominent in a product? (for instance, Chef Watson)

I would think the hierarchy would be something like this:

![screen shot 2015-03-23 at 9 19 34 am](https://cloud.githubusercontent.com/assets/9538528/6781726/c323ab8c-d13d-11e4-8eda-462068a28def.png)

**Comment by britanyponvelle** [comment]
Also, I know that we can't use the yellow from cartographer in our palette right now, but perhaps we can use the approve yellow as a substitute for the time being?

![screen shot 2015-03-23 at 9 36 46 am](https://cloud.githubusercontent.com/assets/9538528/6782168/638f0f88-d140-11e4-97e8-b6777df8820e.png)

**Comment by bobbinrobyn** [comment]
Choosing Your Color Palette

The IBM Watson color system consists of a set of primary colors and secondary colors, with additional **supporting** color values. The colors chosen for IBM Watson are flexible **and** distinguish Watson as a brand across all user experiences. Carefully choose colors that reinforce Watson's personality (link to personality) and set the tone of your product.

Color is a powerful communication tool to determine hierarchy on a page. Use ample white space and neutrals to create balance and to direct users' attention. Use tints and shades of your primary or secondary colors to unify your design. These values can add variety to your palette without additional colors. It is essential to understand color psychology to evoke desired feelings or moods from users. For example, while warm colors can impress a sense of energy, and cool colors can feel soothing.

**Comment by britanyponvelle** [comment]
How about something like this for choosing palettes?

![screen shot 2015-03-23 at 10 34 42 am](https://cloud.githubusercontent.com/assets/9538528/6783579/76728302-d148-11e4-8f85-4c37fa98e7c6.png)

**Comment by britanyponvelle** [comment]
Draft 3: 

## Color
Color is a crucial component of our visual vernacular, helping to unify the look and feel of all communications. The IBM Design core color system comprises a wide spectrum of colors; IBM Watson relies on a defined subset of those colors to establish its unique presence while respecting the broader IBM Design guidelines.

**Resources:** .ASE File and link to IBM Design colors

### Choosing Your Color Palette
The IBM Watson color system consists of a set of primary colors and secondary colors, with additional supporting color values. The colors chosen for IBM Watson are flexible and distinguish Watson as a brand across all user experiences. Carefully choose colors that reinforce Watson's personality (link to personality) and set the tone of your product.

**Visual example:**

![wdl-color-examples-05](https://cloud.githubusercontent.com/assets/9538528/6784694/44d0377a-d14f-11e4-9008-c6a34e06e565.png)  
Choose a primary color, a secondary color, and an accent color. Use additional color values and neutrals from the IBM Design color palette as needed.

Color is a powerful communication tool to determine hierarchy on a page. Use ample white space and neutrals to create balance and to direct users' attention. Use tints and shades of your primary or secondary colors to unify your design. These values can add variety to your palette without additional colors. It is essential to understand color psychology to evoke desired feelings or moods from users. For example, while warm colors can impress a sense of energy, and cool colors can feel soothing.

**Visual example:**
1. Color hierarchy: Light Palette

![wdl-color-hierarchy-light-02](https://cloud.githubusercontent.com/assets/9538528/6784726/6f37ee5e-d14f-11e4-83f0-ac124e2b3eda.png)

2. Color hierarchy: Dark Palette
![wdl-color-hierarchy-dark-06](https://cloud.githubusercontent.com/assets/9538528/6784741/80cbae8a-d14f-11e4-9f19-ba88c568fea6.png)

**Comment by britanyponvelle** [comment]
From @bobbinrobyn :  When we display our color palette, we will have our own Sass variables for each color. One of the Watson designers asked that we display each Sass variable along with the hex code and visual rendering of the color. I guess I'm just a little confused – isn't the user going to have to define their _own_ Sass variables when they use our colors? So is it helpful to them to see the way we've named ours?

**Comment by bobbinrobyn** [comment]
Okay, upon further inspection @poofichu found out that IBM Design already has a Sass mix-in for their colors. So we can just use that.

**Comment by joshkimmell** [comment]
I think users can select multiple accent colors, yes?

**Comment by bobbinrobyn** [comment]
@britanyponvelle You're doing so well! This looks great. Just reiterating a couple of the things we just talked about – I think the explicit "Choose 1 primary and one secondary" then "Choose 1 accent" is awesome. To @joshkimmell's comment, I think it would be fine if they choose more than 1 accent. But overall, I like the step-by-step nature of this guide.

**Comment by britanyponvelle** [comment]
@joshkimmell  yes! I left it as one for now, because I feel like we should suggest a max amount. Maybe "Choose two accent colors. (Add additional hues as needed)"

**Comment by britanyponvelle** [comment]
![wdl-color-examples-2-05](https://cloud.githubusercontent.com/assets/9538528/6785608/9bc98f18-d154-11e4-9c75-d206e1765e84.png)

**Comment by bobbinrobyn** [comment]
And like we talked about, maybe the percentages aren't the best way to make it clear to designers. Instead, maybe annotating the visual hierarchy graphic with a caption like _(Primary: Blue 60, Secondary: Orange 50, Accent: Teal 40)_ could be helpful.

**Comment by edouuard** [comment]
hi just leaving a note — y'all are so inspiring to me :heart_eyes: 
![selfie-0](http://i.imgur.com/AkPsoop.png)

**Comment by britanyponvelle** [comment]
@edouuard hello sir, thanks for the love !

**Comment by britanyponvelle** [comment]
@bobbinrobyn agreed. The percentages didn't really add value to the chart. I can add that as a caption instead

**Comment by bobbinrobyn** [comment]
I did a little synthesis / write-up about the final color palette selection: https://releaseblueprints.ibm.com/display/WDA/Color

**Comment by britanyponvelle** [comment]
Added recommended greys and neutrals as we want to recommend using neutral backgrounds rather than pure white:
(still have to add this to the written guideline)

![wdl-color-examples-v2-05](https://cloud.githubusercontent.com/assets/9538528/6787925/f7eaa1d8-d163-11e4-998f-f4819b8e208c.png)

**Comment by britanyponvelle** [comment]
Just added: 
*When possible, use a neutral value as a background color instead of pure white.*
*When possible, use a grey value as a background color instead of pure black.*

@bobbinrobyn the wiki is updated! If @joshkimmell and @poofichu are cool with these as they are, I'd say send it out :)

**Comment by britanyponvelle** [comment]
@joshkimmell Josh says it's good to go!

**Comment by joshkimmell** [comment]
yup

**Comment by poofichu** [comment]
WOOHOO!!

**Comment by bobbinrobyn** [comment]
Here's the coded color palette (just for now, I know it will need to be redone for the real website).  http://pages.design.ibm.com/rlhammon/watson-color-palettes/master/palette_final.html

**Comment by britanyponvelle** [comment]
Updated links, and re-named "Color Hierarchy" to "Applying a Color Palette"


## Color
Color is a crucial component of our visual vernacular, helping to unify the look and feel of all communications. The IBM Design core color system comprises a wide spectrum of colors; IBM Watson relies on a defined subset of those colors to establish its unique presence while respecting the broader IBM Design guidelines.

**Resources:** .ASE File and link to IBM Design colors (http://www.ibm.com/design/language/framework/visual/color.shtml)

### Choosing A Color Palette
The colors chosen for IBM Watson are flexible and distinguish Watson as a brand across all user experiences. Carefully choose colors that reinforce Watson's personality (link to personality) and set the tone of your product. Choose a primary color, a secondary color, and an accent color. Use additional color values and neutrals from the IBM Design color palette as needed. Use tints and shades of your primary or secondary colors to unify your design. These values can add variety to your palette without additional colors.

**Visual example:** (Sass attributes are placeholders)

![wdl-color-examples-v2-05](https://cloud.githubusercontent.com/assets/9538528/6787925/f7eaa1d8-d163-11e4-998f-f4819b8e208c.png)  

### Applying A Color Palette
Color is a powerful communication tool to determine hierarchy on a page. Use ample white space and neutrals to create balance and to direct users' attention. 

**Visual example:**  
1. Color Application: Light Palette

![wdl-color-hierarchy-light-02](https://cloud.githubusercontent.com/assets/9538528/6784726/6f37ee5e-d14f-11e4-83f0-ac124e2b3eda.png)  
Primary: Blue 60, Secondary: Orange 50, Accent: Teal 40  
*When possible, use a neutral value as a background color instead of pure white.*


2. Color Application: Dark Palette
![wdl-color-hierarchy-dark-06](https://cloud.githubusercontent.com/assets/9538528/6784741/80cbae8a-d14f-11e4-9f19-ba88c568fea6.png)  
Primary: Blue 30, Secondary: Orange 30, Accent: Teal 30  
*When possible, use a grey value as a background color instead of pure black.*

**Comment by britanyponvelle** [comment]
Update:
-Comments on why Watson recommends not using pure black or white

### Applying A Color Palette
Color is a powerful communication tool to determine hierarchy on a page. Use ample white space and neutrals to create balance and to direct users' attention. 

**Visual example:**  
1. Color Application: Light Palette

![wdl-color-hierarchy-light-02](https://cloud.githubusercontent.com/assets/9538528/6784726/6f37ee5e-d14f-11e4-83f0-ac124e2b3eda.png)  
Primary: Blue 60, Secondary: Orange 50, Accent: Teal 40  
*Consider users who are sensitive to brightness and high contrast colors by using a neutral value as a background color instead of pure white.*


2. Color Application: Dark Palette
![wdl-color-hierarchy-dark-06](https://cloud.githubusercontent.com/assets/9538528/6784741/80cbae8a-d14f-11e4-9f19-ba88c568fea6.png)  
Primary: Blue 30, Secondary: Orange 30, Accent: Teal 30  
*Consider users who are sensitive to brightness and high contrast colors by using a grey value as a background color instead of pure black.*

**Comment by britanyponvelle** [comment]
Update: 
-reasoning as to why IBM Watson is recommending these colors

## Colors for Watson
The colors chosen for IBM Watson are flexible and distinguish Watson as a brand across all user experiences. The colors chosen for IBM Watson were developed to support the Watson brand attributes,  reinforce Watson's personality (link to personality), and set the tone of your product. 

**Visual Examples:**  
List three primary colors, and word associations

**Comment by britanyponvelle** [comment]
Update: 
-reasoning as to why IBM Watson is recommending these colors

## Colors for Watson
The colors chosen for IBM Watson are flexible and distinguish Watson as a brand across all user experiences. The colors chosen for IBM Watson were developed to support the Watson brand attributes,  reinforce Watson's personality (link to personality), and set the tone of your product. 

**Visual Examples:**  
![screen shot 2015-03-25 at 10 51 11 am](https://cloud.githubusercontent.com/assets/9538528/6828691/1151fe6c-d2dd-11e4-8647-90a67fc57f7e.png)

**Comment by britanyponvelle** [comment]
Pull request opened for color guidelines #131

**Comment by Snugug** [comment]
Resolved by #133

**Comment by britanyponvelle** [comment]
![color-personality](https://cloud.githubusercontent.com/assets/9538528/6948026/b0050de0-d870-11e4-881c-dd1a8d50d0c0.png)

**Comment by britanyponvelle** [comment]
![color-swatches](https://cloud.githubusercontent.com/assets/9538528/6948081/04b6a61e-d871-11e4-9548-1e47f09698f7.png)
