### ISSUE TITLE
Color Workshop Blog

### ISSUE THREAD

**Issue by joshkimmell** [IBM-Watson/design-library#96]
Complete Color workshop presentation to share with Watson Design and then with "the world"

**Comment by joshkimmell** [comment]
I'm putting the finishing touches on this today.

**Comment by Snugug** [comment]
Was this completed?

**Comment by Snugug** [comment]
What's the status on this? Should it still be blocked?

**Comment by Snugug** [comment]
@joshkimmell Is this still blocked? Is it still valid?

**Comment by bobbinrobyn** [comment]
I've been working on this for my own blog, which I'm happy to share with the larger Watson Design blog. It's a lot of info and photos, so I'm splitting it over three posts. The first two are done:

https://w3-connections.ibm.com/blogs/robynhammond/entry/What_Color_is_Watson?lang=en_us
https://w3-connections.ibm.com/blogs/robynhammond/entry/What_Color_is_Watson_Part_2?lang=en_us

**Comment by bobbinrobyn** [comment]
Finished the third post about color, and with that, I'm done. https://w3-connections.ibm.com/blogs/robynhammond/entry/What_Color_is_Watson_Part_3?lang=en_us

**Comment by bobbinrobyn** [comment]
This is all done! Per Marnie's suggestion, I posted a synopsis to the IBM Watson blog: https://w3-connections.ibm.com/blogs/76f4974e-15fb-41d1-8fa5-5ad4abc1ae4d/entry/Introducing_the_Watson_Design_Guide_Case_Study_Color?lang=en_us.

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by Snugug** [comment]
Closing this then!

**Comment by joshkimmell** [comment]
Fantastic job!!!
