### ISSUE TITLE
Determine Visual Guidelines

### ISSUE THREAD

**Issue by britanyponvelle** [IBM-Watson/design-library#98]
- [x] Interview Watson visual designers to find their pain points
- [x] Synthesize feedback from interviews
- [x]  Determine which guidelines to include
- [x]  Write visual guidelines
- [x]  Prototype concepts for visual examples
- [x]  Get feedback

**Comment by poofichu** [comment]
Scheduled meetings with the following people for Friday 3/6:
Jillian Quiller, Nicholas Quinterro, Leslie Shapiro, Angela Swindell, Jeri Bowers, Amanda McMicken, Stephanie Brunner

**Comment by britanyponvelle** [comment]
I was thinking we could use a Mural.ly board for ideating guielines, and Release Blueprints for storing notes from interviews/ writing the guidelines as we refine them in Mural.ly. Thoughts?

Release Blueprints: https://releaseblueprints.ibm.com/display/WDA/Explore%3A+Visual+Guidelines
Mural.ly: http://mrl.li/mronaoxL

@joshkimmell @poofichu

**Comment by Snugug** [comment]
Personally I'd like as much of this as possible to be on [our public wiki](https://github.com/IBM-Watson/patterns/wiki)

**Comment by una** [comment]
@britanyponvelle make a new page here https://github.com/IBM-Watson/patterns/wiki when you're ready -- we can iterate on that and have all of your progress be accessible to everyone at all times

**Comment by poofichu** [comment]
@britanyponvelle we'll use the mural.ly initially, but then can move into the wiki.  I like the visual-ness of mural.ly for initial organization.

**Comment by britanyponvelle** [comment]
I've added *first drafts* of visual guidelines, including: Typography, Color, and Iconography. Some of it is recycled from the existing site (typography and iconography) and others are new (Color, Color Choosing System, and examples). Still working with Robyn to choose the actual palette, but this is to get that ball rolling. I am gladly welcoming all feedback on that page as I am not the best writer :)

**Comment by britanyponvelle** [comment]
Visual Design guidelines we've identified so far:

- [ ] Typography
- [ ] Typographic Scale
- [ ] Cross-Platform Fontstack Options
- [ ] Color
- [ ] Choosing Your Color Palette
- [ ] Accessibility
- [ ] Iconography

**Comment by britanyponvelle** [comment]
This issue has been completed and lives here:
https://github.com/IBM-Watson/design-library/wiki/Visual-Guidelines

**Comment by Snugug** [comment]
Until these are merged in, we can't consider this closed. I'm going to re-open until we've merged the PR

**Comment by britanyponvelle** [comment]
ok. once it's merged, can we add additional changes later?

**Comment by Snugug** [comment]
Yup, we can iterate on everything.

**Comment by Snugug** [comment]
Resolved by #133
